import { useEffect, useRef } from 'react';
import { toast } from 'react-toastify';
import { useUser } from '@/hooks/useUser';
import { useEvolutionRuntimeStore } from '@/stores/evolutionRuntimeStore';
import { useEvolutionGraphStore } from '@/stores/evolutionGraphStore';
import { useEvolutionSettingsStore } from '@/stores/evolutionSettingsStore';
import { evolutionGraphApi } from '@/services/evolutionGraphApi';
import { API_BASE_URL } from '@/env';
import { renderHtmlToPngBase64 } from '@/utils/evolutionPreview';
import type { EvolutionWebSocketMessage } from '@/types/evolution';

const appendUserId = (url: string, userId?: string) => {
  if (!userId) return url;
  const separator = url.includes('?') ? '&' : '?';
  return `${url}${separator}user_id=${encodeURIComponent(userId)}`;
};

export function useEvolutionWebSocket() {
  const { user } = useUser();
  const websocketUrl = useEvolutionRuntimeStore((s) => s.websocketUrl);
  const setSocketStatus = useEvolutionRuntimeStore((s) => s.setSocketStatus);
  const setProgress = useEvolutionRuntimeStore((s) => s.setProgress);
  const setGeneration = useEvolutionRuntimeStore((s) => s.setGeneration);
  const setStatus = useEvolutionRuntimeStore((s) => s.setStatus);
  const setError = useEvolutionRuntimeStore((s) => s.setError);
  const setLastEvent = useEvolutionRuntimeStore((s) => s.setLastEvent);
  const reconnectToken = useEvolutionRuntimeStore((s) => s.reconnectToken);
  const runId = useEvolutionGraphStore((s) => s.runId);
  const addNode = useEvolutionGraphStore((s) => s.addNode);
  const updateNode = useEvolutionGraphStore((s) => s.updateNode);
  const cachePreviewsEnabled = useEvolutionSettingsStore((s) =>
    Boolean(s.evolutionInputs.cachePreviews ?? true)
  );
  const cachePreviewsRef = useRef(cachePreviewsEnabled);
  const autoGeneratedThumbnailsRef = useRef<Set<string>>(new Set());
  const socketRef = useRef<WebSocket | null>(null);
  const reconnectAttemptsRef = useRef(0);
  const reconnectTimeoutRef = useRef<number | null>(null);
  const reconnectingRef = useRef(false);

  const MAX_RECONNECT_ATTEMPTS = 5;
  const BASE_RECONNECT_DELAY = 1000;

  useEffect(() => {
    cachePreviewsRef.current = cachePreviewsEnabled;
  }, [cachePreviewsEnabled]);

  useEffect(() => {
    autoGeneratedThumbnailsRef.current = new Set();
  }, [runId]);

  useEffect(() => {
    if (!websocketUrl) return;

    let cancelled = false;

    const clearReconnectTimeout = () => {
      if (reconnectTimeoutRef.current) {
        window.clearTimeout(reconnectTimeoutRef.current);
        reconnectTimeoutRef.current = null;
      }
    };

    const connect = () => {
      if (cancelled) return;
      const userId = user?.id;
      const resolvedUrl = appendUserId(websocketUrl, userId);
      const socket = new WebSocket(resolvedUrl);
      socketRef.current = socket;
      setSocketStatus('connecting');
      reconnectingRef.current = false;

      socket.onopen = () => {
        if (cancelled) return;
        reconnectAttemptsRef.current = 0;
        setSocketStatus('connected');
      };

      const toBase64 = (value: string) => {
        try {
          return btoa(unescape(encodeURIComponent(value)));
        } catch {
          return btoa(value);
        }
      };

      const resolveAssetUrl = (assetId?: number | null) => {
        if (!assetId) return null;
        return `${API_BASE_URL}/evolution-graph/assets/${assetId}`;
      };

      const persistDescendant = async (
        payload: Record<string, unknown>
      ): Promise<void> => {
        if (!runId) return;

        const nodeId = String(payload.node_id ?? payload.id ?? '');
        if (!nodeId) return;

        try {
          const cachePreviews = cachePreviewsRef.current;
          const html =
            typeof payload.html === 'string' ? payload.html : undefined;
          let thumbnailBase64 =
            cachePreviews && typeof payload.thumbnail_base64 === 'string'
              ? payload.thumbnail_base64
              : undefined;
          const generation = Number(payload.generation ?? 0);
          const status = String(payload.status ?? 'evaluating');
          const parentNodeId =
            payload.parent_id != null ? String(payload.parent_id) : null;
          const fitness =
            typeof payload.fitness === 'number' ? payload.fitness : null;
          const score = typeof payload.score === 'number' ? payload.score : null;
          const label = typeof payload.label === 'string' ? payload.label : null;
          const metadata =
            payload.metadata && typeof payload.metadata === 'object'
              ? (payload.metadata as Record<string, unknown>)
              : null;

          let htmlAssetId: number | null = null;
          let thumbnailAssetId: number | null = null;
          let resolvedThumbnailUrl: string | null = null;

          if (html) {
            const asset = await evolutionGraphApi.createAsset({
              runId,
              kind: 'html',
              contentType: 'text/html',
              dataBase64: toBase64(html),
            });
            htmlAssetId = asset.id;
          }

          if (
            cachePreviews &&
            !thumbnailBase64 &&
            html &&
            !autoGeneratedThumbnailsRef.current.has(nodeId)
          ) {
            autoGeneratedThumbnailsRef.current.add(nodeId);
            const renderedThumbnail = await renderHtmlToPngBase64(html, {
              width: 1024,
              height: 768,
              backgroundColor: '#ffffff',
            });
            thumbnailBase64 = renderedThumbnail ?? undefined;
          }

          if (cachePreviews && thumbnailBase64) {
            const asset = await evolutionGraphApi.createAsset({
              runId,
              kind: 'thumbnail',
              contentType: 'image/png',
              dataBase64: thumbnailBase64,
            });
            thumbnailAssetId = asset.id;
            resolvedThumbnailUrl = resolveAssetUrl(asset.id);
          }

          const record = await evolutionGraphApi.upsertNode({
            runId,
            nodeId,
            parentNodeId,
            generation,
            status,
            fitness,
            score,
            label,
            htmlAssetId,
            thumbnailAssetId,
            metadata,
          });

          addNode({
            id: record.nodeId,
            parentId: record.parentNodeId ?? null,
            generation: record.generation,
            status: record.status as 'evaluating' | 'survived' | 'killed',
            fitness: record.fitness ?? null,
            score: record.score ?? null,
            label: record.label ?? undefined,
            html: html ?? undefined,
            htmlUrl: resolveAssetUrl(record.htmlAssetId),
            thumbnailUrl: cachePreviews
              ? resolvedThumbnailUrl ?? resolveAssetUrl(record.thumbnailAssetId)
              : null,
            metadata: record.metadata ?? undefined,
            createdAt: record.createdAt,
            spawnedAt: Date.now(),
          });
        } catch {
          // Ignore persistence errors; realtime graph updates still render.
        }
      };

      socket.onmessage = (event) => {
        try {
          const message = JSON.parse(event.data) as EvolutionWebSocketMessage;
          setLastEvent(message);

          switch (message.type) {
            case 'generation_start': {
              const generation = Number(message.data.generation ?? 0);
              const progress = Number(message.data.progress ?? 0);
              setProgress(progress, `Generation ${generation} started`);
              break;
            }
            case 'progress_update': {
              const progress = Number(message.data.progress ?? 0);
              const status = String(message.data.status ?? 'Running');
              setProgress(progress, status);
              break;
            }
            case 'design_evaluated': {
              const payload = message.data as Record<string, unknown>;
              const nodeId =
                typeof payload.node_id === 'string'
                  ? payload.node_id
                  : typeof payload.id === 'string'
                    ? payload.id
                    : '';
              if (!nodeId) break;
              updateNode(nodeId, {
                status: String(payload.status ?? 'evaluating') as
                  | 'evaluating'
                  | 'survived'
                  | 'killed',
                fitness:
                  typeof payload.fitness === 'number' ? payload.fitness : null,
                score: typeof payload.score === 'number' ? payload.score : null,
              });
              break;
            }
            case 'generation_complete': {
              const generation = Number(message.data.generation ?? 0);
              const fitness = Number(message.data.fitness ?? 0);
              setGeneration(generation, fitness);
              break;
            }
            case 'complete': {
              setStatus('completed');
              setProgress(100, 'Evolution complete');
              break;
            }
            case 'evolution_complete': {
              setStatus('completed');
              setProgress(100, 'Evolution complete');
              break;
            }
            case 'error': {
              const errorMessage =
                typeof message.data.error === 'string'
                  ? message.data.error
                  : 'Evolution error';
              setError(errorMessage);
              break;
            }
            case 'descendant_created': {
              const payload = message.data as Record<string, unknown>;
              const cachePreviews = cachePreviewsRef.current;
              const nodeId =
                typeof payload.node_id === 'string'
                  ? payload.node_id
                  : typeof payload.id === 'string'
                    ? payload.id
                    : '';
              if (!nodeId) break;
              addNode({
                id: nodeId,
                parentId:
                  payload.parent_id != null ? String(payload.parent_id) : null,
                generation: Number(payload.generation ?? 0),
                status:
                  (payload.status as 'evaluating' | 'survived' | 'killed') ??
                  'evaluating',
                fitness:
                  typeof payload.fitness === 'number' ? payload.fitness : null,
                score: typeof payload.score === 'number' ? payload.score : null,
                label: typeof payload.label === 'string' ? payload.label : null,
                html: typeof payload.html === 'string' ? payload.html : null,
                thumbnailUrl:
                  cachePreviews && typeof payload.thumbnail_url === 'string'
                    ? payload.thumbnail_url
                    : null,
                metadata:
                  payload.metadata && typeof payload.metadata === 'object'
                    ? (payload.metadata as Record<string, unknown>)
                    : null,
                spawnedAt: Date.now(),
              });
              void persistDescendant(payload);
              break;
            }
            case 'descendant_status': {
              const payload = message.data as Record<string, unknown>;
              const nodeId =
                typeof payload.node_id === 'string'
                  ? payload.node_id
                  : typeof payload.id === 'string'
                    ? payload.id
                    : '';
              if (!nodeId) break;
              updateNode(nodeId, {
                status: String(payload.status ?? 'evaluating') as
                  | 'evaluating'
                  | 'survived'
                  | 'killed',
                fitness:
                  typeof payload.fitness === 'number' ? payload.fitness : null,
                score: typeof payload.score === 'number' ? payload.score : null,
              });
              void persistDescendant(payload);
              break;
            }
            default:
              console.debug('Unhandled evolution event', message.type, message);
              break;
          }
        } catch (error) {
          setError(
            error instanceof Error
              ? error.message
              : 'Failed to parse evolution update'
          );
        }
      };

      const scheduleReconnect = () => {
        if (cancelled || reconnectingRef.current) return;
        if (reconnectAttemptsRef.current >= MAX_RECONNECT_ATTEMPTS) {
          setSocketStatus('error');
          return;
        }
        reconnectingRef.current = true;
        reconnectAttemptsRef.current += 1;
        if (reconnectAttemptsRef.current === 1) {
          toast.info('Reconnecting to evolution updates...');
        }
        const delay = Math.min(
          BASE_RECONNECT_DELAY * 2 ** (reconnectAttemptsRef.current - 1),
          15000
        );
        clearReconnectTimeout();
        setSocketStatus('connecting');
        reconnectTimeoutRef.current = window.setTimeout(() => {
          reconnectingRef.current = false;
          connect();
        }, delay);
      };

      socket.onerror = () => {
        if (cancelled) return;
        setSocketStatus('error');
        try {
          socket.close();
        } catch {
          // ignore
        }
      };

      socket.onclose = () => {
        if (cancelled) return;
        setSocketStatus('disconnected');
        scheduleReconnect();
      };
    };

    connect();

    return () => {
      cancelled = true;
      clearReconnectTimeout();
      const socket = socketRef.current;
      if (socket) {
        socket.close();
      }
      socketRef.current = null;
      reconnectAttemptsRef.current = 0;
      reconnectingRef.current = false;
    };
  }, [
    websocketUrl,
    user?.id,
    reconnectToken,
    runId,
    addNode,
    updateNode,
    setSocketStatus,
    setProgress,
    setGeneration,
    setStatus,
    setError,
    setLastEvent,
  ]);
}
