default:
  openevolve_base_url: "http://localhost:8000"
  openevolve_api_key: "your-api-key"
  model_name: "gpt-4"
  api_base: "https://api.openai.com/v1"
  temperature: 0.7
  top_p: 0.95
  max_tokens: 4096
  max_iterations: 100
  population_size: 10
  num_islands: 1
  migration_interval: 50
  migration_rate: 0.1
  archive_size: 100
  elite_ratio: 0.1
  exploration_ratio: 0.2
  exploitation_ratio: 0.7
  checkpoint_interval: 10
  language: "python"
  file_suffix: ".py"
  reasoning_effort: "medium"
  feature_dimensions: ["complexity", "diversity"]
  feature_bins: 10
  diversity_metric: "edit_distance"
  frequency_penalty: 0.0
  presence_penalty: 0.0
  seed: 42

production:
  openevolve_base_url: "https://api.openevolve.com"
  openevolve_api_key: "your-production-api-key"