/**
 * RAGBitsGenerationBubble - RAG Generation Bubble for BubbleLab
 *
 * This bubble generates responses using retrieved context from RAGBits
 */

import { BaseBubble } from './BaseBubble';
import { RAGBitsGenerationConfig, RAGBitsGenerationInput, RAGBitsGenerationOutput } from '../types';
import { RAGBitsDocumentProcessor } from '../../knowledge_engine/ragbits_document_processor';
import { Logger, generateId } from '../utils/common.utils';

export class RAGBitsGenerationBubble extends BaseBubble<
  RAGBitsGenerationConfig,
  RAGBitsGenerationInput,
  RAGBitsGenerationOutput
> {
  private processor: RAGBitsDocumentProcessor;

  constructor(config: RAGBitsGenerationConfig) {
    super(config);
    this.processor = new RAGBitsDocumentProcessor();
  }

  async initialize(): Promise<void> {
    await this.processor.initialize();
    this.logger.info('RAGBitsGenerationBubble initialized');
  }

  async action(input: RAGBitsGenerationInput): Promise<RAGBitsGenerationOutput> {
    const startTime = Date.now();
    const operationId = generateId('generation-operation');

    this.logger.debug(`Starting generation operation ${operationId} for query: "${input.query.substring(0, 50)}..."`);

    try {
      // Build the prompt with context
      let prompt = '';

      // Add system prompt if available
      if (this.config.systemPrompt) {
        prompt += `System: ${this.config.systemPrompt}\n\n`;
      }

      // Add context if provided
      if (input.context && input.context.length > 0) {
        prompt += 'Context:\n';
        input.context.forEach((ctx, idx) => {
          prompt += `[${idx + 1}] ${ctx.content}\n`;
        });
        prompt += '\n';
      }

      // Add user query
      prompt += `User Query: ${input.query}\n`;

      // Add custom prompt if provided
      if (input.customPrompt) {
        prompt += `\nAdditional Instructions: ${input.customPrompt}`;
      }

      this.logger.debug(`Built prompt with ${prompt.length} characters for operation ${operationId}`);

      // In a real implementation, this would call the Ragbits LLM generation functionality
      // For now, we'll simulate the generation
      const response = await this.generateResponse(prompt, operationId);

      const executionTime = Date.now() - startTime;

      this.logger.info(`Generation operation ${operationId} completed in ${executionTime}ms`);

      return {
        success: true,
        response,
        executionTime,
        tokensUsed: {
          input: this.countTokens(prompt),
          output: this.countTokens(response),
          total: this.countTokens(prompt) + this.countTokens(response)
        },
        error: undefined
      };
    } catch (error) {
      const executionTime = Date.now() - startTime;
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';

      this.logger.error(`Generation operation ${operationId} failed after ${executionTime}ms: ${errorMessage}`);

      return {
        success: false,
        response: '',
        executionTime,
        error: errorMessage
      };
    }
  }

  /**
   * Add context formatting logic
   */
  private formatContext(context: RAGBitsGenerationInput['context']): string {
    if (!context || context.length === 0) {
      return '';
    }

    return context.map((ctx, idx) => `[${idx + 1}] ${ctx.content}`).join('\n');
  }

  /**
   * Add prompt construction logic
   */
  private constructPrompt(input: RAGBitsGenerationInput): string {
    let prompt = '';

    // Add system prompt if available
    if (this.config.systemPrompt) {
      prompt += `System: ${this.config.systemPrompt}\n\n`;
    }

    // Add context if provided
    if (input.context && input.context.length > 0) {
      prompt += 'Context:\n';
      prompt += this.formatContext(input.context);
      prompt += '\n';
    }

    // Add user query
    prompt += `User Query: ${input.query}\n`;

    // Add custom prompt if provided
    if (input.customPrompt) {
      prompt += `\nAdditional Instructions: ${input.customPrompt}`;
    }

    return prompt;
  }

  /**
   * Add LLM integration logic
   */
  private async generateResponse(prompt: string, operationId: string): Promise<string> {
    // In a real implementation, this would call the actual LLM
    // For simulation purposes, we'll return a contextual response
    return `Based on the provided context and query "${prompt.split('User Query: ')[1]?.split('\n')[0] || 'the query'}", here is a generated response. In a real implementation, this would be generated by the Ragbits LLM with the provided context.`;
  }

  /**
   * Count tokens in text (approximate)
   */
  private countTokens(text: string): number {
    // Rough approximation: 1 token ~ 4 characters
    return Math.ceil(text.length / 4);
  }

  /**
   * Override error handling for generation failures
   */
  override handleError(error: unknown, context?: string): Error {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    const fullContext = context ? ` in ${context}` : '';
    this.logger.error(`Generation error${fullContext}: ${errorMessage}`);
    return new Error(errorMessage);
  }

  /**
   * Add logging for generation process
   */
  private logGenerationProgress(progress: number, operationId: string): void {
    this.logger.debug(`Generation operation ${operationId} progress: ${progress}%`);
  }

  /**
   * Add metrics collection for generation
   */
  private collectMetrics(result: RAGBitsGenerationOutput, executionTime: number): void {
    // In a real implementation, this would collect metrics
    this.logger.debug(`Collected metrics for generation: ${result.tokensUsed?.total} tokens in ${executionTime}ms`);
  }

  /**
   * Generate response with streaming support
   */
  async generateStream(input: RAGBitsGenerationInput, onChunk: (chunk: string) => void): Promise<RAGBitsGenerationOutput> {
    // In a real implementation, this would support streaming responses
    const result = await this.action(input);
    onChunk(result.response || '');
    return result;
  }

  /**
   * Generate with specific parameters
   */
  async generateWithParams(query: string, context: RAGBitsGenerationInput['context'], params: {
    temperature?: number;
    maxTokens?: number;
    systemPrompt?: string;
  }): Promise<RAGBitsGenerationOutput> {
    // Temporarily override config with provided params
    const originalConfig = { ...this.config };

    if (params.temperature !== undefined) this.config.temperature = params.temperature;
    if (params.maxTokens !== undefined) this.config.maxTokens = params.maxTokens;
    if (params.systemPrompt !== undefined) this.config.systemPrompt = params.systemPrompt;

    const result = await this.action({ query, context });

    // Restore original config
    this.config = originalConfig;

    return result;
  }
}