/**
 * RAGBitsGenerationBubble - RAG Generation Bubble for BubbleLab
 *
 * This bubble generates responses using retrieved context from RAGBits
 */

import { BaseBubble } from './BaseBubble';
import { RAGBitsGenerationConfig, RAGBitsGenerationInput, RAGBitsGenerationOutput } from '../types';
import { RAGBitsDocumentProcessor } from '../../knowledge_engine/ragbits_document_processor';

export class RAGBitsGenerationBubble extends BaseBubble<
  RAGBitsGenerationConfig,
  RAGBitsGenerationInput,
  RAGBitsGenerationOutput
> {
  private processor: RAGBitsDocumentProcessor;

  constructor(config: RAGBitsGenerationConfig) {
    super(config);
    this.processor = new RAGBitsDocumentProcessor();
  }

  async initialize(): Promise<void> {
    await this.processor.initialize();
    console.log('RAGBitsGenerationBubble initialized');
  }

  async action(input: RAGBitsGenerationInput): Promise<RAGBitsGenerationOutput> {
    try {
      const startTime = Date.now();

      // Build the prompt with context
      let prompt = '';

      // Add system prompt if available
      if (this.config.systemPrompt) {
        prompt += `System: ${this.config.systemPrompt}\n\n`;
      }

      // Add context if provided
      if (input.context && input.context.length > 0) {
        prompt += 'Context:\n';
        input.context.forEach((ctx, idx) => {
          prompt += `[${idx + 1}] ${ctx.content}\n`;
        });
        prompt += '\n';
      }

      // Add user query
      prompt += `User Query: ${input.query}\n`;

      // Add custom prompt if provided
      if (input.customPrompt) {
        prompt += `\nAdditional Instructions: ${input.customPrompt}`;
      }

      // For now, we'll simulate the generation since we don't have direct access to Ragbits LLM
      // In a real implementation, this would call the Ragbits LLM generation functionality
      const response = `This is a simulated response based on the query: "${input.query}". In a real implementation, this would be generated by the Ragbits LLM with the provided context.`;

      const executionTime = Date.now() - startTime;

      return {
        success: true,
        response,
        executionTime,
        tokensUsed: {
          input: prompt.length,
          output: response.length,
          total: prompt.length + response.length
        },
        error: undefined
      };
    } catch (error) {
      console.error('RAGBitsGenerationBubble error:', error);
      return {
        success: false,
        response: '',
        executionTime: 0,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }
}