# Model: BOMDetailExtractionModel
# Generated by Case 2 Hierarchical Extraction

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class BOMDetailExtractionModel(BaseModel):
    """Generated Pydantic model for Case 2 extraction"""
    materialnumber: str = Field(default=..., description="Unique identifier for the part; matches Material Number from PO.")
    typepartdesignation: str = Field(default=..., description="Technical type or designation of the part.")
    dimensions: str = Field(default=..., description="Physical dimensions of the part.")