# Extraction prompt
# Generated by Case 2 Hierarchical Extraction

extraction_prompt = """
TASK: BOM Detail Extraction

EXTRACTION TASK:
Extracts technical details for each part from the BOM, including ID, Type/Part Designation, and Dimensions.

EMBEDDED PYDANTIC MODELS:
```python
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class BOMDetailExtractionModel(BaseModel):
    materialnumber: str = Field(description="Unique identifier for the part; matches Material Number from PO.")
    typepartdesignation: str = Field(description="Technical type or designation of the part.")
    dimensions: str = Field(description="Physical dimensions of the part.")
```

CRITICAL EXTRACTION RULES:
1. ACCURACY & VERIFICATION:
   - Extract information ONLY from the provided text
   - Never fabricate, infer, or guess any information
   - Use 'n/a' for any fields where information is not explicitly stated
   - Verify all extracted data against the source text
   - Maintain exact values, dates, and numerical figures as written

2. DATA HANDLING:
   - For dates: Use DD-MM-YYYY format when possible
   - For numbers: Preserve original precision and units
   - For text: Maintain original spelling and capitalization
   - For lists: Extract all relevant items, remove duplicates
   - For enums: Choose ONLY from the specified options
   - For fields whose length exceeds 30 words, summarize into less than 30 words with key phrases separated by semi-colons

3. FIELD VALIDATION:
   - Enum fields must match one of the specified values exactly
   - List fields should contain valid, non-empty items
   - Numerical fields should be valid numbers in correct format

4. QUALITY ASSURANCE:
   - Double-check all extracted information against source
   - Ensure no information is duplicated across fields
   - Verify that field types match the expected data types
   - Confirm that all required fields are addressed
   - Validate that enum selections are from available options

OUTPUT FORMAT:
Return the extracted information as a JSON object that exactly matches the BOMDetailExtractionModel structure shown above.

CRITICAL: All JSON field names MUST be in snake_case format (lowercase with underscores) to match the model exactly.
For example: "field_name", "delivery_date", "type_designation" - NOT "Field Name", "Delivery Date", "Type Designation"

Example output structure:
```json
{
  "field_name_1": "extracted_value_or_n/a",
  "field_name_2": ["list", "of", "values"],
  "field_name_3": "enum_option_or_n/a"
}
```

VALIDATION CHECKLIST:
Before returning your response, verify:
- All required fields are populated or marked 'n/a'
- All enum fields contain valid options only
- All numerical fields contain valid numbers
- All date fields follow proper format
- No information is fabricated or inferred
- JSON structure matches the model exactly
- Field names match the model exactly (snake_case)
- Data types are appropriate for each field

FINAL INSTRUCTIONS:
- Process the document systematically
- Extract information field by field as specified above
- Maintain accuracy over completeness
- When in doubt, use 'n/a' rather than guessing
- Return only the JSON object with extracted data
- Ensure the output can be parsed as valid JSON

DOCUMENTS TO PROCESS:
{documents}

Return the extracted information as a JSON array of objects (if multiple items) or single JSON object matching the BOMDetailExtractionModel structure.
        """
