"""
Lean 4 Adversarial Evolution Integration

This module implements adversarial evolution for Lean 4 proofs, enabling:
- Red team vs Blue team competition for proof improvement
- Co-evolution of proof strategies and counterexamples
- Adversarial robustness testing of mathematical proofs
- Integration with LeanAide for proof verification

The system uses an adversarial approach where:
- Blue Team: Generates proof strategies using different approaches
- Red Team: Finds counterexamples and flaws in proofs
- Arena: Manages competition and tracks performance
- Co-evolution: Both teams adapt based on adversarial feedback
"""

import json
import time
import logging
import re
from typing import Dict, List, Any, Optional, Tuple, Callable
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime, timezone
from pathlib import Path
import tempfile
import subprocess

# Configure logging
logger = logging.getLogger(__name__)

# Import LeanAide components
try:
    from LeanAide.leanaide_client import LeanAideClient, LeanProof, LeanTactic, ProofContext
    LEANAIDE_AVAILABLE = True
except ImportError:
    LEANAIDE_AVAILABLE = False
    logger.warning("LeanAide not available - some features will be limited")

    # Define stubs when LeanAide is not available
    @dataclass
    class ProofContext:
        """Stub ProofContext for when LeanAide is not available."""
        available_lemmas: List[str] = field(default_factory=list)
        definitions: Dict[str, str] = field(default_factory=dict)
        theorems: List[str] = field(default_factory=list)

    @dataclass
    class LeanProof:
        """Stub LeanProof for when LeanAide is not available."""
        theorem_name: str = ""
        theorem_statement: str = ""
        tactics: List[Any] = field(default_factory=list)

    @dataclass
    class LeanTactic:
        """Stub LeanTactic for when LeanAide is not available."""
        name: str = ""
        arguments: List[str] = field(default_factory=list)

    class LeanAideClient:
        """Stub LeanAideClient for when LeanAide is not available."""
        pass

# Import adversarial components
try:
    from red_team import RedTeam, IssueFinding, IssueCategory
    from blue_team import BlueTeam, FixSuggestion, FixType
    ADVERSARIAL_AVAILABLE = True
except ImportError:
    ADVERSARIAL_AVAILABLE = False
    logger.warning("Adversarial teams not available - using simplified implementation")


class ProofApproach(Enum):
    """Different approaches to generating proofs"""
    CONSTRUCTIVE = "constructive"  # Build proof explicitly
    CLASSICAL = "classical"  # Use classical reasoning
    COMPUTATIONAL = "computational"  # Use computation/decidability
    INDIRECT = "indirect"  # Proof by contradiction
    STRUCTURAL = "structural"  # Exploit structure of objects
    ALGEBRAIC = "algebraic"  # Use algebraic manipulations


class CritiqueSeverity(Enum):
    """Severity levels for proof critiques"""
    CRITICAL = "critical"  # Proof is invalid
    HIGH = "high"  # Significant gap or flaw
    MEDIUM = "medium"  # Minor issue or weakness
    LOW = "low"  # Style or clarity issue"
    INFO = "info"  # Suggestion for improvement"


class CounterexampleStatus(Enum):
    """Status of counterexample validation"""
    VALID = "valid"  # Counterexample disproves theorem
    INVALID = "invalid"  # Counterexample doesn't work
    INCONCLUSIVE = "inconclusive"  # Cannot verify
    PENDING = "pending"  # Awaiting verification


@dataclass
class LeanProofStrategy:
    """A proof strategy generated by the Blue Team"""
    approach: ProofApproach
    tactics: List[str]
    reasoning: str
    estimated_complexity: float  # 0-1 scale
    confidence: float  # 0-1 scale
    lean_code: str  # Actual Lean 4 code
    dependencies: List[str] = field(default_factory=list)
    performance_history: Dict[str, float] = field(default_factory=dict)


@dataclass
class ProofCritique:
    """A critique of a proof from the Red Team"""
    issue_type: str  # "logic_gap", "invalid_step", "missing_case", etc.
    description: str
    severity: CritiqueSeverity
    location: Optional[str] = None  # Where in the proof
    counterexample_suggestion: Optional[str] = None
    confidence: float = 0.8
    fix_suggestion: Optional[str] = None


@dataclass
class LeanCounterexample:
    """A counterexample to a theorem or proof"""
    theorem: str
    counterexample_code: str  # Lean 4 code
    description: str
    status: CounterexampleStatus = CounterexampleStatus.PENDING
    verification_output: Optional[str] = None
    disproves_theorem: bool = False
    confidence: float = 0.8


@dataclass
class RoundResult:
    """Result of an adversarial round"""
    round_number: int
    blue_strategy: LeanProofStrategy
    red_critique: List[ProofCritique]
    counterexamples: List[LeanCounterexample]
    blue_survived: bool  # Did proof survive attacks?
    red_score: float  # 0-1, how successful red team was
    blue_score: float  # 0-1, how robust proof was
    improvements_made: List[str] = field(default_factory=list)
    time_taken: float = 0.0


@dataclass
class AdversarialStatistics:
    """Statistics tracking adversarial performance"""
    total_rounds: int = 0
    blue_wins: int = 0
    red_wins: int = 0
    draws: int = 0
    blue_success_rate: float = 0.0
    red_success_rate: float = 0.0
    average_proof_complexity: float = 0.0
    unique_counterexamples_found: int = 0
    most_effective_approach: Optional[ProofApproach] = None
    approach_success_rates: Dict[ProofApproach, float] = field(default_factory=dict)


class LeanBlueTeamAgent:
    """
    Blue Team agent that generates Lean 4 proof strategies.

    Uses multiple approaches:
    - Constructive: Build explicit witnesses
    - Classical: Use classical logic principles
    - Computational: Leverage decidability
    - Indirect: Proof by contradiction
    - Structural: Exploit mathematical structure
    - Algebraic: Use algebraic properties

    Learns from successful proofs and adapts tactics based on feedback.
    """

    def __init__(self, name: str = "BlueTeam",
                 client: Optional['LeanAideClient'] = None,
                 approaches: List[ProofApproach] = None):
        self.name = name
        self.client = client
        self.approaches = approaches or list(ProofApproach)
        self.performance_history: Dict[ProofApproach, List[float]] = {
            approach: [] for approach in self.approaches
        }
        self.tactic_success_rates: Dict[str, float] = {}
        self.learning_rate = 0.1

    def generate_proof_strategy(self,
                               theorem: str,
                               context: ProofContext,
                               previous_critiques: List[ProofCritique] = None,
                               approach: Optional[ProofApproach] = None) -> LeanProofStrategy:
        """
        Generate a proof strategy for the given theorem.

        Args:
            theorem: The theorem statement to prove
            context: Proof context with available definitions and lemmas
            previous_critiques: Critiques from previous rounds to learn from
            approach: Specific approach to use, or None to select adaptively

        Returns:
            LeanProofStrategy with tactics and Lean code
        """
        start_time = time.time()

        # Select approach based on performance history
        if approach is None:
            approach = self._select_approach(theorem, context, previous_critiques)

        # Generate tactics based on approach
        tactics = self._generate_tactics(theorem, context, approach, previous_critiques)

        # Build reasoning explanation
        reasoning = self._explain_approach(theorem, context, approach, tactics)

        # Estimate complexity
        complexity = self._estimate_complexity(theorem, tactics, context)

        # Generate actual Lean 4 code
        lean_code = self._generate_lean_code(theorem, tactics, context)

        # Calculate confidence based on approach and tactics
        confidence = self._calculate_confidence(approach, tactics, context)

        # Extract dependencies
        dependencies = self._extract_dependencies(lean_code, context)

        strategy = LeanProofStrategy(
            approach=approach,
            tactics=tactics,
            reasoning=reasoning,
            estimated_complexity=complexity,
            confidence=confidence,
            lean_code=lean_code,
            dependencies=dependencies,
            performance_history=self._get_performance_history(approach)
        )

        logger.info(f"Generated {approach.value} proof strategy in {time.time() - start_time:.2f}s")
        return strategy

    def _select_approach(self,
                        theorem: str,
                        context: ProofContext,
                        critiques: List[ProofCritique]) -> ProofApproach:
        """Select the best approach based on theorem characteristics and history"""
        # Analyze theorem to suggest best approach
        theorem_lower = theorem.lower()

        # Heuristic approach selection
        if any(word in theorem_lower for word in ["exists", "construct", "find", "example"]):
            preferred = ProofApproach.CONSTRUCTIVE
        elif any(word in theorem_lower for word in ["not", "false", "contradiction", "impossible"]):
            preferred = ProofApproach.INDIRECT
        elif any(word in theorem_lower for word in ["compute", "decide", "eval", "finite"]):
            preferred = ProofApproach.COMPUTATIONAL
        elif any(word in theorem_lower for word in ["struct", "type", "inductive", "rec"]):
            preferred = ProofApproach.STRUCTURAL
        elif any(word in theorem_lower for word in ["equal", "equiv", "iso", "map"]):
            preferred = ProofApproach.ALGEBRAIC
        else:
            preferred = ProofApproach.CLASSICAL

        # Consider past performance
        if self.performance_history[preferred]:
            avg_success = sum(self.performance_history[preferred]) / len(self.performance_history[preferred])
            if avg_success < 0.5:
                # Try alternative approaches
                alternatives = [a for a in self.approaches if a != preferred]
                for alt in alternatives:
                    if self.performance_history[alt]:
                        alt_success = sum(self.performance_history[alt]) / len(self.performance_history[alt])
                        if alt_success > avg_success:
                            return alt

        return preferred

    def _generate_tactics(self,
                         theorem: str,
                         context: ProofContext,
                         approach: ProofApproach,
                         critiques: List[ProofCritique]) -> List[str]:
        """Generate appropriate tactics for the approach"""
        # Base tactics for each approach
        approach_tactics = {
            ProofApproach.CONSTRUCTIVE: [
                "constructor", "exists", "use", "refine", "have", "apply"
            ],
            ProofApproach.CLASSICAL: [
                "by_cases", "push_neg", "classical", "apply", "exact"
            ],
            ProofApproach.COMPUTATIONAL: [
                "decide", "rfl", "norm_num", "simp", "compute"
            ],
            ProofApproach.INDIRECT: [
                "by_contradiction", "push_neg", "apply", "exact", "contrapose"
            ],
            ProofApproach.STRUCTURAL: [
                "induction", "cases", "split", "refl", "congr"
            ],
            ProofApproach.ALGEBRAIC: [
                "simp", "ring", "abel", "linarith", "field_simp"
            ]
        }

        base_tactics = approach_tactics.get(approach, ["apply", "exact"])

        # Adjust based on critiques
        if critiques:
            for critique in critiques:
                if "missing case" in critique.description.lower():
                    if "cases" not in base_tactics:
                        base_tactics.append("cases")
                elif "computation" in critique.description.lower():
                    if "simp" not in base_tactics:
                        base_tactics.append("simp")
                elif "induction" in critique.description.lower():
                    if "induction" not in base_tactics:
                        base_tactics.append("induction")

        return base_tactics

    def _explain_approach(self,
                         theorem: str,
                         context: ProofContext,
                         approach: ProofApproach,
                         tactics: List[str]) -> str:
        """Generate natural language explanation of the approach"""
        explanations = {
            ProofApproach.CONSTRUCTIVE:
                f"Construct explicit witness for {theorem}. Using tactics: {', '.join(tactics[:3])}",
            ProofApproach.CLASSICAL:
                f"Apply classical reasoning principles to prove {theorem}",
            ProofApproach.COMPUTATIONAL:
                f"Use computational methods and normalization for {theorem}",
            ProofApproach.INDIRECT:
                f"Proof by contradiction: assume negation and derive false",
            ProofApproach.STRUCTURAL:
                f"Exploit structural properties through induction/cases analysis",
            ProofApproach.ALGEBRAIC:
                f"Use algebraic manipulations and simplification tactics"
        }

        base = explanations.get(approach, "Standard proof approach")

        # Add context-specific details
        if context and context.available_lemmas:
            base += f"\nAvailable lemmas: {len(context.available_lemmas)}"
            if context.available_lemmas:
                base += f" (e.g., {context.available_lemmas[0]})"

        return base

    def _estimate_complexity(self,
                           theorem: str,
                           tactics: List[str],
                           context: ProofContext) -> float:
        """Estimate proof complexity on 0-1 scale"""
        complexity = 0.3  # Base complexity

        # Increase based on theorem length
        complexity += min(0.2, len(theorem) / 500)

        # Increase based on number of tactics
        complexity += min(0.3, len(tactics) / 20)

        # Increase if structural induction is needed
        if any(t in tactics for t in ["induction", "cases"]):
            complexity += 0.2

        # Decrease if computational decision is possible
        if "decide" in tactics:
            complexity -= 0.1

        return min(1.0, max(0.0, complexity))

    def _generate_lean_code(self,
                           theorem: str,
                           tactics: List[str],
                           context: ProofContext) -> str:
        """
        Generate Lean 4 proof code using tactics.

        If LeanAide client is available, use it to generate proof.
        Otherwise, return a template with tactics.
        """
        if LEANAIDE_AVAILABLE and self.client:
            try:
                # Use LeanAide to generate proof
                proof = self.client.generate_proof(
                    theorem_statement=theorem,
                    context=context,
                    tactics=tactics
                )
                return proof.lean_code if proof else self._generate_template(theorem, tactics)
            except Exception as e:
                logger.warning(f"LeanAide generation failed: {e}, using template")

        return self._generate_template(theorem, tactics)

    def _generate_template(self, theorem: str, tactics: List[str]) -> str:
        """Generate a basic Lean 4 proof template"""
        template = f"""theorem {theorem} : Prop := by
  -- Proof using tactics: {', '.join(tactics[:5])}
"""

        # Add tactic applications
        indent = "  "
        for tactic in tactics[:8]:  # Limit to first 8 tactics
            template += f"{indent}{tactic}\n"

        return template

    def _calculate_confidence(self,
                             approach: ProofApproach,
                             tactics: List[str],
                             context: ProofContext) -> float:
        """Calculate confidence in this strategy"""
        base_confidence = 0.7

        # Boost confidence for approaches with good history
        if self.performance_history[approach]:
            history_success = sum(self.performance_history[approach]) / len(self.performance_history[approach])
            base_confidence = (base_confidence + history_success) / 2

        # Adjust based on tactic diversity
        tactic_diversity = len(set(tactics)) / max(1, len(tactics))
        base_confidence *= (0.8 + 0.2 * tactic_diversity)

        return min(1.0, max(0.0, base_confidence))

    def _extract_dependencies(self, lean_code: str, context: ProofContext) -> List[str]:
        """Extract dependencies from Lean code"""
        # Find imports and requires
        dependencies = []

        # Match import statements
        import_pattern = r'import\s+(\S+)'
        imports = re.findall(import_pattern, lean_code)
        dependencies.extend(imports)

        # Add context dependencies if available
        if context and context.available_lemmas:
            dependencies.extend(context.available_lemmas[:5])

        return list(set(dependencies))

    def _get_performance_history(self, approach: ProofApproach) -> Dict[str, float]:
        """Get performance history for an approach"""
        if not self.performance_history[approach]:
            return {"avg_success": 0.5, "attempts": 0}

        history = self.performance_history[approach]
        return {
            "avg_success": sum(history) / len(history),
            "attempts": len(history),
            "recent": history[-5:] if len(history) > 5 else history
        }

    def update_performance(self, approach: ProofApproach, success: float):
        """Update performance history for learning"""
        self.performance_history[approach].append(success)

        # Keep only recent history
        if len(self.performance_history[approach]) > 20:
            self.performance_history[approach] = self.performance_history[approach][-20:]

    def adapt_tactics(self, critiques: List[ProofCritique]):
        """Adapt tactic selection based on critiques"""
        for critique in critiques:
            if critique.fix_suggestion:
                # Extract suggested tactics
                suggested = re.findall(r'\b(apply|simp|induction|cases|rw)\b',
                                     critique.fix_suggestion.lower())
                for tactic in suggested:
                    if tactic not in self.tactic_success_rates:
                        self.tactic_success_rates[tactic] = 0.6
                    else:
                        self.tactic_success_rates[tactic] = min(1.0,
                            self.tactic_success_rates[tactic] + self.learning_rate * 0.1)


class LeanRedTeamAgent:
    """
    Red Team agent that critiques proofs and finds counterexamples.

    Responsibilities:
    - Analyze proof strategies for logical gaps
    - Attempt to find counterexamples to theorems
    - Identify invalid proof steps
    - Suggest improvements

    Uses multiple attack strategies:
    - Logical analysis: Check for fallacies
    - Counterexample search: Find disproving cases
    - Edge case testing: Test boundary conditions
    - Structure analysis: Check for incomplete cases
    """

    def __init__(self, name: str = "RedTeam",
                 client: Optional['LeanAideClient'] = None):
        self.name = name
        self.client = client
        self.attack_strategies = [
            "logical_analysis",
            "counterexample_search",
            "edge_case_testing",
            "structure_analysis",
            "formal_verification"
        ]
        self.successful_attacks: Dict[str, int] = {}
        self.counterexample_db: List[LeanCounterexample] = []

    def critique_proof(self,
                      strategy: LeanProofStrategy,
                      theorem: str,
                      context: ProofContext) -> List[ProofCritique]:
        """
        Critique a proof strategy and identify flaws.

        Args:
            strategy: The proof strategy to critique
            theorem: The theorem being proved
            context: Proof context

        Returns:
            List of critiques identifying issues
        """
        start_time = time.time()
        critiques = []

        # Apply different attack strategies
        for attack_strategy in self.attack_strategies:
            try:
                strategy_critiques = self._apply_attack_strategy(
                    attack_strategy, strategy, theorem, context
                )
                critiques.extend(strategy_critiques)
            except Exception as e:
                logger.warning(f"Attack strategy {attack_strategy} failed: {e}")

        # Prioritize and deduplicate critiques
        critiques = self._prioritize_critiques(critiques)

        logger.info(f"Generated {len(critiques)} critiques in {time.time() - start_time:.2f}s")
        return critiques

    def _apply_attack_strategy(self,
                              strategy_name: str,
                              proof_strategy: LeanProofStrategy,
                              theorem: str,
                              context: ProofContext) -> List[ProofCritique]:
        """Apply a specific attack strategy"""
        if strategy_name == "logical_analysis":
            return self._logical_analysis_attack(proof_strategy, theorem, context)
        elif strategy_name == "counterexample_search":
            return self._counterexample_search_attack(proof_strategy, theorem, context)
        elif strategy_name == "edge_case_testing":
            return self._edge_case_attack(proof_strategy, theorem, context)
        elif strategy_name == "structure_analysis":
            return self._structure_analysis_attack(proof_strategy, theorem, context)
        elif strategy_name == "formal_verification":
            return self._formal_verification_attack(proof_strategy, theorem, context)
        else:
            return []

    def _logical_analysis_attack(self,
                                  strategy: LeanProofStrategy,
                                  theorem: str,
                                  context: ProofContext) -> List[ProofCritique]:
        """Analyze proof for logical fallacies and gaps"""
        critiques = []

        # Check for common logical issues
        lean_code = strategy.lean_code.lower()

        # Check for incomplete case analysis
        if ("cases" in lean_code or "induction" in lean_code):
            # Look for missing cases
            if lean_code.count("case") < 2 and "induction" in lean_code:
                critiques.append(ProofCritique(
                    issue_type="missing_case",
                    description="Induction without explicit case analysis",
                    severity=CritiqueSeverity.MEDIUM,
                    location="Induction step",
                    confidence=0.7,
                    fix_suggestion="Add explicit case analysis for base and inductive steps"
                ))

        # Check for assumptions without justification
        if "sorry" in lean_code or "admit" in lean_code:
            critiques.append(ProofCritique(
                issue_type="invalid_step",
                description="Proof contains admissions or incomplete steps",
                severity=CritiqueSeverity.CRITICAL,
                location="Admitted steps",
                confidence=0.95,
                fix_suggestion="Replace all sorry/admit with actual proofs"
            ))

        # Check for circular reasoning
        if theorem.split("→")[0].lower() in lean_code[:100]:
            critiques.append(ProofCritique(
                issue_type="logic_gap",
                description="Potential circular reasoning detected",
                severity=CritiqueSeverity.HIGH,
                location="Proof opening",
                confidence=0.6,
                fix_suggestion="Ensure proof doesn't assume what it's trying to prove"
            ))

        return critiques

    def _counterexample_search_attack(self,
                                      strategy: LeanProofStrategy,
                                      theorem: str,
                                      context: ProofContext) -> List[ProofCritique]:
        """Search for counterexamples that disprove the theorem"""
        critiques = []

        # Try to construct counterexamples for edge cases
        counterexample_attempts = self._generate_counterexamples(theorem, context)

        for counterexample in counterexample_attempts:
            if self._validate_counterexample(counterexample, theorem):
                critiques.append(ProofCritique(
                    issue_type="counterexample",
                    description=f"Found counterexample: {counterexample.description}",
                    severity=CritiqueSeverity.CRITICAL,
                    counterexample_suggestion=counterexample.counterexample_code,
                    confidence=counterexample.confidence,
                    fix_suggestion="Theorem statement may need additional hypotheses"
                ))

                # Store in database
                self.counterexample_db.append(counterexample)

        return critiques

    def _edge_case_attack(self,
                         strategy: LeanProofStrategy,
                         theorem: str,
                         context: ProofContext) -> List[ProofCritique]:
        """Test edge cases and boundary conditions"""
        critiques = []

        # Check for handling of empty/corner cases
        theorem_lower = theorem.lower()

        edge_cases = [
            ("empty set", "∅", "non-empty"),
            ("zero", "0", "non-zero"),
            ("empty list", "[]", "non-empty"),
            ("unit type", "Unit", "non-unit"),
            ("false", "False", "true case")
        ]

        for case_name, case_sym, alternative in edge_cases:
            if case_name in theorem_lower:
                # Check if proof handles this edge case
                if case_sym not in strategy.lean_code:
                    critiques.append(ProofCritique(
                        issue_type="missing_case",
                        description=f"May not handle {case_name} case",
                        severity=CritiqueSeverity.MEDIUM,
                        location="Case analysis",
                        confidence=0.6,
                        fix_suggestion=f"Add explicit handling for {case_name} ({alternative} case)"
                    ))

        return critiques

    def _structure_analysis_attack(self,
                                   strategy: LeanProofStrategy,
                                   theorem: str,
                                   context: ProofContext) -> List[ProofCritique]:
        """Analyze proof structure for completeness"""
        critiques = []

        # Check for structural issues
        lean_lines = strategy.lean_code.split('\n')

        # Check if proof is too short for complex theorem
        if len(lean_lines) < 5 and len(theorem) > 100:
            critiques.append(ProofCritique(
                issue_type="logic_gap",
                description="Proof suspiciously short for theorem complexity",
                severity=CritiqueSeverity.MEDIUM,
                location="Overall structure",
                confidence=0.5,
                fix_suggestion="Expand proof with more detailed steps"
            ))

        # Check for missing by/proof markers
        if ":=" not in strategy.lean_code and "by" not in strategy.lean_code:
            critiques.append(ProofCritique(
                issue_type="invalid_step",
                description="Proof lacks proper structure markers",
                severity=CritiqueSeverity.LOW,
                location="Proof declaration",
                confidence=0.7,
                fix_suggestion="Add ':= by' or other proof structure markers"
            ))

        return critiques

    def _formal_verification_attack(self,
                                    strategy: LeanProofStrategy,
                                    theorem: str,
                                    context: ProofContext) -> List[ProofCritique]:
        """Attempt formal verification using Lean"""
        critiques = []

        if LEANAIDE_AVAILABLE and self.client:
            try:
                # Try to verify proof with Lean
                result = self.client.verify_proof(strategy.lean_code, context)

                if not result.is_valid:
                    critiques.append(ProofCritique(
                        issue_type="invalid_step",
                        description=f"Formal verification failed: {result.error_message}",
                        severity=CritiqueSeverity.CRITICAL,
                        location=result.error_location if hasattr(result, 'error_location') else None,
                        confidence=0.95,
                        fix_suggestion=result.suggestion if hasattr(result, 'suggestion') else None
                    ))
                else:
                    # Proof verified, but check for warnings
                    if hasattr(result, 'warnings') and result.warnings:
                        for warning in result.warnings:
                            critiques.append(ProofCritique(
                                issue_type="logic_gap",
                                description=f"Verification warning: {warning}",
                                severity=CritiqueSeverity.LOW,
                                confidence=0.5
                            ))

            except Exception as e:
                logger.debug(f"Formal verification failed: {e}")

        return critiques

    def _generate_counterexamples(self,
                                 theorem: str,
                                 context: ProofContext) -> List[LeanCounterexample]:
        """Generate potential counterexamples"""
        counterexamples = []

        # Parse theorem structure
        theorem_lower = theorem.lower()

        # Generate counterexamples based on theorem type
        if "forall" in theorem_lower or "∀" in theorem:
            # Universal quantifier - try to find counterexample
            counterexamples.append(LeanCounterexample(
                theorem=theorem,
                counterexample_code="-- Counterexample for universal statement",
                description="Empty set or zero value may violate property",
                confidence=0.6
            ))

        if "exists" in theorem_lower or "∃" in theorem:
            # Existential quantifier - try to show non-existence
            counterexamples.append(LeanCounterexample(
                theorem=theorem,
                counterexample_code="-- Counterexample for existential statement",
                description="May not exist for all cases",
                confidence=0.5
            ))

        if "injective" in theorem_lower or "one_to_one" in theorem_lower:
            # Injectivity - try to find collision
            counterexamples.append(LeanCounterexample(
                theorem=theorem,
                counterexample_code="-- Collision example",
                description="Function may not be injective for all inputs",
                confidence=0.7
            ))

        return counterexamples

    def _validate_counterexample(self,
                                counterexample: LeanCounterexample,
                                theorem: str) -> bool:
        """Validate if counterexample actually disproves theorem"""
        # In a real implementation, this would use Lean to verify
        # For now, return True if confidence is high enough
        return counterexample.confidence > 0.6

    def _prioritize_critiques(self, critiques: List[ProofCritique]) -> List[ProofCritique]:
        """Prioritize critiques by severity and remove duplicates"""
        # Sort by severity and confidence
        severity_order = {
            CritiqueSeverity.CRITICAL: 0,
            CritiqueSeverity.HIGH: 1,
            CritiqueSeverity.MEDIUM: 2,
            CritiqueSeverity.LOW: 3,
            CritiqueSeverity.INFO: 4
        }

        # Deduplicate by issue type
        seen = set()
        unique = []
        for critique in critiques:
            key = (critique.issue_type, critique.description[:50])
            if key not in seen:
                seen.add(key)
                unique.append(critique)

        # Sort by severity and confidence
        prioritized = sorted(unique,
                            key=lambda c: (severity_order.get(c.severity, 5), -c.confidence))

        return prioritized


class LeanCounterexampleGenerator:
    """
    Generates and validates counterexamples for Lean 4 theorems.

    Responsibilities:
    - Generate counterexamples for failed proofs
    - Use Lean 4 to validate counterexamples
    - Store counterexamples in knowledge base
    - Suggest proof fixes based on counterexamples
    """

    def __init__(self,
                 client: Optional['LeanAideClient'] = None,
                 knowledge_base_path: Optional[str] = None):
        self.client = client
        self.knowledge_base_path = knowledge_base_path or "lean_counterexamples.json"
        self.counterexamples: Dict[str, List[LeanCounterexample]] = {}
        self._load_knowledge_base()

    def generate_counterexample(self,
                               theorem: str,
                               proof: LeanProofStrategy,
                               critique: ProofCritique) -> Optional[LeanCounterexample]:
        """
        Generate a counterexample based on a critique.

        Args:
            theorem: The theorem statement
            proof: The proof strategy being critiqued
            critique: The critique suggesting a counterexample

        Returns:
            LeanCounterexample if successful, None otherwise
        """
        # Generate counterexample code
        counterexample_code = self._generate_counterexample_code(theorem, critique)

        if not counterexample_code:
            return None

        counterexample = LeanCounterexample(
            theorem=theorem,
            counterexample_code=counterexample_code,
            description=critique.description,
            confidence=critique.confidence
        )

        # Validate counterexample
        validated = self._validate_counterexample(counterexample, theorem)
        if validated:
            self._store_counterexample(theorem, counterexample)
            return counterexample

        return None

    def _generate_counterexample_code(self,
                                      theorem: str,
                                      critique: ProofCritique) -> Optional[str]:
        """Generate Lean 4 code for counterexample"""
        # Parse theorem to generate appropriate counterexample
        if "forall" in theorem.lower() or "∀" in theorem:
            return self._generate_universal_counterexample(theorem, critique)
        elif "injective" in theorem.lower():
            return self._generate_injective_counterexample(theorem)
        elif "surjective" in theorem.lower():
            return self._generate_surjective_counterexample(theorem)
        else:
            return None

    def _generate_universal_counterexample(self,
                                          theorem: str,
                                          critique: ProofCritique) -> str:
        """Generate counterexample for universal statement"""
        return f"""
-- Counterexample to: {theorem[:50]}...
example : False := by
  -- Construct specific case that violates universal claim
  let counterexample : Type := _
  -- Show property fails for this case
  sorry
"""

    def _generate_injective_counterexample(self, theorem: str) -> str:
        """Generate collision example for injectivity claim"""
        return f"""
-- Counterexample to injectivity claim: {theorem[:50]}...
example (f : Nat → Nat) : ∃ x y, x ≠ y ∧ f x = f y := by
  -- Find two distinct inputs with same output
  exists (0, 1)
  -- Define function where f(0) = f(1)
  constructor
  <;> decide
"""

    def _generate_surjective_counterexample(self, theorem: str) -> str:
        """Generate example outside range for surjectivity claim"""
        return f"""
-- Counterexample to surjectivity claim: {theorem[:50]}...
example : ∃ y : Nat, ¬∃ x, f x = y := by
  -- Find value not in function's range
  exists 0
  intro h
  -- Show 0 cannot be in range
  contradiction
"""

    def _validate_counterexample(self,
                                counterexample: LeanCounterexample,
                                theorem: str) -> bool:
        """Validate counterexample using Lean"""
        if LEANAIDE_AVAILABLE and self.client:
            try:
                result = self.client.verify_proof(
                    counterexample.counterexample_code,
                    ProofContext()
                )
                counterexample.status = CounterexampleStatus.VALID if result.is_valid else CounterexampleStatus.INVALID
                counterexample.verification_output = result.error_message
                counterexample.disproves_theorem = result.is_valid
                return result.is_valid
            except Exception as e:
                logger.debug(f"Counterexample validation failed: {e}")
                counterexample.status = CounterexampleStatus.INCONCLUSIVE

        return False

    def _store_counterexample(self, theorem: str, counterexample: LeanCounterexample):
        """Store counterexample in knowledge base"""
        if theorem not in self.counterexamples:
            self.counterexamples[theorem] = []

        self.counterexamples[theorem].append(counterexample)
        self._save_knowledge_base()

    def _load_knowledge_base(self):
        """Load counterexamples from knowledge base"""
        try:
            if Path(self.knowledge_base_path).exists():
                with open(self.knowledge_base_path, 'r') as f:
                    data = json.load(f)
                    # Reconstruct Counterexample objects
                    for theorem, counterexamples in data.items():
                        self.counterexamples[theorem] = [
                            LeanCounterexample(**ce) for ce in counterexamples
                        ]
        except Exception as e:
            logger.warning(f"Failed to load counterexample database: {e}")

    def _save_knowledge_base(self):
        """Save counterexamples to knowledge base"""
        try:
            # Convert to serializable format
            data = {}
            for theorem, counterexamples in self.counterexamples.items():
                data[theorem] = [
                    {
                        "theorem": ce.theorem,
                        "counterexample_code": ce.counterexample_code,
                        "description": ce.description,
                        "status": ce.status.value,
                        "disproves_theorem": ce.disproves_theorem,
                        "confidence": ce.confidence
                    }
                    for ce in counterexamples
                ]

            with open(self.knowledge_base_path, 'w') as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to save counterexample database: {e}")

    def suggest_fix(self,
                   theorem: str,
                   counterexample: LeanCounterexample) -> Optional[str]:
        """Suggest how to fix theorem based on counterexample"""
        if not counterexample.disproves_theorem:
            return None

        suggestions = []

        # Suggest additional hypotheses
        if "forall" in theorem.lower():
            suggestions.append("Add additional hypotheses to exclude counterexample case")

        # Suggest weakening theorem
        suggestions.append("Consider weakening theorem claim to handle edge cases")

        # Suggest existential version
        suggestions.append("Convert universal claim to existential if appropriate")

        return "\n".join(suggestions) if suggestions else None


class LeanAdversarialArena:
    """
    Manages adversarial competition between Blue and Red teams.

    Features:
    - Run adversarial rounds
    - Track win/loss ratios
    - Maintain leaderboards
    - Evolve strategies based on performance
    - Co-evolution of proof and critique
    """

    def __init__(self,
                 blue_team: LeanBlueTeamAgent,
                 red_team: LeanRedTeamAgent,
                 counterexample_generator: LeanCounterexampleGenerator):
        self.blue_team = blue_team
        self.red_team = red_team
        self.counterexample_generator = counterexample_generator

        self.round_history: List[RoundResult] = []
        self.statistics = AdversarialStatistics()

        # Strategy leaderboards
        self.approach_leaderboard: Dict[ProofApproach, float] = {
            approach: 0.5 for approach in ProofApproach
        }

        # Convergence tracking
        self.convergence_history: List[float] = []
        self.convergence_threshold = 0.95
        self.max_rounds = 20

    def run_adversarial_evolution(self,
                                 theorem: str,
                                 context: ProofContext,
                                 rounds: int = 10) -> Tuple[LeanProofStrategy, List[RoundResult]]:
        """
        Run full adversarial evolution process.

        Args:
            theorem: The theorem to prove
            context: Proof context
            rounds: Number of adversarial rounds

        Returns:
            Tuple of (final_proof_strategy, round_results)
        """
        logger.info(f"Starting adversarial evolution for {theorem[:50]}... ({rounds} rounds)")

        current_round = 0
        converged = False
        all_rounds = []

        # Initialize with empty critiques
        previous_critiques: List[ProofCritique] = []

        while current_round < rounds and not converged:
            current_round += 1

            # Run adversarial round
            result = self.run_adversarial_round(
                theorem, context, previous_critiques, current_round
            )

            all_rounds.append(result)

            # Update statistics
            self._update_statistics(result)

            # Update teams based on results
            self.blue_team.update_performance(result.blue_strategy.approach, result.blue_score)
            self.red_team.successful_attacks[result.round_number] = len(result.red_critique)

            # Check for convergence
            if result.blue_survived and result.blue_score > self.convergence_threshold:
                self.convergence_history.append(result.blue_score)
                if len(self.convergence_history) >= 3:
                    recent = self.convergence_history[-3:]
                    if all(s > self.convergence_threshold for s in recent):
                        converged = True
                        logger.info(f"Converged at round {current_round}")

            # Prepare critiques for next round
            previous_critiques = result.red_critique

        # Update final statistics
        self.statistics.total_rounds = len(all_rounds)
        self._calculate_final_statistics()

        # Return best proof (last one if converged, or best from history)
        if converged:
            final_proof = all_rounds[-1].blue_strategy
        else:
            # Find best scoring proof
            final_proof = max(all_rounds, key=lambda r: r.blue_score).blue_strategy

        logger.info(f"Adversarial evolution complete: {len(all_rounds)} rounds, "
                   f"final score: {final_proof.confidence:.2f}")

        return final_proof, all_rounds

    def run_adversarial_round(self,
                             theorem: str,
                             context: ProofContext,
                             previous_critiques: List[ProofCritique],
                             round_number: int) -> RoundResult:
        """
        Run a single adversarial round.

        Args:
            theorem: The theorem statement
            context: Proof context
            previous_critiques: Critiques from previous round
            round_number: Current round number

        Returns:
            RoundResult with round statistics
        """
        start_time = time.time()

        # Blue Team: Generate proof strategy
        logger.info(f"Round {round_number}: Blue Team generating proof...")
        blue_strategy = self.blue_team.generate_proof_strategy(
            theorem, context, previous_critiques
        )

        # Red Team: Critique the proof
        logger.info(f"Round {round_number}: Red Team critiquing proof...")
        red_critique = self.red_team.critique_proof(blue_strategy, theorem, context)

        # Generate counterexamples if critiques suggest issues
        counterexamples = []
        for critique in red_critique:
            if critique.severity in [CritiqueSeverity.CRITICAL, CritiqueSeverity.HIGH]:
                counterexample = self.counterexample_generator.generate_counterexample(
                    theorem, blue_strategy, critique
                )
                if counterexample:
                    counterexamples.append(counterexample)

        # Score the round
        blue_survived, red_score, blue_score = self._score_round(
            blue_strategy, red_critique, counterexamples
        )

        # Generate improvements
        improvements = []
        if not blue_survived:
            improvements = self._generate_improvements(blue_strategy, red_critique)

        round_result = RoundResult(
            round_number=round_number,
            blue_strategy=blue_strategy,
            red_critique=red_critique,
            counterexamples=counterexamples,
            blue_survived=blue_survived,
            red_score=red_score,
            blue_score=blue_score,
            improvements_made=improvements,
            time_taken=time.time() - start_time
        )

        # Update approach leaderboard
        self.approach_leaderboard[blue_strategy.approach] = (
            self.approach_leaderboard[blue_strategy.approach] * 0.9 + blue_score * 0.1
        )

        logger.info(f"Round {round_number} complete: Blue score={blue_score:.2f}, "
                   f"Red score={red_score:.2f}, Survived={blue_survived}")

        return round_result

    def _score_round(self,
                    blue_strategy: LeanProofStrategy,
                    red_critique: List[ProofCritique],
                    counterexamples: List[LeanCounterexample]) -> Tuple[bool, float, float]:
        """
        Score an adversarial round.

        Returns:
            Tuple of (blue_survived, red_score, blue_score)
        """
        # Blue survives if no critical or high severity critiques
        critical_issues = [c for c in red_critique
                          if c.severity in [CritiqueSeverity.CRITICAL, CritiqueSeverity.HIGH]]

        blue_survived = len(critical_issues) == 0

        # Red score: How many issues found
        red_score = min(1.0, len(red_critique) / 10.0)

        # Blue score: Based on survival and strategy quality
        if blue_survived:
            blue_score = blue_strategy.confidence
        else:
            # Penalize based on severity of issues
            penalty = sum(0.3 if c.severity == CritiqueSeverity.CRITICAL else 0.1
                         for c in critical_issues)
            blue_score = max(0.0, blue_strategy.confidence - penalty)

        # Adjust for counterexamples
        valid_counterexamples = [ce for ce in counterexamples if ce.disproves_theorem]
        if valid_counterexamples:
            red_score = min(1.0, red_score + 0.3 * len(valid_counterexamples))
            blue_score = max(0.0, blue_score - 0.2 * len(valid_counterexamples))
            blue_survived = False

        return blue_survived, min(1.0, red_score), min(1.0, blue_score)

    def _generate_improvements(self,
                             strategy: LeanProofStrategy,
                             critiques: List[ProofCritique]) -> List[str]:
        """Generate improvement suggestions based on critiques"""
        improvements = []

        for critique in critiques:
            if critique.fix_suggestion:
                improvements.append(f"Fix: {critique.fix_suggestion}")

            if critique.issue_type == "missing_case":
                improvements.append("Add explicit case analysis")

            elif critique.issue_type == "invalid_step":
                improvements.append("Verify and correct invalid steps")

            elif critique.issue_type == "counterexample":
                improvements.append("Add hypotheses to exclude counterexample")

        return list(set(improvements))  # Deduplicate

    def _update_statistics(self, result: RoundResult):
        """Update running statistics"""
        self.statistics.total_rounds += 1

        if result.blue_survived:
            self.statistics.blue_wins += 1
        else:
            self.statistics.red_wins += 1

        # Update approach success rates
        approach = result.blue_strategy.approach
        if approach not in self.statistics.approach_success_rates:
            self.statistics.approach_success_rates[approach] = []

        self.statistics.approach_success_rates[approach].append(result.blue_score)

        # Update average complexity
        n = self.statistics.total_rounds
        self.statistics.average_proof_complexity = (
            (self.statistics.average_proof_complexity * (n - 1) +
             result.blue_strategy.estimated_complexity) / n
        )

        # Track counterexamples
        valid_counterexamples = [ce for ce in result.counterexamples if ce.disproves_theorem]
        self.statistics.unique_counterexamples_found += len(valid_counterexamples)

    def _calculate_final_statistics(self):
        """Calculate final statistics from all rounds"""
        if self.statistics.total_rounds == 0:
            return

        self.statistics.blue_success_rate = (
            self.statistics.blue_wins / self.statistics.total_rounds
        )
        self.statistics.red_success_rate = (
            self.statistics.red_wins / self.statistics.total_rounds
        )

        # Find most effective approach
        approach_avgs = {}
        for approach, scores in self.statistics.approach_success_rates.items():
            if scores:
                approach_avgs[approach] = sum(scores) / len(scores)

        if approach_avgs:
            self.statistics.most_effective_approach = max(approach_avgs, key=approach_avgs.get)

    def get_leaderboard(self) -> Dict[str, Any]:
        """Get current leaderboard statistics"""
        return {
            "approach_rankings": sorted(
                self.approach_leaderboard.items(),
                key=lambda x: x[1],
                reverse=True
            ),
            "overall_statistics": {
                "total_rounds": self.statistics.total_rounds,
                "blue_win_rate": self.statistics.blue_success_rate,
                "red_win_rate": self.statistics.red_success_rate,
                "average_complexity": self.statistics.average_proof_complexity,
                "counterexamples_found": self.statistics.unique_counterexamples_found,
                "most_effective_approach": self.statistics.most_effective_approach.value if self.statistics.most_effective_approach else None
            }
        }


class LeanAdversarialEvolution:
    """
    Main orchestrator for Lean 4 adversarial proof evolution.

    Integrates:
    - Blue team proof generation
    - Red team critique and counterexamples
    - Adversarial arena for competition
    - LeanAide for proof verification
    - ACE knowledge storage for learned patterns

    Usage:
        evolution = LeanAdversarialEvolution()
        proof, history, stats = evolution.run_adversarial_evolution(
            theorem="theorem my_theorem : ...",
            rounds=10
        )
    """

    def __init__(self,
                 api_key: Optional[str] = None,
                 lean_path: Optional[str] = None,
                 knowledge_base_path: Optional[str] = None):
        """
        Initialize adversarial evolution system.

        Args:
            api_key: OpenAI API key for LLM-based generation
            lean_path: Path to Lean 4 installation
            knowledge_base_path: Path to store learned patterns
        """
        self.api_key = api_key
        self.lean_path = lean_path

        # Initialize LeanAide client if available
        self.leanaide_client = None
        if LEANAIDE_AVAILABLE:
            try:
                self.leanaide_client = LeanAideClient(api_key=api_key, lean_path=lean_path)
            except Exception as e:
                logger.warning(f"Failed to initialize LeanAide: {e}")

        # Initialize teams
        self.blue_team = LeanBlueTeamAgent(client=self.leanaide_client)
        self.red_team = LeanRedTeamAgent(client=self.leanaide_client)
        self.counterexample_generator = LeanCounterexampleGenerator(
            client=self.leanaide_client,
            knowledge_base_path=knowledge_base_path
        )

        # Initialize arena
        self.arena = LeanAdversarialArena(
            blue_team=self.blue_team,
            red_team=self.red_team,
            counterexample_generator=self.counterexample_generator
        )

        # History tracking
        self.evolution_history: List[Dict[str, Any]] = []

    def run_adversarial_evolution(self,
                                 theorem: str,
                                 context: Optional[ProofContext] = None,
                                 rounds: int = 10) -> Tuple[LeanProofStrategy, List[RoundResult], AdversarialStatistics]:
        """
        Run adversarial evolution on a theorem.

        Args:
            theorem: The theorem statement to prove
            context: Proof context (will create empty one if None)
            rounds: Number of adversarial rounds

        Returns:
            Tuple of (final_proof, round_results, statistics)
        """
        if context is None:
            context = ProofContext()

        logger.info(f"Starting adversarial evolution for theorem: {theorem[:100]}...")

        # Run evolution in arena
        final_proof, round_results = self.arena.run_adversarial_evolution(
            theorem, context, rounds
        )

        # Get statistics
        statistics = self.arena.statistics

        # Store in history
        self.evolution_history.append({
            "theorem": theorem,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "rounds": len(round_results),
            "final_proof": final_proof,
            "statistics": statistics,
            "round_results": round_results
        })

        return final_proof, round_results, statistics

    def blue_team_generate_proof(self,
                                theorem: str,
                                context: ProofContext) -> LeanProofStrategy:
        """Generate a proof using Blue Team"""
        return self.blue_team.generate_proof_strategy(theorem, context)

    def red_team_critique(self,
                         proof: LeanProofStrategy,
                         theorem: str,
                         context: ProofContext) -> List[ProofCritique]:
        """Critique a proof using Red Team"""
        return self.red_team.critique_proof(proof, theorem, context)

    def generate_counterexample(self,
                               theorem: str,
                               proof: LeanProofStrategy,
                               critique: ProofCritique) -> Optional[LeanCounterexample]:
        """Generate counterexample for failed proof"""
        return self.counterexample_generator.generate_counterexample(
            theorem, proof, critique
        )

    def improve_proof(self,
                     proof: LeanProofStrategy,
                     critiques: List[ProofCritique]) -> LeanProofStrategy:
        """Improve proof based on critiques"""
        # Generate new strategy incorporating critiques
        new_strategy = self.blue_team.generate_proof_strategy(
            theorem=critiques[0].description if critiques else "",
            context=ProofContext(),
            previous_critiques=critiques
        )
        return new_strategy

    def run_adversarial_round(self,
                             blue_strategy: LeanProofStrategy,
                             red_critique: List[ProofCritique],
                             theorem: str,
                             context: ProofContext) -> RoundResult:
        """Run a single adversarial round"""
        # This wraps the arena's method
        round_num = len(self.arena.round_history) + 1
        return self.arena.run_adversarial_round(theorem, context, red_critique, round_num)

    def get_lean_proof(self, strategy: LeanProofStrategy) -> str:
        """Get the Lean 4 code for a strategy"""
        return strategy.lean_code

    def verify_proof(self, lean_code: str, context: ProofContext) -> bool:
        """Verify a proof using Lean"""
        if LEANAIDE_AVAILABLE and self.leanaide_client:
            try:
                result = self.leanaide_client.verify_proof(lean_code, context)
                return result.is_valid
            except Exception as e:
                logger.error(f"Proof verification failed: {e}")
        return False

    def store_learned_pattern(self, pattern: Dict[str, Any]):
        """Store a learned pattern in knowledge base"""
        # This would integrate with ACE knowledge storage
        # For now, just log it
        logger.info(f"Storing learned pattern: {pattern.get('type', 'unknown')}")

    def get_evolution_report(self) -> Dict[str, Any]:
        """Generate comprehensive evolution report"""
        return {
            "total_evolutions": len(self.evolution_history),
            "leaderboard": self.arena.get_leaderboard(),
            "recent_history": self.evolution_history[-5:] if self.evolution_history else [],
            "blue_team_performance": self.blue_team.performance_history,
            "red_team_success": self.red_team.successful_attacks
        }


# Convenience functions for quick usage

def evolve_lean_proof(theorem: str,
                     rounds: int = 10,
                     api_key: Optional[str] = None) -> Dict[str, Any]:
    """
    Convenience function to evolve a Lean 4 proof adversarially.

    Args:
        theorem: The theorem statement
        rounds: Number of adversarial rounds
        api_key: OpenAI API key

    Returns:
        Dictionary with proof, history, and statistics
    """
    evolution = LeanAdversarialEvolution(api_key=api_key)

    final_proof, round_results, statistics = evolution.run_adversarial_evolution(
        theorem=theorem,
        rounds=rounds
    )

    return {
        "proof": final_proof.lean_code,
        "strategy": final_proof.approach.value,
        "confidence": final_proof.confidence,
        "rounds": len(round_results),
        "statistics": {
            "blue_win_rate": statistics.blue_success_rate,
            "red_win_rate": statistics.red_success_rate,
            "counterexamples_found": statistics.unique_counterexamples_found
        },
        "history": [
            {
                "round": r.round_number,
                "blue_score": r.blue_score,
                "red_score": r.red_score,
                "survived": r.blue_survived,
                "critiques": len(r.red_critique),
                "counterexamples": len(r.counterexamples)
            }
            for r in round_results
        ]
    }


# =============================================================================
# MDAP-Enhanced Adversarial Evolution
# =============================================================================

class LeanAdversarialEvolutionMDAP:
    """
    Adversarial evolution with MDAP agent voting.

    Blue Team and Red Team use MDAP voting for:
    - Blue Team: Multi-agent proof strategy generation
    - Red Team: Multi-agent proof critique
    - Enhanced adversarial rounds with consensus
    """

    def __init__(
        self,
        blue_agents: List[LeanBlueTeamAgent],
        red_agents: List[LeanRedTeamAgent],
        mdap_config: Optional['LeanMDAPConfig'] = None
    ):
        """
        Initialize MDAP-enhanced adversarial evolution.

        Args:
            blue_agents: List of blue team agents
            red_agents: List of red team agents
            mdap_config: MDAP configuration
        """
        self.blue_agents = blue_agents
        self.red_agents = red_agents
        self.mdap_config = mdap_config

        # Statistics tracking
        self.mdap_stats = {
            "blue_team_votes": defaultdict(int),
            "red_team_votes": defaultdict(int),
            "consensus_rates": [],
            "agent_contributions": defaultdict(int)
        }

    async def blue_team_generate_with_mdap(
        self,
        theorem: str,
        agents: List[LeanBlueTeamAgent],
        context: Optional[ProofContext] = None
    ) -> LeanProofStrategy:
        """
        Generate proof strategy using MDAP voting among blue team agents.

        Args:
            theorem: Theorem to prove
            agents: List of blue team agents
            context: Proof context

        Returns:
            Consensus proof strategy
        """
        if context is None:
            context = ProofContext()

        logger.info(f"Blue team MDAP generation with {len(agents)} agents")

        # Each agent generates a strategy
        strategies = []
        for agent in agents:
            strategy = agent.generate_proof_strategy(
                theorem, context, approach=None
            )
            strategies.append(strategy)

        # MDAP voting on best strategy
        consensus_strategy = await self._mdap_vote_on_strategy(strategies)

        # Track voting statistics
        for strategy in strategies:
            self.mdap_stats["blue_team_votes"][strategy.approach] += 1

        logger.info(f"MDAP selected {consensus_strategy.approach} strategy")
        return consensus_strategy

    async def red_team_critique_with_mdap(
        self,
        proof: LeanProof,
        agents: List[LeanRedTeamAgent],
        theorem: str,
        context: Optional[ProofContext] = None
    ) -> List[ProofCritique]:
        """
        Critique proof using MDAP voting among red team agents.

        Args:
            proof: Proof to critique
            agents: List of red team agents
            theorem: Theorem being proved
            context: Proof context

        Returns:
            Consensus list of critiques
        """
        if context is None:
            context = ProofContext()

        logger.info(f"Red team MDAP critique with {len(agents)} agents")

        # Each agent critiques the proof
        all_critiques = []
        for agent in agents:
            agent_critiques = agent.critique_proof(proof, theorem, context)
            all_critiques.extend(agent_critiques)

        # MDAP voting on most important critiques
        consensus_critiques = await self._mdap_vote_on_critiques(all_critiques)

        # Track voting statistics
        for critique in consensus_critiques:
            self.mdap_stats["red_team_votes"][critique.severity] += 1

        logger.info(f"MDAP selected {len(consensus_critiques)} consensus critiques")
        return consensus_critiques

    async def run_adversarial_round_with_mdap(
        self,
        blue_agents: List[LeanBlueTeamAgent],
        red_agents: List[LeanRedTeamAgent],
        theorem: str,
        context: Optional[ProofContext] = None,
        round_number: int = 1
    ) -> RoundResult:
        """
        Run a single adversarial round with MDAP voting.

        Args:
            blue_agents: Blue team agents
            red_agents: Red team agents
            theorem: Theorem to prove
            context: Proof context
            round_number: Current round number

        Returns:
            RoundResult with MDAP-enhanced adversarial round
        """
        start_time = time.time()

        if context is None:
            context = ProofContext()

        # Blue Team: Generate proof with MDAP
        logger.info(f"Round {round_number}: Blue Team MDAP generation...")
        blue_strategy = await self.blue_team_generate_with_mdap(
            theorem, blue_agents, context
        )

        # Red Team: Critique with MDAP
        logger.info(f"Round {round_number}: Red Team MDAP critique...")
        red_critique = await self.red_team_critique_with_mdap(
            blue_strategy, red_agents, theorem, context
        )

        # Score the round
        blue_survived = len([c for c in red_critique
                           if c.severity in [CritiqueSeverity.CRITICAL, CritiqueSeverity.HIGH]]) == 0

        red_score = min(1.0, len(red_critique) / 10.0)
        blue_score = blue_strategy.confidence if blue_survived else max(0.0, blue_strategy.confidence - 0.3)

        # Track consensus rate
        consensus_rate = self._calculate_consensus_rate(blue_strategy, red_critique)
        self.mdap_stats["consensus_rates"].append(consensus_rate)

        round_result = RoundResult(
            round_number=round_number,
            blue_strategy=blue_strategy,
            red_critique=red_critique,
            counterexamples=[],
            blue_survived=blue_survived,
            red_score=red_score,
            blue_score=blue_score,
            time_taken=time.time() - start_time,
            metadata={"mdap_enhanced": True, "consensus_rate": consensus_rate}
        )

        logger.info(
            f"Round {round_number}: Blue={blue_score:.2f}, Red={red_score:.2f}, "
            f"Survived={blue_survived}, Consensus={consensus_rate:.2f}"
        )

        return round_result

    async def _mdap_vote_on_strategy(
        self,
        strategies: List[LeanProofStrategy]
    ) -> LeanProofStrategy:
        """
        Use MDAP voting to select best strategy.

        Args:
            strategies: List of strategies to vote on

        Returns:
            Consensus strategy
        """
        if not strategies:
            raise ValueError("No strategies to vote on")

        if len(strategies) == 1:
            return strategies[0]

        # Score each strategy
        scored_strategies = []
        for strategy in strategies:
            # Combined score from confidence, complexity, and elegance
            score = (
                strategy.confidence * 0.5 +
                (1.0 - strategy.estimated_complexity) * 0.3 +
                strategy.performance_history.get("avg_success", 0.5) * 0.2
            )
            scored_strategies.append((strategy, score))

        # Sort by score
        scored_strategies.sort(key=lambda x: x[1], reverse=True)

        # First-K-ahead voting: select top strategy
        k_ahead = self.mdap_config.k_ahead_threshold if self.mdap_config else 3
        top_k = min(k_ahead, len(scored_strategies))

        # In full MDAP, agents would vote here
        # For now, return highest scored
        return scored_strategies[0][0]

    async def _mdap_vote_on_critiques(
        self,
        critiques: List[ProofCritique]
    ) -> List[ProofCritique]:
        """
        Use MDAP voting to select most important critiques.

        Args:
            critiques: List of critiques to vote on

        Returns:
            Consensus critiques
        """
        if not critiques:
            return []

        # Group by issue type
        by_type = defaultdict(list)
        for critique in critiques:
            by_type[critique.issue_type].append(critique)

        # Select best critique for each type
        consensus = []
        for issue_type, type_critiques in by_type.items():
            # Sort by severity and confidence
            sorted_critiques = sorted(
                type_critiques,
                key=lambda c: (c.severity.value, c.confidence),
                reverse=True
            )
            consensus.append(sorted_critiques[0])

        # Sort by overall importance
        consensus.sort(
            key=lambda c: (c.severity.value, c.confidence),
            reverse=True
        )

        return consensus

    def _calculate_consensus_rate(
        self,
        strategy: LeanProofStrategy,
        critiques: List[ProofCritique]
    ) -> float:
        """Calculate rate of consensus among agents."""
        # Simplified consensus calculation
        if not critiques:
            return 1.0

        # Consensus is higher when critiques are less severe
        severity_weights = {
            CritiqueSeverity.CRITICAL: 0.0,
            CritiqueSeverity.HIGH: 0.3,
            CritiqueSeverity.MEDIUM: 0.6,
            CritiqueSeverity.LOW: 0.8,
            CritiqueSeverity.INFO: 1.0
        }

        weights = [severity_weights.get(c.severity, 0.5) for c in critiques]
        return sum(weights) / len(weights) if weights else 0.0

    def get_mdap_statistics(self) -> Dict[str, Any]:
        """Get MDAP voting statistics."""
        avg_consensus = 0.0
        if self.mdap_stats["consensus_rates"]:
            avg_consensus = sum(self.mdap_stats["consensus_rates"]) / len(self.mdap_stats["consensus_rates"])

        return {
            "blue_team_votes": dict(self.mdap_stats["blue_team_votes"]),
            "red_team_votes": dict(self.mdap_stats["red_team_votes"]),
            "average_consensus_rate": avg_consensus,
            "agent_contributions": dict(self.mdap_stats["agent_contributions"])
        }


# Example usage and testing
if __name__ == "__main__":
    # Example theorem
    example_theorem = """
    theorem add_comm (a b : Nat) : a + b = b + a
    """

    # Run adversarial evolution
    result = evolve_lean_proof(example_theorem, rounds=5)

    print("Adversarial Evolution Results:")
    print(f"Proof:\n{result['proof']}")
    print(f"\nStrategy: {result['strategy']}")
    print(f"Confidence: {result['confidence']:.2f}")
    print(f"\nStatistics:")
    for key, value in result['statistics'].items():
        print(f"  {key}: {value}")
    print(f"\nRound History:")
    for round_data in result['history']:
        print(f"  Round {round_data['round']}: Blue={round_data['blue_score']:.2f}, "
              f"Red={round_data['red_score']:.2f}, Survived={round_data['survived']}")


# Export all classes
__all__ = [
    # Enums
    'Approach',
    'CritiqueSeverity',
    'CritiqueIssueType',

    # Core classes
    'ProofContext',
    'LeanProofStrategy',
    'LeanProof',
    'ProofCritique',
    'RoundResult',
    'AdversarialStatistics',

    # Blue Team
    'LeanBlueTeamAgent',

    # Red Team
    'LeanRedTeamAgent',

    # Adversarial Evolution
    'LeanAdversarialEvolution',
    'evolve_lean_proof',

    # MDAP-Enhanced
    'LeanAdversarialEvolutionMDAP',
]
