#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenEvolve PES Integration Module

This module integrates the content-agnostic PES (Plan-Execute-Summarize) system
with OpenEvolve to enhance code outputs through evolutionary improvement.

Usage:
    from openevolve_pes_integration import enhance_openevolve_code, OpenEvolvePESEnhancer

    # Enhance code generated by OpenEvolve
    enhanced_code = enhance_openevolve_code(code, tests, language="python")

    # For Lean code (theorems/proofs):
    from openevolve_pes_integration import enhance_lean_proof
    enhanced_lean = enhance_lean_proof(lean_code, theorem_description)
"""

import asyncio
import logging
import sys
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

# Import the agnostic PES system
try:
    from openevolve_agnostic_pes import (
        AgnosticPESEngine,
        EvolutionResult,
        UniversalTestRunner,
        LanguageDetector,
        UniversalCodeAnalyzer,
        UniversalFixGenerator,
    )
    PES_AVAILABLE = True
except ImportError as e:
    PES_AVAILABLE = False
    logging.warning(f"PES system not available: {e}")

# Import LeanAide PES handler
try:
    from leanaide_pes_handler import (
        LeanPESHandler,
        LeanCodeAnalyzer,
        enhance_lean_proof as lean_enhance_lean_proof,
        verify_lean_code as lean_verify_lean_code,
    )
    LEANAIDE_PES_AVAILABLE = True
except ImportError as e:
    LEANAIDE_PES_AVAILABLE = False
    logging.warning(f"LeanAide PES handler not available: {e}")

# REAL Lean Integration
try:
    from leanaide_client import LeanAideClient
    LEAN_AVAILABLE = True
except ImportError:
    LEAN_AVAILABLE = False

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] [OpenEvolve-PES] %(message)s",
    stream=sys.stdout
)
logger = logging.getLogger("OpenEvolve-PES-Integration")


# =============================================================================
# Test Generation for OpenEvolve Outputs
# =============================================================================

class OpenEvolveTestGenerator:
    """
    Generates test cases for OpenEvolve outputs based on code analysis.
    
    This class extracts testable functions from code and generates
    corresponding test cases.
    """
    
    @staticmethod
    def extract_functions(code: str) -> List[Dict[str, Any]]:
        """Extract function definitions from code."""
        functions = []
        
        # Python patterns
        py_pattern = r'def\s+(\w+)\s*\(([^)]*)\)'
        for match in __import__('re').finditer(py_pattern, code):
            functions.append({
                'name': match.group(1),
                'params': match.group(2).strip() if match.group(2) else '',
                'language': 'python'
            })
        
        # PHP patterns
        php_pattern = r'function\s+(\w+)\s*\(([^)]*)\)'
        for match in __import__('re').finditer(php_pattern, code):
            functions.append({
                'name': match.group(1),
                'params': match.group(2).strip() if match.group(2) else '',
                'language': 'php'
            })
        
        # JavaScript patterns
        js_pattern = r'(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)'
        for match in __import__('re').finditer(js_pattern, code):
            functions.append({
                'name': match.group(1),
                'params': match.group(2).strip() if match.group(2) else '',
                'language': 'javascript'
            })
        
        return functions
    
    @staticmethod
    def generate_default_tests(code: str, language: str = 'python') -> List[Dict[str, Any]]:
        """
        Generate default test cases for code.
        
        This creates basic smoke tests that verify the code doesn't crash
        and returns expected data types.
        """
        functions = OpenEvolveTestGenerator.extract_functions(code)
        tests = []
        
        for func in functions:
            func_name = func['name']
            
            # Generate a basic test based on function name and detected patterns
            if 'payment' in func_name.lower() or 'calculate' in func_name.lower():
                # Payment/calculation function tests
                tests.append({
                    'name': f'{func_name}_basic',
                    'input': {'amount': 100},
                    'expected': {'total': 100},  # Basic expectation
                    'function': func_name
                })
            elif 'validate' in func_name.lower() or 'check' in func_name.lower():
                # Validation function tests
                tests.append({
                    'name': f'{func_name}_valid',
                    'input': {'value': 'test@example.com'},
                    'expected': {'valid': True},
                    'function': func_name
                })
            elif 'process' in func_name.lower() or 'handle' in func_name.lower():
                # Processing function tests
                tests.append({
                    'name': f'{func_name}_basic',
                    'input': {'data': {}},
                    'expected': {'success': True},
                    'function': func_name
                })
            else:
                # Generic function test
                tests.append({
                    'name': f'{func_name}_smoke',
                    'input': {},
                    'expected': None,  # Just check it doesn't crash
                    'function': func_name
                })
        
        return tests
    
    @staticmethod
    def generate_inference_tests(code: str, problem_description: str) -> List[Dict[str, Any]]:
        """
        Generate tests based on problem description inference.
        
        Analyzes the problem description to understand what the code
        should do and generates appropriate test cases.
        """
        tests = []
        problem_lower = problem_description.lower()
        
        # Payment/financial tests
        if 'payment' in problem_lower or 'calculate' in problem_lower or 'price' in problem_lower:
            tests = [
                {
                    'name': 'basic_calculation',
                    'input': {'amount': 100},
                    'expected': {'total': 100},
                    'function': 'calculate_payment'
                },
                {
                    'name': 'with_discount',
                    'input': {'amount': 100, 'discount': 10},
                    'expected': {'total': 90},
                    'function': 'calculate_payment'
                },
                {
                    'name': 'zero_amount',
                    'input': {'amount': 0},
                    'expected': {'total': 0},
                    'function': 'calculate_payment'
                },
            ]
        
        # Validation tests
        elif 'valid' in problem_lower or 'check' in problem_lower:
            tests = [
                {
                    'name': 'valid_input',
                    'input': {'value': 'test@example.com'},
                    'expected': {'valid': True},
                    'function': 'validate'
                },
                {
                    'name': 'invalid_input',
                    'input': {'value': 'invalid'},
                    'expected': {'valid': False},
                    'function': 'validate'
                },
            ]
        
        # Order/processing tests
        elif 'order' in problem_lower or 'process' in problem_lower:
            tests = [
                {
                    'name': 'basic_order',
                    'input': {'items': [{'price': 10, 'quantity': 2}]},
                    'expected': {'subtotal': 20},
                    'function': 'process_order'
                },
                {
                    'name': 'empty_order',
                    'input': {'items': []},
                    'expected': {'error': None},
                    'function': 'process_order'
                },
            ]
        
        # Default tests
        if not tests:
            tests = OpenEvolveTestGenerator.generate_default_tests(code)
        
        return tests


# =============================================================================
# OpenEvolve PES Enhancer
# =============================================================================

@dataclass
class EnhancementResult:
    """Result of enhancing OpenEvolve code with PES."""
    original_code: str = ""
    enhanced_code: str = ""
    tests_generated: int = 0
    tests_passed_before: int = 0
    tests_passed_after: int = 0
    improvements: List[str] = field(default_factory=list)
    success: bool = False
    error: Optional[str] = None


class PESEvolutionEngine:
    """PES-based evolution engine.
    
    Combines Plan-Execute-Summarize paradigm with
    evolutionary optimization techniques.
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """Initialize PES evolution engine.
        
        Args:
            config: Optional configuration dictionary
        """
        self.config = config or {}
        self.iterations = self.config.get("iterations", 10)
        self.population_size = self.config.get("population_size", 50)
        
    def evolve(self, code: str, **kwargs) -> EnhancementResult:
        """Evolve code using PES strategy.
        
        Args:
            code: Source code to evolve
            **kwargs: Additional parameters
            
        Returns:
            EnhancementResult with evolved code
        """
        return quick_evolve(code, **kwargs)


class OpenEvolvePESEnhancer:
    """
    Enhances OpenEvolve outputs using the content-agnostic PES system.
    
    This class takes code generated by OpenEvolve and applies
    evolutionary improvement to fix bugs and enhance correctness.
    """
    
    def __init__(self, max_iterations: int = 5):
        """
        Initialize the enhancer.
        
        Args:
            max_iterations: Maximum evolution iterations (default: 5)
        """
        self.max_iterations = max_iterations
        
        if PES_AVAILABLE:
            self.engine = AgnosticPESEngine(max_iterations=max_iterations)
        else:
            self.engine = None
            logger.warning("PES engine not available - enhancement disabled")
    
    def enhance(
        self,
        code: str,
        problem_description: str = "",
        tests: List[Dict[str, Any]] = None,
        language: str = None,
    ) -> EnhancementResult:
        """
        Enhance code using the PES system.
        
        Args:
            code: The code to enhance
            problem_description: Description of what the code should do
            tests: Optional pre-defined test cases
            language: Programming language (auto-detected if not provided)
        
        Returns:
            EnhancementResult with enhanced code and metrics
        """
        result = EnhancementResult(original_code=code)
        
        if not PES_AVAILABLE or self.engine is None:
            result.error = "PES system not available"
            return result
        
        try:
            # Auto-detect language if not provided
            if language is None:
                language = LanguageDetector.detect(code)
            
            result.tests_generated = len(tests) if tests else 0
            
            # Generate tests if not provided
            if not tests:
                if problem_description:
                    tests = OpenEvolveTestGenerator.generate_inference_tests(
                        code, problem_description
                    )
                else:
                    tests = OpenEvolveTestGenerator.generate_default_tests(code)
                result.tests_generated = len(tests)
            
            if not tests:
                result.error = "No tests available for enhancement"
                return result
            
            logger.info(f"Starting enhancement for {len(tests)} tests in {language}")
            
            # Run PES evolution
            evolution_result = asyncio.run(
                self.engine.evolve(code, tests)
            )
            
            # Populate result
            result.enhanced_code = evolution_result.evolved_code
            result.tests_passed_before = evolution_result.tests_passed - (
                1 if evolution_result.improvement > 0 else 0
            )
            result.tests_passed_after = evolution_result.tests_passed
            result.improvements = evolution_result.fixes_applied
            result.success = evolution_result.final_score == 1.0
            
            logger.info(f"Enhancement complete: {result.tests_passed_after}/{result.tests_generated} tests pass")
            
            return result
            
        except Exception as e:
            result.error = str(e)
            logger.error(f"Enhancement failed: {e}")
            return result
    
    def enhance_with_validation(
        self,
        code: str,
        problem_description: str,
        expected_behavior: Dict[str, Any],
    ) -> EnhancementResult:
        """
        Enhance code with explicit expected behavior validation.
        
        Args:
            code: The code to enhance
            problem_description: Description of what the code should do
            expected_behavior: Dictionary of expected function behaviors
        
        Returns:
            EnhancementResult with enhanced code and metrics
        """
        # Convert expected behavior to tests
        tests = []
        for func_name, expected in expected_behavior.items():
            tests.append({
                'name': f'{func_name}_validation',
                'input': expected.get('input', {}),
                'expected': expected.get('output', {}),
                'function': func_name
            })
        
        return self.enhance(code, problem_description, tests)

    def verify_with_lean(self, workflow_or_node) -> Dict[str, Any]:
        """
        REAL Lean verification for PES workflows.
        
        Args:
            workflow_or_node: Workflow component or node to verify
            
        Returns:
            Dictionary with verification results
        """
        if not LEAN_AVAILABLE:
            return {"verified": False, "error": "Lean not available"}
        
        try:
            client = LeanAideClient()
            formalized = client.autoformalize(str(workflow_or_node))
            return client.verify(formalized)
        except Exception as e:
            logger.warning(f"Lean verification failed: {e}")
            return {"verified": False, "error": str(e)}


# =============================================================================
# Convenience Functions
# =============================================================================

def enhance_openevolve_code(
    code: str,
    tests: List[Dict[str, Any]] = None,
    problem_description: str = "",
    language: str = None,
    max_iterations: int = 5,
) -> EnhancementResult:
    """
    Convenience function to enhance OpenEvolve code.
    
    Args:
        code: The code to enhance
        tests: Optional test cases
        problem_description: Description of the problem being solved
        language: Programming language
        max_iterations: Maximum evolution iterations
    
    Returns:
        EnhancementResult with enhanced code
    """
    enhancer = OpenEvolvePESEnhancer(max_iterations=max_iterations)
    return enhancer.enhance(code, problem_description, tests, language)


def quick_enhance(code: str, problem_description: str = "") -> EnhancementResult:
    """
    Quick enhancement with default settings.
    
    Args:
        code: The code to enhance
        problem_description: Description of the problem
    
    Returns:
        EnhancementResult with enhanced code
    """
    return enhance_openevolve_code(code, problem_description=problem_description)


# =============================================================================
# Lean/LeanAide Enhancement Functions
# =============================================================================

def enhance_lean_proof(
    lean_code: str,
    theorem_description: str = "",
    max_iterations: int = 3,
) -> Dict[str, Any]:
    """
    Enhance Lean code (theorems/proofs) using the LeanAide PES system.
    
    This function specifically handles Lean 4 code and can:
    - Complete incomplete proofs (replace 'sorry' with tactics)
    - Verify theorem structure
    - Suggest appropriate proof tactics
    
    Args:
        lean_code: The Lean code to enhance
        theorem_description: Description of the theorem/problem
        max_iterations: Maximum enhancement iterations
    
    Returns:
        Dict with 'enhanced_code', 'success', 'improvements', 'tests_passed', 'tests_total'
    """
    if not LEANAIDE_PES_AVAILABLE:
        return {
            'enhanced_code': lean_code,
            'success': False,
            'improvements': [],
            'tests_passed': 0,
            'tests_total': 1,
            'error': 'LeanAide PES handler not available'
        }
    
    return lean_enhance_lean_proof(lean_code, theorem_description, max_iterations)


def verify_lean_code(lean_code: str) -> Dict[str, Any]:
    """
    Verify Lean code for common issues.
    
    Args:
        lean_code: Lean code to verify
    
    Returns:
        Dict with 'valid', 'issues', 'has_sorry', 'theorems_found'
    """
    if not LEANAIDE_PES_AVAILABLE:
        return {
            'valid': False,
            'issues': ['LeanAide PES handler not available'],
            'has_sorry': False,
            'theorems_found': 0
        }
    
    return lean_verify_lean_code(lean_code)


def is_lean_code(code: str) -> bool:
    """
    Check if code appears to be Lean 4 code.
    
    Args:
        code: Code to check
    
    Returns:
        True if code appears to be Lean 4
    """
    lean_patterns = [
        r'\btheorem\b',
        r'\blemma\b',
        r'\bdef\b.*:=\b',
        r'\bby\s+(?:simp|trivial|ring|induction)',
        r'\bimport\s+Mathlib',
        r'\bsorry\b',
    ]
    
    for pattern in lean_patterns:
        if __import__('re').search(pattern, code):
            return True
    return False


def detect_language(code: str) -> str:
    """
    Detect the programming language of code.
    
    Args:
        code: Code to analyze
    
    Returns:
        Language string ('python', 'lean', 'javascript', etc.)
    """
    # Check for Lean first
    if is_lean_code(code):
        return 'lean'
    
    # Use the agnostic PES language detector
    if PES_AVAILABLE:
        return LanguageDetector.detect(code)
    
    # Fallback detection
    code_lower = code.lower()
    if 'def ' in code and ':' in code and ' -> ' in code:
        return 'python'
    if 'function' in code and '=>' in code:
        return 'javascript'
    if 'public class' in code:
        return 'java'
    
    return 'unknown'


def enhance_code(
    code: str,
    problem_description: str = "",
    tests: List[Dict[str, Any]] = None,
    language: str = None,
    max_iterations: int = 5,
) -> Dict[str, Any]:
    """
    Universal code enhancement function that handles any language.
    
    This is the main entry point for enhancing code from OpenEvolve.
    It automatically detects the language and uses the appropriate handler.
    
    Args:
        code: The code to enhance
        problem_description: Description of what the code should do
        tests: Optional test cases
        language: Programming language (auto-detected if not provided)
        max_iterations: Maximum enhancement iterations
    
    Returns:
        Dict with 'enhanced_code', 'success', 'language', 'improvements'
    """
    # Auto-detect language if not provided
    if language is None:
        language = detect_language(code)
    
    # Handle Lean code
    if language == 'lean':
        result = enhance_lean_proof(
            lean_code=code,
            theorem_description=problem_description,
            max_iterations=max_iterations
        )
        result['language'] = 'lean'
        return result
    
    # Handle other languages with agnostic PES
    if PES_AVAILABLE:
        enhancement_result = enhance_openevolve_code(
            code=code,
            tests=tests,
            problem_description=problem_description,
            language=language,
            max_iterations=max_iterations
        )
        return {
            'enhanced_code': enhancement_result.enhanced_code,
            'success': enhancement_result.success,
            'language': language,
            'improvements': enhancement_result.improvements,
            'tests_passed': enhancement_result.tests_passed_after,
            'tests_total': enhancement_result.tests_generated,
        }
    
    # Fallback
    return {
        'enhanced_code': code,
        'success': False,
        'language': language,
        'improvements': [],
        'error': 'No enhancement system available'
    }


# =============================================================================
# Demo
# =============================================================================

def demo():
    """Demonstrate the OpenEvolve PES integration."""
    
    print("\n" + "="*70)
    print("  OpenEvolve PES Integration Demo")
    print("  Enhancing OpenEvolve Outputs with Content-Agnostic Evolution")
    print("="*70)
    
    # Sample code that might come from OpenEvolve
    code = '''def calculate_payment(amount, discount_code=None, payment_method="credit_card"):
    """Calculate payment with tax, discounts, and fees."""
    subtotal = amount
    discount = 0
    
    # Apply discount
    if discount_code == "SAVE10":
        discount = subtotal * 0.10
    elif discount_code == "SAVE20":
        discount = subtotal * 0.20
    
    # Calculate tax
    taxable = subtotal - discount
    tax = taxable * 0.085
    
    # Payment fee
    fee = 0
    if payment_method == "credit_card":
        fee = subtotal * 0.029
    elif payment_method == "debit_card":
        fee = subtotal * 0.015
    
    total = taxable + tax + fee
    return {"subtotal": subtotal, "discount": discount, "tax": tax, "fee": fee, "total": total}'''
    
    problem_description = "Calculate payment with tax, discounts, and payment method fees"
    
    # Tests that OpenEvolve might generate
    tests = [
        {"name": "Basic payment", "input": {"amount": 100}, "expected": {"total": 111.4}, "function": "calculate_payment"},
        {"name": "10% discount", "input": {"amount": 100, "discount_code": "SAVE10"}, "expected": {"discount": 10}, "function": "calculate_payment"},
        {"name": "PayPal fee", "input": {"amount": 150, "payment_method": "paypal"}, "expected": {"fee": 5.25}, "function": "calculate_payment"},
    ]
    
    print("\nOriginal Code (from OpenEvolve):")
    print(code)
    
    print("\n" + "-"*70)
    print("Enhancing with PES system...")
    
    result = enhance_openevolve_code(
        code=code,
        tests=tests,
        problem_description=problem_description,
        max_iterations=5
    )
    
    print(f"\nEnhancement Result:")
    print(f"  Success: {result.success}")
    print(f"  Tests Generated: {result.tests_generated}")
    print(f"  Tests Passed (After): {result.tests_passed_after}/{result.tests_generated}")
    print(f"  Improvements: {result.improvements}")
    
    if result.error:
        print(f"  Error: {result.error}")
    
    if result.enhanced_code:
        print(f"\nEnhanced Code:")
        print(result.enhanced_code)
    
    return result


class PHPHandler:
    """Handler for PHP code enhancement."""
    
    @staticmethod
    def is_php(code: str) -> bool:
        """Check if code is PHP."""
        return code.strip().startswith('<?php') or '<?php' in code[:100]
    
    @staticmethod
    def enhance(code: str, **kwargs) -> str:
        """Enhance PHP code."""
        return code


class PythonHandler:
    """
    Handler for Python code testing and execution.
    
    This is a stub class for backward compatibility.
    """
    
    def __init__(self, *args, **kwargs):
        """Initialize the Python handler."""
        pass
    
    def generate_test_wrapper(self, code: str, tests: List[Dict]) -> str:
        """
        Generate a test wrapper for the given code and tests.
        
        Args:
            code: Python code to test
            tests: List of test cases
        
        Returns:
            Test wrapper code as string
        """
        import json
        tests_json = json.dumps(tests)
        # Use string concatenation to avoid f-string issues with triple quotes
        wrapper_parts = [
            code,
            "",
            "# Test execution",
            "import json",
            "test_results = []",
            "tests = json.loads('" + tests_json + "')",
            "",
            "for test in tests:",
            "    try:",
            "        result = globals()[test['function']](**test['input'])",
            "        # Check expected values",
            "        passed = True",
            "        for key, expected in test.get('expected', {}).items():",
            "            if result.get(key) != expected:",
            "                passed = False",
            "                break",
            "        test_results.append(dict(name=test['name'], passed=passed))",
            "    except Exception as e:",
            "        test_results.append(dict(name=test['name'], passed=False, error=str(e)))",
            "",
            "# Output results",
            "print(json.dumps(test_results))",
        ]
        return "\n".join(wrapper_parts)
    
    def execute_tests(self, wrapper_code: str) -> Tuple[int, int, List[str]]:
        """
        Execute the test wrapper code.
        
        Args:
            wrapper_code: Test wrapper code to execute
        
        Returns:
            Tuple of (passed_count, total_count, failing_tests)
        """
        import json
        import subprocess
        import sys
        import tempfile
        import os
        
        # Write wrapper to temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
            f.write(wrapper_code)
            temp_file = f.name
        
        try:
            # Execute the wrapper
            result = subprocess.run(
                [sys.executable, temp_file],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            # Parse results
            try:
                output = result.stdout.strip().split('\n')[-1]
                test_results = json.loads(output)
                passed = sum(1 for r in test_results if r.get('passed', False))
                total = len(test_results)
                failing = [r['name'] for r in test_results if not r.get('passed', False)]
                return passed, total, failing
            except (json.JSONDecodeError, IndexError):
                return 0, 0, []
        finally:
            # Clean up
            try:
                os.unlink(temp_file)
            except:
                pass


def quick_evolve(code: str, problem_description: str = "", **kwargs) -> EnhancementResult:
    """Quick evolution for code.
    
    Args:
        code: Source code to evolve
        problem_description: Description of the problem
        **kwargs: Additional evolution parameters
        
    Returns:
        EnhancementResult with evolved code
    """
    return evolve_code(code, problem_description, iterations=5, **kwargs)


def evolve_code(
    code: str,
    problem_description: str = "",
    iterations: int = 10,
    **kwargs
) -> EnhancementResult:
    """Evolve code using OpenEvolve PES integration.
    
    Args:
        code: Source code to evolve
        problem_description: Description of the problem
        iterations: Number of evolution iterations
        **kwargs: Additional evolution parameters
        
    Returns:
        EnhancementResult with evolved code
    """
    return enhance_code(
        code=code,
        problem_description=problem_description,
        iterations=iterations,
        **kwargs
    )


__all__ = [
    "OpenEvolvePESEnhancer",
    "OpenEvolveTestGenerator",
    "EnhancementResult",
    "enhance_openevolve_code",
    "enhance_code",
    "evolve_code",
    "quick_enhance",
    "enhance_lean_proof",
    "verify_lean_code",
    "is_lean_code",
    "detect_language"
]


if __name__ == "__main__":
    demo()
