#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OpenEvolve PES Integration Module

This module integrates the content-agnostic PES (Plan-Execute-Summarize) system
with OpenEvolve to enhance code outputs through evolutionary improvement.

Usage:
    from openevolve_pes_integration import enhance_openevolve_code, OpenEvolvePESEnhancer

    # Enhance code generated by OpenEvolve
    enhanced_code = enhance_openevolve_code(code, tests, language="python")
"""

import asyncio
import logging
import sys
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

# Import the agnostic PES system
try:
    from openevolve_agnostic_pes import (
        AgnosticPESEngine,
        EvolutionResult,
        UniversalTestRunner,
        LanguageDetector,
        UniversalCodeAnalyzer,
        UniversalFixGenerator,
    )
    PES_AVAILABLE = True
except ImportError as e:
    PES_AVAILABLE = False
    logging.warning(f"PES system not available: {e}")

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] [OpenEvolve-PES] %(message)s",
    stream=sys.stdout
)
logger = logging.getLogger("OpenEvolve-PES-Integration")


# =============================================================================
# Test Generation for OpenEvolve Outputs
# =============================================================================

class OpenEvolveTestGenerator:
    """
    Generates test cases for OpenEvolve outputs based on code analysis.
    
    This class extracts testable functions from code and generates
    corresponding test cases.
    """
    
    @staticmethod
    def extract_functions(code: str) -> List[Dict[str, Any]]:
        """Extract function definitions from code."""
        functions = []
        
        # Python patterns
        py_pattern = r'def\s+(\w+)\s*\(([^)]*)\)'
        for match in __import__('re').finditer(py_pattern, code):
            functions.append({
                'name': match.group(1),
                'params': match.group(2).strip() if match.group(2) else '',
                'language': 'python'
            })
        
        # PHP patterns
        php_pattern = r'function\s+(\w+)\s*\(([^)]*)\)'
        for match in __import__('re').finditer(php_pattern, code):
            functions.append({
                'name': match.group(1),
                'params': match.group(2).strip() if match.group(2) else '',
                'language': 'php'
            })
        
        # JavaScript patterns
        js_pattern = r'(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)'
        for match in __import__('re').finditer(js_pattern, code):
            functions.append({
                'name': match.group(1),
                'params': match.group(2).strip() if match.group(2) else '',
                'language': 'javascript'
            })
        
        return functions
    
    @staticmethod
    def generate_default_tests(code: str, language: str = 'python') -> List[Dict[str, Any]]:
        """
        Generate default test cases for code.
        
        This creates basic smoke tests that verify the code doesn't crash
        and returns expected data types.
        """
        functions = OpenEvolveTestGenerator.extract_functions(code)
        tests = []
        
        for func in functions:
            func_name = func['name']
            
            # Generate a basic test based on function name and detected patterns
            if 'payment' in func_name.lower() or 'calculate' in func_name.lower():
                # Payment/calculation function tests
                tests.append({
                    'name': f'{func_name}_basic',
                    'input': {'amount': 100},
                    'expected': {'total': 100},  # Basic expectation
                    'function': func_name
                })
            elif 'validate' in func_name.lower() or 'check' in func_name.lower():
                # Validation function tests
                tests.append({
                    'name': f'{func_name}_valid',
                    'input': {'value': 'test@example.com'},
                    'expected': {'valid': True},
                    'function': func_name
                })
            elif 'process' in func_name.lower() or 'handle' in func_name.lower():
                # Processing function tests
                tests.append({
                    'name': f'{func_name}_basic',
                    'input': {'data': {}},
                    'expected': {'success': True},
                    'function': func_name
                })
            else:
                # Generic function test
                tests.append({
                    'name': f'{func_name}_smoke',
                    'input': {},
                    'expected': None,  # Just check it doesn't crash
                    'function': func_name
                })
        
        return tests
    
    @staticmethod
    def generate_inference_tests(code: str, problem_description: str) -> List[Dict[str, Any]]:
        """
        Generate tests based on problem description inference.
        
        Analyzes the problem description to understand what the code
        should do and generates appropriate test cases.
        """
        tests = []
        problem_lower = problem_description.lower()
        
        # Payment/financial tests
        if 'payment' in problem_lower or 'calculate' in problem_lower or 'price' in problem_lower:
            tests = [
                {
                    'name': 'basic_calculation',
                    'input': {'amount': 100},
                    'expected': {'total': 100},
                    'function': 'calculate_payment'
                },
                {
                    'name': 'with_discount',
                    'input': {'amount': 100, 'discount': 10},
                    'expected': {'total': 90},
                    'function': 'calculate_payment'
                },
                {
                    'name': 'zero_amount',
                    'input': {'amount': 0},
                    'expected': {'total': 0},
                    'function': 'calculate_payment'
                },
            ]
        
        # Validation tests
        elif 'valid' in problem_lower or 'check' in problem_lower:
            tests = [
                {
                    'name': 'valid_input',
                    'input': {'value': 'test@example.com'},
                    'expected': {'valid': True},
                    'function': 'validate'
                },
                {
                    'name': 'invalid_input',
                    'input': {'value': 'invalid'},
                    'expected': {'valid': False},
                    'function': 'validate'
                },
            ]
        
        # Order/processing tests
        elif 'order' in problem_lower or 'process' in problem_lower:
            tests = [
                {
                    'name': 'basic_order',
                    'input': {'items': [{'price': 10, 'quantity': 2}]},
                    'expected': {'subtotal': 20},
                    'function': 'process_order'
                },
                {
                    'name': 'empty_order',
                    'input': {'items': []},
                    'expected': {'error': None},
                    'function': 'process_order'
                },
            ]
        
        # Default tests
        if not tests:
            tests = OpenEvolveTestGenerator.generate_default_tests(code)
        
        return tests


# =============================================================================
# OpenEvolve PES Enhancer
# =============================================================================

@dataclass
class EnhancementResult:
    """Result of enhancing OpenEvolve code with PES."""
    original_code: str = ""
    enhanced_code: str = ""
    tests_generated: int = 0
    tests_passed_before: int = 0
    tests_passed_after: int = 0
    improvements: List[str] = field(default_factory=list)
    success: bool = False
    error: Optional[str] = None


class OpenEvolvePESEnhancer:
    """
    Enhances OpenEvolve outputs using the content-agnostic PES system.
    
    This class takes code generated by OpenEvolve and applies
    evolutionary improvement to fix bugs and enhance correctness.
    """
    
    def __init__(self, max_iterations: int = 5):
        """
        Initialize the enhancer.
        
        Args:
            max_iterations: Maximum evolution iterations (default: 5)
        """
        self.max_iterations = max_iterations
        
        if PES_AVAILABLE:
            self.engine = AgnosticPESEngine(max_iterations=max_iterations)
        else:
            self.engine = None
            logger.warning("PES engine not available - enhancement disabled")
    
    def enhance(
        self,
        code: str,
        problem_description: str = "",
        tests: List[Dict[str, Any]] = None,
        language: str = None,
    ) -> EnhancementResult:
        """
        Enhance code using the PES system.
        
        Args:
            code: The code to enhance
            problem_description: Description of what the code should do
            tests: Optional pre-defined test cases
            language: Programming language (auto-detected if not provided)
        
        Returns:
            EnhancementResult with enhanced code and metrics
        """
        result = EnhancementResult(original_code=code)
        
        if not PES_AVAILABLE or self.engine is None:
            result.error = "PES system not available"
            return result
        
        try:
            # Auto-detect language if not provided
            if language is None:
                language = LanguageDetector.detect(code)
            
            result.tests_generated = len(tests) if tests else 0
            
            # Generate tests if not provided
            if not tests:
                if problem_description:
                    tests = OpenEvolveTestGenerator.generate_inference_tests(
                        code, problem_description
                    )
                else:
                    tests = OpenEvolveTestGenerator.generate_default_tests(code)
                result.tests_generated = len(tests)
            
            if not tests:
                result.error = "No tests available for enhancement"
                return result
            
            logger.info(f"Starting enhancement for {len(tests)} tests in {language}")
            
            # Run PES evolution
            evolution_result = asyncio.run(
                self.engine.evolve(code, tests)
            )
            
            # Populate result
            result.enhanced_code = evolution_result.evolved_code
            result.tests_passed_before = evolution_result.tests_passed - (
                1 if evolution_result.improvement > 0 else 0
            )
            result.tests_passed_after = evolution_result.tests_passed
            result.improvements = evolution_result.fixes_applied
            result.success = evolution_result.final_score == 1.0
            
            logger.info(f"Enhancement complete: {result.tests_passed_after}/{result.tests_generated} tests pass")
            
            return result
            
        except Exception as e:
            result.error = str(e)
            logger.error(f"Enhancement failed: {e}")
            return result
    
    def enhance_with_validation(
        self,
        code: str,
        problem_description: str,
        expected_behavior: Dict[str, Any],
    ) -> EnhancementResult:
        """
        Enhance code with explicit expected behavior validation.
        
        Args:
            code: The code to enhance
            problem_description: Description of what the code should do
            expected_behavior: Dictionary of expected function behaviors
        
        Returns:
            EnhancementResult with enhanced code and metrics
        """
        # Convert expected behavior to tests
        tests = []
        for func_name, expected in expected_behavior.items():
            tests.append({
                'name': f'{func_name}_validation',
                'input': expected.get('input', {}),
                'expected': expected.get('output', {}),
                'function': func_name
            })
        
        return self.enhance(code, problem_description, tests)


# =============================================================================
# Convenience Functions
# =============================================================================

def enhance_openevolve_code(
    code: str,
    tests: List[Dict[str, Any]] = None,
    problem_description: str = "",
    language: str = None,
    max_iterations: int = 5,
) -> EnhancementResult:
    """
    Convenience function to enhance OpenEvolve code.
    
    Args:
        code: The code to enhance
        tests: Optional test cases
        problem_description: Description of the problem being solved
        language: Programming language
        max_iterations: Maximum evolution iterations
    
    Returns:
        EnhancementResult with enhanced code
    """
    enhancer = OpenEvolvePESEnhancer(max_iterations=max_iterations)
    return enhancer.enhance(code, problem_description, tests, language)


def quick_enhance(code: str, problem_description: str = "") -> EnhancementResult:
    """
    Quick enhancement with default settings.
    
    Args:
        code: The code to enhance
        problem_description: Description of the problem
    
    Returns:
        EnhancementResult with enhanced code
    """
    return enhance_openevolve_code(code, problem_description=problem_description)


# =============================================================================
# Demo
# =============================================================================

def demo():
    """Demonstrate the OpenEvolve PES integration."""
    
    print("\n" + "="*70)
    print("  OpenEvolve PES Integration Demo")
    print("  Enhancing OpenEvolve Outputs with Content-Agnostic Evolution")
    print("="*70)
    
    # Sample code that might come from OpenEvolve
    code = '''def calculate_payment(amount, discount_code=None, payment_method="credit_card"):
    """Calculate payment with tax, discounts, and fees."""
    subtotal = amount
    discount = 0
    
    # Apply discount
    if discount_code == "SAVE10":
        discount = subtotal * 0.10
    elif discount_code == "SAVE20":
        discount = subtotal * 0.20
    
    # Calculate tax
    taxable = subtotal - discount
    tax = taxable * 0.085
    
    # Payment fee
    fee = 0
    if payment_method == "credit_card":
        fee = subtotal * 0.029
    elif payment_method == "debit_card":
        fee = subtotal * 0.015
    
    total = taxable + tax + fee
    return {"subtotal": subtotal, "discount": discount, "tax": tax, "fee": fee, "total": total}'''
    
    problem_description = "Calculate payment with tax, discounts, and payment method fees"
    
    # Tests that OpenEvolve might generate
    tests = [
        {"name": "Basic payment", "input": {"amount": 100}, "expected": {"total": 111.4}, "function": "calculate_payment"},
        {"name": "10% discount", "input": {"amount": 100, "discount_code": "SAVE10"}, "expected": {"discount": 10}, "function": "calculate_payment"},
        {"name": "PayPal fee", "input": {"amount": 150, "payment_method": "paypal"}, "expected": {"fee": 5.25}, "function": "calculate_payment"},
    ]
    
    print("\nOriginal Code (from OpenEvolve):")
    print(code)
    
    print("\n" + "-"*70)
    print("Enhancing with PES system...")
    
    result = enhance_openevolve_code(
        code=code,
        tests=tests,
        problem_description=problem_description,
        max_iterations=5
    )
    
    print(f"\nEnhancement Result:")
    print(f"  Success: {result.success}")
    print(f"  Tests Generated: {result.tests_generated}")
    print(f"  Tests Passed (After): {result.tests_passed_after}/{result.tests_generated}")
    print(f"  Improvements: {result.improvements}")
    
    if result.error:
        print(f"  Error: {result.error}")
    
    if result.enhanced_code:
        print(f"\nEnhanced Code:")
        print(result.enhanced_code)
    
    return result


if __name__ == "__main__":
    demo()
