# Auto-generated Pydantic models
# Generated by Knowledge Extraction Agent

from pydantic import BaseModel, Field
from typing import Optional

class ProcurementInvoiceinfo(BaseModel):
    suppliername: str = Field(..., description='Name of the supplier')
    supplierid: str = Field(..., description='Unique identifier for the supplier')
    invoicenumber: str = Field(..., description='Unique number identifying the invoice')
    invoicedate: str = Field(..., description='Date the invoice was issued')
    totalamount: float = Field(..., description='Total amount of the invoice')
    currency: str = Field(..., description='Currency of the invoice amount')
    paymentduedate: str = Field(..., description='Date by which payment is due')
