/**
 * Evolution Engine Parameter Schema
 */

import { ParameterSchema } from '@/types/plugin';

export const evolutionParameters: ParameterSchema[] = [
  {
    name: 'content',
    type: 'text',
    label: 'Content to Evolve',
    description: 'The content that will be evolved through genetic algorithms',
    required: true,
    multiline: true,
    defaultValue: '',
    placeholder: 'Enter content to evolve...',
  },
  {
    name: 'iterations',
    type: 'number',
    label: 'Iterations',
    description: 'Number of evolution iterations to perform',
    required: true,
    defaultValue: 10,
    min: 1,
    max: 100,
    step: 1,
  },
  {
    name: 'temperature',
    type: 'slider',
    label: 'Temperature',
    description: 'Creativity temperature (0.0 - 2.0). Higher values increase randomness.',
    required: true,
    defaultValue: 0.7,
    min: 0,
    max: 2,
    step: 0.1,
  },
  {
    name: 'populationSize',
    type: 'number',
    label: 'Population Size',
    description: 'Size of population per generation',
    required: true,
    defaultValue: 5,
    min: 1,
    max: 20,
    step: 1,
  },
  {
    name: 'mutationRate',
    type: 'slider',
    label: 'Mutation Rate',
    description: 'Rate of genetic mutation (0.0 - 1.0)',
    required: true,
    defaultValue: 0.1,
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    name: 'crossoverRate',
    type: 'slider',
    label: 'Crossover Rate',
    description: 'Rate of genetic crossover (0.0 - 1.0)',
    required: true,
    defaultValue: 0.7,
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    name: 'selectionMethod',
    type: 'select',
    label: 'Selection Method',
    description: 'Method for selecting parents for next generation',
    required: true,
    defaultValue: 'tournament',
    options: [
      { value: 'tournament', label: 'Tournament Selection' },
      { value: 'roulette', label: 'Roulette Wheel' },
      { value: 'rank', label: 'Rank-Based Selection' },
      { value: 'steady', label: 'Steady State' },
    ],
  },
  {
    name: 'provider',
    type: 'select',
    label: 'AI Provider',
    description: 'The AI provider to use for evolution',
    required: true,
    defaultValue: 'anthropic',
    options: [
      { value: 'openai', label: 'OpenAI' },
      { value: 'anthropic', label: 'Anthropic' },
      { value: 'google', label: 'Google' },
      { value: 'openrouter', label: 'OpenRouter' },
    ],
  },
  {
    name: 'model',
    type: 'select',
    label: 'Model',
    description: 'The AI model to use',
    required: true,
    defaultValue: 'claude-3-sonnet',
    options: [
      { value: 'gpt-4', label: 'GPT-4' },
      { value: 'gpt-4-turbo', label: 'GPT-4 Turbo' },
      { value: 'claude-3-sonnet', label: 'Claude 3 Sonnet' },
      { value: 'claude-3-opus', label: 'Claude 3 Opus' },
      { value: 'claude-3-haiku', label: 'Claude 3 Haiku' },
      { value: 'gemini-pro', label: 'Gemini Pro' },
    ],
  },
  {
    name: 'objective',
    type: 'textarea',
    label: 'Objective Function',
    description: 'Define the fitness objective (optional custom objective)',
    required: false,
    multiline: true,
    placeholder: 'Define custom fitness criteria...',
  },
  {
    name: 'preserveElite',
    type: 'boolean',
    label: 'Preserve Elite',
    description: 'Preserve best individuals from each generation',
    required: false,
    defaultValue: true,
  },
  {
    name: 'enableLogging',
    type: 'boolean',
    label: 'Enable Logging',
    description: 'Enable detailed logging of evolution process',
    required: false,
    defaultValue: true,
  },
];
