# Model: PO_BOM_Alignment_and_ConsolidationModel
# Generated by Case 2 Hierarchical Extraction

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class PO_BOM_Alignment_and_ConsolidationModel(BaseModel):
    """Generated Pydantic model for Case 2 extraction"""
    materialnumber: str = Field(default=..., description="Material Number from PO, linked to ID in BOM.")
    quantity: int = Field(default=..., description="Quantity from PO.")
    description: str = Field(default=..., description="Description from PO.")
    deliverydate: str = Field(default=..., description="Delivery Date from PO.")
    typepartdesignation: str = Field(default=..., description="Type/Part Designation from BOM.")
    dimensions: str = Field(default=..., description="Dimensions from BOM.")