# Auto-generated Pydantic models
# Generated by Knowledge Extraction Agent

from pydantic import BaseModel, Field, field_validator
from typing import List

class ProcurementDeliveryNoteinfo(BaseModel):
    suppliername: str = Field(..., description='Name of the supplier')
    supplierid: str = Field(..., description='Unique identifier for the supplier')
    shipmentnumber: str = Field(..., description='Unique number identifying the shipment')
    delivereditems: List[str] = Field(..., description='List of items delivered')
    deliveryconfirmationdate: str = Field(..., description='Date confirming delivery of items')

    @field_validator('delivereditems')
    @classmethod
    def validate_delivereditems(cls, v):
        if not isinstance(v, list):
            raise ValueError('delivereditems must be a list')
        return v
