# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

WORKDIR /app/server

COPY server/package.json server/package-lock.json ./
RUN npm install --production --ignore-scripts

COPY server/ ./

CMD ["node", "index.js"]
