"""
Configuration Provider Adapter

Provides configuration values and environment variables for core projects
without modifying core config files.

Handles:
- .env file creation and validation
- Environment variable injection
- Configuration validation
- Directory creation

Usage:
    from integrations.bug_fixes import ConfigProvider

    # Initialize config provider
    provider = ConfigProvider()

    # Setup .env file (creates if missing)
    provider.setup_env()

    # Get environment variables
    api_key = provider.get_env('OPENAI_API_KEY')

    # Validate configuration
    issues = provider.validate_config()
"""

import os
import secrets
import logging
from pathlib import Path
from typing import Dict, Any, Optional, List

logger = logging.getLogger(__name__)


class ConfigProvider:
    """
    Provides configuration management for core projects.

    Creates and manages .env file and other config overrides
    in the integrations layer, not in core projects.
    """

    # Required environment variables
    REQUIRED_VARS = {
        'SECRET_KEY': '32-byte hex string for JWT tokens',
        'KEY_ENCRYPTION_KEY': '32-byte hex string for encrypting API keys',
    }

    # Optional but recommended variables
    RECOMMENDED_VARS = {
        'OPENAI_API_KEY': 'OpenAI API key for LLM operations',
        'ANTHROPIC_API_KEY': 'Anthropic API key for Claude models',
        'GOOGLE_API_KEY': 'Google AI API key for Gemini models',
    }

    def __init__(self, env_path: Optional[str] = None):
        """
        Initialize config provider.

        Args:
            env_path: Path to .env file (defaults to ./integrations/bug_fixes/.env)
        """
        if env_path is None:
            # Place .env in integrations/bug_fixes, not root
            env_path = os.path.join(os.path.dirname(__file__), '.env')

        self.env_path = env_path
        self._env_vars: Dict[str, str] = {}

    def setup_env(self, force: bool = False) -> bool:
        """
        Setup .env file with required variables.

        Args:
            force: Recreate .env even if it exists

        Returns:
            True if setup successful
        """
        if os.path.exists(self.env_path) and not force:
            logger.info(f".env file already exists at {self.env_path}")
            self._load_env()
            return True

        logger.info(f"Creating .env file at {self.env_path}")
        self._generate_env()
        return self._save_env()

    def _generate_env(self) -> None:
        """Generate environment variables with secure defaults."""
        # Generate secure keys
        secret_key = secrets.token_hex(32)
        encryption_key = secrets.token_hex(32)

        self._env_vars = {
            '#': 'Auto-generated by integrations/bug_fixes/ConfigProvider',
            '#': 'DO NOT commit this file to version control',
            '': '',
            '# Security Configuration': '',
            'SECRET_KEY': secret_key,
            'KEY_ENCRYPTION_KEY': encryption_key,
            'JWT_ALGORITHM': 'HS256',
            'ACCESS_TOKEN_EXPIRE_MINUTES': '30',
            'ENABLE_ENCRYPTION': 'true',
            '': '',
            '# Server Configuration': '',
            'SERVER_HOST': '0.0.0.0',
            'SERVER_PORT': '8000',
            'DEBUG': 'false',
            '': '',
            '# LLM Configuration': '',
            'TEMPERATURE': '0.7',
            'MAX_TOKENS': '4096',
            '': '',
            '# Evolution Parameters': '',
            'MAX_ITERATIONS': '100',
            'POPULATION_SIZE': '20',
            'SEED': '42',
            '': '',
            '# Add your API keys below': '',
            '# OPENAI_API_KEY': 'your-openai-api-key-here',
            '# ANTHROPIC_API_KEY': 'your-anthropic-api-key-here',
            '# GOOGLE_API_KEY': 'your-google-api-key-here',
        }

        logger.info("Generated secure configuration keys")

    def _save_env(self) -> bool:
        """Save environment variables to .env file."""
        try:
            os.makedirs(os.path.dirname(self.env_path), exist_ok=True)

            with open(self.env_path, 'w') as f:
                for key, value in self._env_vars.items():
                    if key == '#':
                        f.write(f'# {value}\n')
                    elif key == '':
                        f.write('\n')
                    else:
                        f.write(f'{key}={value}\n')

            logger.info(f"Saved .env file to {self.env_path}")
            return True

        except Exception as e:
            logger.error(f"Failed to save .env file: {e}")
            return False

    def _load_env(self) -> bool:
        """Load environment variables from .env file."""
        try:
            self._env_vars = {}
            with open(self.env_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    if '=' in line:
                        key, value = line.split('=', 1)
                        self._env_vars[key.strip()] = value.strip()

            logger.info(f"Loaded .env file from {self.env_path}")
            return True

        except Exception as e:
            logger.error(f"Failed to load .env file: {e}")
            return False

    def get_env(self, key: str, default: Optional[str] = None) -> Optional[str]:
        """
        Get environment variable value.

        Checks in order:
        1. System environment (os.getenv)
        2. .env file
        3. Default value

        Args:
            key: Environment variable name
            default: Default value if not found

        Returns:
            Environment variable value or default
        """
        # Check system environment first
        value = os.getenv(key)
        if value is not None:
            return value

        # Check .env file
        if not self._env_vars:
            self._load_env()

        value = self._env_vars.get(key)
        if value is not None:
            return value

        return default

    def validate_config(self) -> List[str]:
        """
        Validate configuration and return list of issues.

        Returns:
            List of validation issues (empty if all good)
        """
        issues = []

        # Check required variables
        for var_name, description in self.REQUIRED_VARS.items():
            value = self.get_env(var_name)
            if not value:
                issues.append(f"Missing required variable: {var_name} ({description})")
            elif var_name == 'SECRET_KEY' and len(value) < 32:
                issues.append(f"SECRET_KEY too short (should be 32+ chars)")

        # Check recommended variables
        for var_name, description in self.RECOMMENDED_VARS.items():
            value = self.get_env(var_name)
            if not value or value.startswith('your-'):
                issues.append(f"Recommended variable not set: {var_name} ({description})")

        return issues

    def load_dotenv(self) -> None:
        """
        Load .env file into system environment.

        Makes variables available via os.getenv()
        """
        if not self._load_env():
            return

        for key, value in self._env_vars.items():
            if key not in ('#', ''):
                os.environ[key] = value

        logger.info("Loaded .env variables into environment")

    def ensure_directories(self) -> None:
        """Create required directories."""
        directories = [
            './crewai_worktrees',
            './llm_cache',
            './integrations/bug_fixes/logs',
        ]

        for dir_path in directories:
            try:
                os.makedirs(dir_path, exist_ok=True)
                logger.debug(f"Ensured directory exists: {dir_path}")
            except Exception as e:
                logger.warning(f"Could not create directory {dir_path}: {e}")


# Convenience functions
def setup_config(force: bool = False) -> ConfigProvider:
    """
    Quick setup for configuration.

    Usage:
        from integrations.bug_fixes.config_provider import setup_config

        provider = setup_config()
        provider.load_dotenv()
    """
    provider = ConfigProvider()
    provider.setup_env(force=force)
    provider.ensure_directories()
    return provider


def get_env(key: str, default: Optional[str] = None) -> Optional[str]:
    """
    Quick access to environment variables.

    Usage:
        from integrations.bug_fixes.config_provider import get_env

        api_key = get_env('OPENAI_API_KEY')
    """
    provider = ConfigProvider()
    return provider.get_env(key, default=default)
