# Auto-generated Pydantic models
# Generated by Knowledge Extraction Agent

from pydantic import BaseModel, Field, field_validator
from typing import List

class ProcurementPurchaseOrderinfo(BaseModel):
    suppliername: str = Field(..., description='Name of the supplier')
    supplierid: str = Field(..., description='Unique identifier for the supplier')
    ordernumber: str = Field(..., description='Unique number identifying the purchase order')
    ordereditems: List[str] = Field(..., description='List of items ordered')
    quantities: List[str] = Field(..., description='Quantities for each ordered item')
    deliverydates: List[str] = Field(..., description='Delivery dates for each ordered item')

    @field_validator('ordereditems')
    @classmethod
    def validate_ordereditems(cls, v):
        if not isinstance(v, list):
            raise ValueError('ordereditems must be a list')
        return v

    @field_validator('quantities')
    @classmethod
    def validate_quantities(cls, v):
        if not isinstance(v, list):
            raise ValueError('quantities must be a list')
        return v

    @field_validator('deliverydates')
    @classmethod
    def validate_deliverydates(cls, v):
        if not isinstance(v, list):
            raise ValueError('deliverydates must be a list')
        return v
