/**
 * API Types for OpenEvolve Integration Library
 *
 * Defines the core types used throughout the API client layer
 */

import { IntegrationError } from './errors';

/**
 * Middleware function for execution pipeline
 */
export type Middleware = (
  context: {
    integration: string;
    inputs: any;
    options?: ExecutionOptions;
    executionId: string;
  },
  next: () => Promise<any>
) => Promise<any>;


/**
 * Circuit breaker configuration
 */
export interface CircuitBreakerConfig {
  /** Whether the circuit breaker is enabled */
  enabled: boolean;
  /** Number of failures before opening the circuit */
  failureThreshold: number;
  /** Time in milliseconds to wait before attempting to close the circuit */
  resetTimeout: number;
  /** Number of successes required in half-open state to close the circuit */
  successThreshold: number;
}

/**
 * Circuit breaker state
 */
export type CircuitState = 'closed' | 'open' | 'half-open';

/**
 * Client configuration
 */
export interface ClientConfig {
  /** Base URL for the OpenEvolve backend */
  baseUrl: string;
  /** Request timeout in milliseconds (default: 30000) */
  timeout?: number;
  /** Number of retry attempts for failed requests (default: 3) */
  retryAttempts?: number;
  /** Default retry configuration */
  retryConfig?: Partial<RetryConfig>;
  /** Circuit breaker configuration */
  circuitBreakerConfig?: Partial<CircuitBreakerConfig>;
  /** Optional health check interval in milliseconds (disable if 0 or undefined) */
  healthCheckInterval?: number;
  /** Enable WebSocket connections (default: true) */

  enableWebSocket?: boolean;

  /** Enable debug logging (default: false) */
  debug?: boolean;
  /** API key for authentication */
  apiKey?: string;
  /** Custom headers to include with all requests */
  headers?: Record<string, string>;
  /** Middleware functions to run before execution */
  middleware?: Middleware[];
  /** Global request transform */
  requestTransform?: RequestTransform;
  /** Global response transform */
  responseTransform?: ResponseTransform;
  /** Global error callback */
  onError?: (error: IntegrationError) => void;
}


/**
 * Execution options for integration calls
 */
export interface ExecutionOptions {
  /** Unique execution ID (autogenerated if not provided) */
  executionId?: string;
  /** Override default timeout */
  timeout?: number;
  /** Number of retries for this specific request */
  retries?: number;
  /** Custom retry configuration for this request */
  retryConfig?: Partial<RetryConfig>;
  /** Enable streaming responses */
  stream?: boolean;
  /** Callback for progress updates */
  onProgress?: (update: ProgressUpdate) => void;
  /** Callback when execution completes */
  onComplete?: (result: any) => void;
  /** Callback when execution fails */
  onError?: (error: IntegrationError) => void;
  /** Callback when a retry is attempted */
  onRetry?: (error: IntegrationError, attempt: number, delay: number) => void;
  /** Fallback data to return if execution fails */
  fallback?: any;
  /** Abort signal for cancellation */


  signal?: AbortSignal;
  /** Custom metadata for this execution */
  metadata?: Record<string, any>;
  /** Bypass cache if middleware is used */
  bypassCache?: boolean;
}

/**
 * Progress update during execution
 */
export interface ProgressUpdate {
  /** Integration generating the update */
  integration: string;
  /** Unique execution ID */
  executionId: string;
  /** Progress percentage (0-100) */
  progress: number;
  /** Status message */
  message: string;
  /** Timestamp of update (ISO 8601) */
  timestamp: string;
  /** Optional data payload */
  data?: any;
  /** Current stage of execution */
  stage?: string;
  /** Estimated time remaining (milliseconds) */
  eta?: number;
}

/**
 * Batch request
 */
export interface BatchRequest<TInputs> {
  /** Integration name */
  integration: string;
  /** Unique request ID */
  id: string;
  /** Input data */
  inputs: TInputs;
  /** Execution options for this request */
  options?: ExecutionOptions;
}

/**
 * Batch result
 */
export interface BatchResult<TResult> {
  /** Request ID */
  id: string;
  /** Result data (null if failed) */
  result: TResult | null;
  /** Error (null if successful) */
  error: IntegrationError | null;
  /** Execution time in milliseconds */
  executionTime: number;
  /** Success status */
  success: boolean;
}


/**
 * Health status
 */
export interface HealthStatus {
  /** Overall health status */
  status: 'healthy' | 'degraded' | 'unhealthy';
  /** Backend status */
  backend: BackendStatus;
  /** Integration-specific status */
  integrations: Record<string, IntegrationHealth>;
  /** Timestamp of check */
  timestamp: string;
}

/**
 * Backend status
 */
export interface BackendStatus {
  /** Whether backend is responding */
  online: boolean;
  /** Backend version */
  version: string;
  /** Uptime in seconds */
  uptime: number;
  /** Active connections */
  activeConnections: number;
  /** Memory usage */
  memory: {
    used: number;
    total: number;
    percentage: number;
  };
  /** CPU usage percentage */
  cpu: number;
}

/**
 * Integration health
 */
export interface IntegrationHealth {
  /** Integration name */
  name: string;
  /** Status */
  status: 'available' | 'unavailable' | 'degraded';
  /** Response time in milliseconds */
  responseTime: number;
  /** Last error (if any) */
  lastError?: string;
  /** Available endpoints */
  endpoints: string[];
}

/**
 * WebSocket message
 */
export interface WebSocketMessage {
  /** Message type */
  type: 'progress' | 'complete' | 'error' | 'status';
  /** Integration name */
  integration?: string;
  /** Execution ID */
  executionId?: string;
  /** Message data */
  data: any;
  /** Timestamp */
  timestamp: string;
}

/**
 * Request transform function
 */
export type RequestTransform = (data: any) => any;

/**
 * Response transform function
 */
export type ResponseTransform = (data: any) => any;

/**
 * Error transform function
 */
export type ErrorTransform = (error: any) => IntegrationError;


/**
 * Connection state
 */
export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'reconnecting' | 'disconnecting';

/**
 * Integration adapter interface
 */
export interface IntegrationAdapter {
  /** Integration name */
  name: string;
  /** Get integration version */
  getVersion(): string;
  /** Execute integration */
  execute<TInputs, TResult>(
    inputs: TInputs,
    options?: ExecutionOptions
  ): Promise<TResult>;
  /** Stream execution */
  executeStream<TInputs, TResult>(
    inputs: TInputs,
    onProgress: (update: ProgressUpdate) => void,
    options?: ExecutionOptions
  ): Promise<TResult>;
  /** Health check */
  healthCheck(): Promise<IntegrationHealth>;
  /** Validate inputs */
  validate<TInputs>(inputs: TInputs): Promise<ValidationResult>;
}

/**
 * Validation result
 */
export interface ValidationResult {
  /** Whether validation passed */
  valid: boolean;
  /** Validation errors */
  errors: ValidationErrorItem[];
  /** Warnings */
  warnings: ValidationWarning[];
}

/**
 * Validation error item
 */
export interface ValidationErrorItem {
  /** Field path */
  field: string;
  /** Error message */
  message: string;
  /** Error code */
  code: string;
  /** Name of the error (optional for interface compatibility) */
  name?: string;
}

/**
 * Parameter schema for validation
 */
export interface ParameterSchema {
  type: string;
  properties?: Record<string, any>;
  required?: string[];
  description?: string;
  enum?: any[];
  [key: string]: any;
}

/**
 * Validation warning
 */
export interface ValidationWarning {
  /** Field path */
  field: string;
  /** Warning message */
  message: string;
  /** Warning code */
  code: string;
}

/**
 * Retry configuration
 */
export interface RetryConfig {
  /** Maximum number of attempts */
  maxAttempts: number;
  /** Initial delay in milliseconds */
  initialDelay: number;
  /** Maximum delay in milliseconds */
  maxDelay: number;
  /** Backoff multiplier */
  backoffMultiplier: number;
  /** Whether to retry on 4xx errors */
  retryOn4xx: boolean;
  /** Whether to retry on 5xx errors */
  retryOn5xx: boolean;
  /** HTTP status codes to retry */
  retryableStatusCodes: number[];
}

/**
 * Request metrics
 */
export interface RequestMetrics {
  /** Request ID */
  requestId: string;
  /** Integration name */
  integration: string;
  /** Start timestamp */
  startTime: string;
  /** End timestamp */
  endTime: string;
  /** Duration in milliseconds */
  duration: number;
  /** Number of retries */
  retries: number;
  /** Success status */
  success: boolean;
  /** HTTP status code */
  statusCode?: number;
  /** Error message */
  error?: string;
}

/**
 * API response wrapper
 */
export interface ApiResponse<T> {
  /** Response data */
  data: T;
  /** Response metadata */
  meta: ResponseMeta;
}

/**
 * Response metadata
 */
export interface ResponseMeta {
  /** Request ID */
  requestId: string;
  /** Timestamp */
  timestamp: string;
  /** Execution time */
  executionTime: number;
  /** Whether response was cached */
  cached: boolean;
  /** Rate limit info */
  rateLimit?: {
    limit: number;
    remaining: number;
    reset: string;
  };
}
