# Auto-generated Pydantic models
# Generated by Knowledge Extraction Agent

from pydantic import BaseModel, Field, field_validator
from enum import Enum
from typing import List

class CompanyType(str, Enum):
    STARTUP = "startup"
    ESTABLISHED = "established"

class AiMaturityLevel(str, Enum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"

class AiField(str, Enum):
    GENERATIVE_AI = "Generative AI"
    MACHINE_LEARNING = "machine learning"
    PREDICTIVE_ANALYTICS = "predictive analytics"
    RULE_BASED_SYSTEMS = "Rule-based systems"
    OTHER = "Other"

class CompanyDomain(str, Enum):
    ARTS_ENTERTAINMENT = "Arts & entertainment"
    AUTOMOTIVE = "Automotive"
    BUSINESS_ENHANCEMENT = "Business enhancement"
    CONSTRUCTION = "Construction"
    CULTURAL_CREATIVE_INDUSTRIES = "Cultural & creative industries"
    DEFENSE = "Defense"
    EDUCATION_TRAINING = "Education & training"
    ENVIRONMENT_SUSTAINABILITY = "Environment & sustainability"
    FINANCE = "Finance"
    HEALTHCARE_WELLBEING = "Healthcare & wellbeing"
    IMMIGRATION = "Immigration"
    MANUFACTURING = "Manufacturing"
    PROPERTY_REAL_ESTATE = "Property and real estate sector"
    SECURITY = "Security"
    SMART_CITIES = "Smart cities"
    TRANSPORT_LOGISTICS = "Transport & logistics"
    TRAVEL_TOURISM = "Travel & tourism"

class ServicesSought(str, Enum):
    AI_ROADMAP_DESIGN = "AI roadmap design"
    TECHNICAL_GUIDANCE = "technical guidance"
    PROOF_OF_CONCEPT_DEVELOPMENT = "proof of concept development"
    STUDENT_THESIS_PROJECT = "student thesis project"
    NETWORKING_SUPPORT = "networking support"
    DATA_COLLECTION = "data collection"

class AIConsultancyReportsInfo(BaseModel):
    companyname: str = Field(..., description='The name of the company receiving consultancy')
    expertnames: List[str] = Field(..., description='Names of the experts who provided consultancy')
    customermanagername: str = Field(..., description='Name of the customer manager')
    consultancydate: str = Field(..., description='Date when the consultancy took place')
    companytype: CompanyType = Field(..., description='Type of company based on maturity')
    aimaturitylevel: AiMaturityLevel = Field(..., description="Company's current AI maturity level")
    aifield: AiField = Field(..., description='The AI field the company is interested in')
    intendedaiidea: str = Field(..., description="Company's intended AI idea described in a concise phrase")
    companydomain: CompanyDomain = Field(..., description='The domain in which the company operates')
    targetgroups: List[str] = Field(..., description="Company's target groups or customer segments")
    servicessought: List[ServicesSought] = Field(..., description='Services that the company is seeking from the consultancy')
    keyrecommendations: List[str] = Field(..., description='Key recommendations provided by the experts')

    @field_validator('expertnames')
    @classmethod
    def validate_expertnames(cls, v):
        if not isinstance(v, list):
            raise ValueError('expertnames must be a list')
        return v

    @field_validator('targetgroups')
    @classmethod
    def validate_targetgroups(cls, v):
        if not isinstance(v, list):
            raise ValueError('targetgroups must be a list')
        return v

    @field_validator('servicessought')
    @classmethod
    def validate_servicessought(cls, v):
        if not isinstance(v, list):
            raise ValueError('servicessought must be a list')
        return v

    @field_validator('keyrecommendations')
    @classmethod
    def validate_keyrecommendations(cls, v):
        if not isinstance(v, list):
            raise ValueError('keyrecommendations must be a list')
        return v
