# Auto-generated Pydantic models
# Generated by Knowledge Extraction Agent

from pydantic import BaseModel, Field
from typing import Optional

class PodataextractionInfo(BaseModel):
    materialnumber: str = Field(..., description='Material Number from PO that links to ID in BOM')
    quantity: int = Field(..., description='Quantity of the item from the Purchase Order')
    description: str = Field(..., description='Description of the item from the Purchase Order')
    deliverydate: str = Field(..., description='Delivery date for the item from the Purchase Order')
    typepartdesignation: str = Field(..., description='Type/Part Designation from the matching BOM')
    dimensions: str = Field(..., description='Dimensions of the part from the matching BOM')
