# Model: POItemExtractionModel
# Generated by Case 2 Hierarchical Extraction

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class POItemExtractionModel(BaseModel):
    """Generated Pydantic model for Case 2 extraction"""
    materialnumber: str = Field(default=..., description="Unique identifier for the item; used for linking with BOM.")
    quantity: int = Field(default=..., description="Number of units ordered.")
    description: str = Field(default=..., description="Description of the item.")
    deliverydate: str = Field(default=..., description="Required delivery date for the item.")