#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Data schemas and models for the Trading Strategy Evolution System.

Defines the core data structures used throughout the system.
"""

from dataclasses import dataclass, field
from datetime import datetime, UTC
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
import json
import numpy as np


class StrategyType(Enum):
    """Types of trading strategies."""
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    STATISTICAL_ARBITRAGE = "statistical_arbitrage"
    MARKET_MAKING = "market_making"
    TREND_FOLLOWING = "trend_following"
    PAIRS_TRADING = "pairs_trading"
    OPTIONS_STRATEGY = "options_strategy"
    MACHINE_LEARNING = "machine_learning"
    HYBRID = "hybrid"


class MarketRegime(Enum):
    """Market regime classifications."""
    BULL = "bull"
    BEAR = "bear"
    SIDEWAYS = "sideways"
    HIGH_VOLATILITY = "high_volatility"
    LOW_VOLATILITY = "low_volatility"
    CRISIS = "crisis"


class SignalType(Enum):
    """Types of trading signals."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE_POSITION = "close_position"


@dataclass
class MarketData:
    """
    Market data snapshot.

    Attributes:
        timestamp: When the data was recorded
        symbol: Trading symbol
        price: Current price
        volume: Trading volume
        bid: Bid price
        ask: Ask price
        ohlc: Open, High, Low, Close
        indicators: Technical indicators
        fundamentals: Fundamental data
        alternative_data: Alternative data sources
    """
    timestamp: datetime
    symbol: str
    price: float
    volume: float
    bid: Optional[float] = None
    ask: Optional[float] = None
    ohlc: Optional[Tuple[float, float, float, float]] = None  # (O, H, L, C)
    indicators: Dict[str, float] = field(default_factory=dict)
    fundamentals: Dict[str, Any] = field(default_factory=dict)
    alternative_data: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "timestamp": self.timestamp.isoformat(),
            "symbol": self.symbol,
            "price": self.price,
            "volume": self.volume,
            "bid": self.bid,
            "ask": self.ask,
            "ohlc": self.ohlc,
            "indicators": self.indicators,
            "fundamentals": self.fundamentals,
            "alternative_data": self.alternative_data
        }


@dataclass
class TradeSignal:
    """
    Trading signal generated by a strategy.

    Attributes:
        strategy_id: ID of strategy that generated signal
        timestamp: When signal was generated
        symbol: Trading symbol
        signal_type: BUY, SELL, HOLD, CLOSE_POSITION
        confidence: Signal confidence (0.0 to 1.0)
        expected_return: Expected return
        risk_estimate: Estimated risk
        holding_period: Expected holding period
        reasoning: Explanation of the signal
        metadata: Additional signal metadata
    """
    strategy_id: str
    timestamp: datetime
    symbol: str
    signal_type: SignalType
    confidence: float
    expected_return: float
    risk_estimate: float
    holding_period: Optional[timedelta] = None
    reasoning: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "strategy_id": self.strategy_id,
            "timestamp": self.timestamp.isoformat(),
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "confidence": self.confidence,
            "expected_return": self.expected_return,
            "risk_estimate": self.risk_estimate,
            "holding_period": str(self.holding_period) if self.holding_period else None,
            "reasoning": self.reasoning,
            "metadata": self.metadata
        }


@dataclass
class Strategy:
    """
    Trading strategy definition.

    Attributes:
        strategy_id: Unique identifier
        name: Strategy name
        description: Strategy description
        strategy_type: Type of strategy
        parameters: Strategy parameters
        entry_conditions: Entry logic
        exit_conditions: Exit logic
        risk_rules: Risk management rules
        metadata: Additional metadata
    """
    strategy_id: str
    name: str
    description: str
    strategy_type: StrategyType
    parameters: Dict[str, Any] = field(default_factory=dict)
    entry_conditions: List[str] = field(default_factory=list)
    exit_conditions: List[str] = field(default_factory=list)
    risk_rules: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "description": self.description,
            "strategy_type": self.strategy_type.value,
            "parameters": self.parameters,
            "entry_conditions": self.entry_conditions,
            "exit_conditions": self.exit_conditions,
            "risk_rules": self.risk_rules,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat()
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Strategy":
        """Create Strategy from dictionary."""
        return cls(
            strategy_id=data["strategy_id"],
            name=data["name"],
            description=data["description"],
            strategy_type=StrategyType(data["strategy_type"]),
            parameters=data.get("parameters", {}),
            entry_conditions=data.get("entry_conditions", []),
            exit_conditions=data.get("exit_conditions", []),
            risk_rules=data.get("risk_rules", {}),
            metadata=data.get("metadata", {}),
            created_at=datetime.fromisoformat(data["created_at"]) if "created_at" in data else datetime.now(UTC)
        )


@dataclass
class StrategyVariant:
    """
    A variant of a base strategy with modified parameters.

    Attributes:
        variant_id: Unique identifier
        parent_strategy_id: Parent strategy ID
        name: Variant name
        parameters: Modified parameters
        generation: Which evolution generation
        status: Current status
        created_at: When variant was created
    """
    variant_id: str
    parent_strategy_id: str
    name: str
    parameters: Dict[str, Any]
    generation: int = 0
    status: str = "initialized"  # initialized, testing, active, pruned
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "variant_id": self.variant_id,
            "parent_strategy_id": self.parent_strategy_id,
            "name": self.name,
            "parameters": self.parameters,
            "generation": self.generation,
            "status": self.status,
            "created_at": self.created_at.isoformat()
        }


@dataclass
class StrategyPerformance:
    """
    Performance metrics for a strategy or variant.

    Attributes:
        strategy_id: Strategy ID
        period: Performance period
        total_return: Total return
        sharpe_ratio: Sharpe ratio
        sortino_ratio: Sortino ratio
        max_drawdown: Maximum drawdown
        win_rate: Win rate
        profit_factor: Profit factor
        avg_win: Average win
        avg_loss: Average loss
        trades: Number of trades
        volatility: Volatility
        beta: Beta
        alpha: Alpha
        calmar_ratio: Calmar ratio
        sharpe_information_ratio: Information ratio
        metrics_history: Historical metrics
    """
    strategy_id: str
    period: str  # "daily", "weekly", "monthly", "all_time"
    total_return: float
    sharpe_ratio: float
    sortino_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    trades: int = 0
    volatility: float = 0.0
    beta: float = 0.0
    alpha: float = 0.0
    calmar_ratio: float = 0.0
    information_ratio: float = 0.0
    metrics_history: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "strategy_id": self.strategy_id,
            "period": self.period,
            "total_return": self.total_return,
            "sharpe_ratio": self.sharpe_ratio,
            "sortino_ratio": self.sortino_ratio,
            "max_drawdown": self.max_drawdown,
            "win_rate": self.win_rate,
            "profit_factor": self.profit_factor,
            "avg_win": self.avg_win,
            "avg_loss": self.avg_loss,
            "trades": self.trades,
            "volatility": self.volatility,
            "beta": self.beta,
            "alpha": self.alpha,
            "calmar_ratio": self.calmar_ratio,
            "information_ratio": self.information_ratio,
            "metrics_history": self.metrics_history
        }

    def calculate_fitness(self, weights: Optional[Dict[str, float]] = None) -> float:
        """
        Calculate composite fitness score.

        Args:
            weights: Optional custom weights for metrics

        Returns:
            Composite fitness score
        """
        weights = weights or {
            "return": 0.3,
            "sharpe": 0.25,
            "drawdown": -0.2,  # Negative because lower is better
            "win_rate": 0.1,
            "profit_factor": 0.1,
            "calmar": 0.05
        }

        fitness = (
            weights["return"] * self.total_return +
            weights["sharpe"] * self.sharpe_ratio +
            weights["drawdown"] * self.max_drawdown +
            weights["win_rate"] * self.win_rate +
            weights["profit_factor"] * min(self.profit_factor, 5.0) / 5.0 +
            weights["calmar"] * min(self.calmar_ratio, 5.0) / 5.0
        )

        return fitness


@dataclass
class EvolutionState:
    """
    State of the strategy evolution process.

    Attributes:
        generation: Current generation
        best_strategy_id: ID of best performing strategy
        best_fitness: Best fitness score
        population: Current population of variants
        diversity_metrics: Population diversity metrics
        convergence_metrics: Convergence metrics
        causal_models: Learned causal models
        knowledge_artifacts: Accumulated knowledge
        timestamp: Last update timestamp
    """
    generation: int = 0
    best_strategy_id: Optional[str] = None
    best_fitness: float = 0.0
    population: List[StrategyVariant] = field(default_factory=list)
    diversity_metrics: Dict[str, float] = field(default_factory=dict)
    convergence_metrics: Dict[str, float] = field(default_factory=dict)
    causal_models: List[Dict[str, Any]] = field(default_factory=list)
    knowledge_artifacts: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "generation": self.generation,
            "best_strategy_id": self.best_strategy_id,
            "best_fitness": self.best_fitness,
            "population": [v.to_dict() for v in self.population],
            "diversity_metrics": self.diversity_metrics,
            "convergence_metrics": self.convergence_metrics,
            "causal_models": self.causal_models,
            "knowledge_artifacts": self.knowledge_artifacts,
            "timestamp": self.timestamp.isoformat()
        }


@dataclass
class CausalRelationship:
    """
    Learned causal relationship.

    Attributes:
        cause: Cause variable
        effect: Effect variable
        strength: Causal strength (-1 to 1)
        confidence: Confidence in relationship (0 to 1)
        mechanism: Proposed mechanism
        evidence: Supporting evidence
        context: Context where relationship holds
    """
    cause: str
    effect: str
    strength: float
    confidence: float
    mechanism: str
    evidence: List[Dict[str, Any]]
    context: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "cause": self.cause,
            "effect": self.effect,
            "strength": self.strength,
            "confidence": self.confidence,
            "mechanism": self.mechanism,
            "evidence": self.evidence,
            "context": self.context
        }


@dataclass
class JudgeEvaluation:
    """
    Evaluation from a single judge perspective.

    Attributes:
        judge_id: Judge identifier
        perspective: Evaluation perspective
        score: Assigned score (0 to 1)
        reasoning: Evaluation reasoning
        concerns: Identified concerns
        recommendations: Recommendations
    """
    judge_id: str
    perspective: str
    score: float
    reasoning: str
    concerns: List[str]
    recommendations: List[str]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "judge_id": self.judge_id,
            "perspective": self.perspective,
            "score": self.score,
            "reasoning": self.reasoning,
            "concerns": self.concerns,
            "recommendations": self.recommendations
        }
