# Auto-generated Pydantic models
# Generated by Knowledge Extraction Agent

from pydantic import BaseModel, Field, field_validator
from typing import List

class ProcurementInfo(BaseModel):
    suppliername: str = Field(..., description='The name of the supplier')
    supplierid: str = Field(..., description='The unique identifier for the supplier')
    ordernumber: str = Field(..., description='The purchase order number')
    ordereditems: List[str] = Field(..., description='List of items ordered in the purchase order')
    quantities: List[str] = Field(..., description='List of quantities for each ordered item')
    deliverydates: List[str] = Field(..., description='List of delivery dates for ordered items')
    invoicenumber: str = Field(..., description='The invoice number')
    invoicedate: str = Field(..., description='The date the invoice was issued')
    totalamount: float = Field(..., description='The total amount on the invoice')
    currency: str = Field(..., description='The currency of the invoice amount')
    paymentduedate: str = Field(..., description='The date payment is due for the invoice')
    shipmentnumber: str = Field(..., description='The shipment number from delivery notes')
    delivereditems: List[str] = Field(..., description='List of items delivered according to delivery notes')
    deliveryconfirmationdate: str = Field(..., description='The date delivery was confirmed')

    @field_validator('ordereditems')
    @classmethod
    def validate_ordereditems(cls, v):
        if not isinstance(v, list):
            raise ValueError('ordereditems must be a list')
        return v

    @field_validator('quantities')
    @classmethod
    def validate_quantities(cls, v):
        if not isinstance(v, list):
            raise ValueError('quantities must be a list')
        return v

    @field_validator('deliverydates')
    @classmethod
    def validate_deliverydates(cls, v):
        if not isinstance(v, list):
            raise ValueError('deliverydates must be a list')
        return v

    @field_validator('delivereditems')
    @classmethod
    def validate_delivereditems(cls, v):
        if not isinstance(v, list):
            raise ValueError('delivereditems must be a list')
        return v
