"""
Auto-generated Extraction Prompt with Embedded Models
Generated by Knowledge Extraction Agent
This file contains a complete, self-contained extraction prompt system.
"""

EXTRACTION_PROMPT = """
TASK: Procurement

EXTRACTION TASK:
To extract key information from various documents

EMBEDDED PYDANTIC MODELS:
```python
```python
from pydantic import BaseModel, Field, field_validator
from typing import List

class ProcurementInfo(BaseModel):
    suppliername: str = Field(..., description="The name of the supplier")
    supplierid: str = Field(..., description="The unique identifier for the supplier")
    ordernumber: str = Field(..., description="The purchase order number")
    ordereditems: List[str] = Field(..., description="List of items ordered in the purchase order")
    quantities: List[str] = Field(..., description="List of quantities for each ordered item")
    deliverydates: List[str] = Field(..., description="List of delivery dates for ordered items")
    invoicenumber: str = Field(..., description="The invoice number")
    invoicedate: str = Field(..., description="The date the invoice was issued")
    totalamount: float = Field(..., description="The total amount on the invoice")
    currency: str = Field(..., description="The currency of the invoice amount")
    paymentduedate: str = Field(..., description="The date payment is due for the invoice")
    shipmentnumber: str = Field(..., description="The shipment number from delivery notes")
    delivereditems: List[str] = Field(..., description="List of items delivered according to delivery notes")
    deliveryconfirmationdate: str = Field(..., description="The date delivery was confirmed")

    @field_validator('ordereditems')
    @classmethod
    def validate_ordereditems(cls, v):
        if not isinstance(v, list):
            raise ValueError('ordereditems must be a list')
        return v

    @field_validator('quantities')
    @classmethod
    def validate_quantities(cls, v):
        if not isinstance(v, list):
            raise ValueError('quantities must be a list')
        return v

    @field_validator('deliverydates')
    @classmethod
    def validate_deliverydates(cls, v):
        if not isinstance(v, list):
            raise ValueError('deliverydates must be a list')
        return v

    @field_validator('delivereditems')
    @classmethod
    def validate_delivereditems(cls, v):
        if not isinstance(v, list):
            raise ValueError('delivereditems must be a list')
        return v
```
```

CRITICAL EXTRACTION RULES:
1. ACCURACY & VERIFICATION:
   - Extract information ONLY from the provided text
   - Never fabricate, infer, or guess any information
   - Use 'n/a' for any fields where information is not explicitly stated
   - Verify all extracted data against the source text
   - Maintain exact values, dates, and numerical figures as written

2. DATA HANDLING:
   - For dates: Use DD-MM-YYYY format when possible
   - For numbers: Preserve original precision and units
   - For text: Maintain original spelling and capitalization
   - For lists: Extract all relevant items, remove duplicates
   - For enums: Choose ONLY from the specified options AND return the STRING VALUE, not the enum member name
   - For the extracted fields whose length exceeds 30 words, summarize their text into less than 30 words comprising very brief key phrases separated by semi-colon.

3. FIELD VALIDATION:
   - Enum fields must match one of the specified values exactly
   - For enum fields: Return the STRING VALUE (e.g., "moderate") NOT the enum member name (e.g., "MODERATE")
   - List fields should contain valid, non-empty items
   - Numerical fields should be valid numbers in correct format

4. ENUM FIELD HANDLING (CRITICAL):
   - For enum fields, ALWAYS return the string value, NEVER the enum member name
   - Example: For AiMaturityLevel enum, return "moderate" NOT "MODERATE"
   - Example: For CompanyType enum, return "startup" NOT "STARTUP"
   - Example: For AiField enum, return "machine learning" NOT "MACHINE_LEARNING"
   - The JSON output must contain the actual string values that match the enum definitions

5. QUALITY ASSURANCE:
   - Double-check all extracted information against source
   - Ensure no information is duplicated across fields
   - Verify that field types match the expected data types
   - Confirm that all required fields are addressed
   - Validate that enum selections are from available options
   - CRITICAL: Verify enum fields return string values, not member names


OUTPUT FORMAT:
Return the extracted information as a JSON object that exactly matches the ProcurementInfo structure shown above.

CRITICAL: All JSON field names MUST be in snake_case format (lowercase with underscores) to match the model exactly.
For example: "due_date", "bank_name", "car_type" - NOT "Due date", "bank name", "car type"

Example output structure:
```json
{
  "field_name_1": "extracted_value_or_n/a",
  "field_name_2": ["list", "of", "values"],
  "field_name_3": "enum_option_or_n/a"
}
```

VALIDATION CHECKLIST:
Before returning your response, verify:
- All required fields are populated or marked 'n/a'
- All enum fields contain valid options only AND return STRING VALUES (not member names)
- All numerical fields contain valid numbers
- All date fields follow proper format
- No information is fabricated or inferred
- JSON structure matches the model exactly
- Field names match the model exactly (snake_case)
- Data types are appropriate for each field
- CRITICAL: Enum fields return values like "moderate", "startup", "machine learning" NOT "MODERATE", "STARTUP", "MACHINE_LEARNING"

FINAL INSTRUCTIONS:
- Process the document systematically
- Extract information field by field as specified above
- Maintain accuracy over completeness
- When in doubt, use 'n/a' rather than guessing
- Return only the JSON object with extracted data
- Ensure the output can be parsed as valid JSON
"""

def get_extraction_prompt():
    """Return the complete extraction prompt with embedded models"""
    return EXTRACTION_PROMPT
