"""
Red Team Integration with Fuzzing

Integrates automated fuzzing into the Red Team workflow to find
vulnerabilities and edge cases in solutions generated by the Blue Team.
"""

from typing import Dict, List, Any, Optional, Callable
from dataclasses import dataclass, field
from datetime import datetime
import logging

from .fuzzing import (
    SolutionFuzzer,
    FuzzInputGenerator,
    FuzzResult,
    Vulnerability,
    VulnerabilitySeverity,
)
from .crash_analyzer import (
    CrashAnalyzer,
    CrashReporter,
    CrashReport,
)

logger = logging.getLogger(__name__)


@dataclass
class RedTeamAttackResult:
    """Result of a Red Team attack (including fuzzing)"""
    attack_id: str
    target_solution: Any
    logical_attacks: List[Dict[str, Any]] = field(default_factory=list)
    fuzz_results: Optional[FuzzResult] = None
    crash_report: Optional[CrashReport] = None
    vulnerabilities_found: int = 0
    critical_vulnerabilities: int = 0
    execution_time: float = 0.0
    passed: bool = False
    confidence: float = 0.0


class RedTeamWithFuzzing:
    """
    Enhanced Red Team that combines logical attacks with automated fuzzing.

    Workflow:
    1. Blue Team generates a solution
    2. Red Team performs logical attacks
    3. Red Team runs automated fuzzing
    4. Results are aggregated and reported
    5. Gold Team makes final judgment
    """

    def __init__(
        self,
        fuzzing_enabled: bool = True,
        fuzz_iterations: int = 1000,
        fuzz_timeout: float = 5.0,
        max_concurrent_fuzz: int = 4,
        logical_attackers: List[Callable] = None
    ):
        self.fuzzing_enabled = fuzzing_enabled
        self.fuzz_iterations = fuzz_iterations
        self.fuzz_timeout = fuzz_timeout
        self.max_concurrent_fuzz = max_concurrent_fuzz
        self.logical_attackers = logical_attackers or []

        # Initialize fuzzing components
        self.fuzzer = SolutionFuzzer(
            iterations=fuzz_iterations,
            timeout=fuzz_timeout,
            max_concurrent=max_concurrent_fuzz,
        )

        self.crash_analyzer = CrashAnalyzer()
        self.crash_reporter = CrashReporter()

    async def attack_solution(
        self,
        solution: Callable,
        problem: Dict[str, Any],
        context: Dict[str, Any] = None
    ) -> RedTeamAttackResult:
        """
        Perform comprehensive Red Team attack on a solution.

        Args:
            solution: Solution function to attack
            problem: Original problem statement
            context: Additional context

        Returns:
            RedTeamAttackResult with all findings
        """
        import time
        start_time = time.time()

        attack_id = f"attack_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}"

        logger.info(f"Starting Red Team attack: {attack_id}")
        logger.info(f"Problem: {problem.get('statement', 'Unknown')}")
        logger.info(f"Fuzzing enabled: {self.fuzzing_enabled}")

        result = RedTeamAttackResult(
            attack_id=attack_id,
            target_solution=solution,
        )

        # Step 1: Logical attacks
        logger.info("Running logical attacks...")
        logical_results = await self._run_logical_attacks(solution, problem, context)
        result.logical_attacks = logical_results

        # Step 2: Automated fuzzing
        if self.fuzzing_enabled:
            logger.info(f"Running fuzzing ({self.fuzz_iterations} iterations)...")
            fuzz_result = await self._run_fuzzing(solution, problem)
            result.fuzz_results = fuzz_result

            # Analyze crashes
            if fuzz_result.crashes_found > 0:
                logger.info(f"Analyzing {fuzz_result.crashes_found} crashes...")
                crash_report = self.crash_analyzer.analyze(fuzz_result)
                result.crash_report = crash_report

                # Count vulnerabilities
                result.vulnerabilities_found = fuzz_result.unique_crashes
                result.critical_vulnerabilities = len(
                    crash_report.vulnerabilities_by_severity.get(VulnerabilitySeverity.CRITICAL, [])
                ) + len(
                    crash_report.vulnerabilities_by_severity.get(VulnerabilitySeverity.HIGH, [])
                )

        # Step 3: Calculate overall pass/fail
        result.passed = self._evaluate_attack_result(result)

        # Step 4: Calculate confidence score
        result.confidence = self._calculate_confidence(result)

        result.execution_time = time.time() - start_time

        logger.info(
            f"Red Team attack complete: "
            f"{'PASSED' if result.passed else 'FAILED'} "
            f"({result.vulnerabilities_found} vulnerabilities, "
            f"{result.confidence:.1%} confidence)"
        )

        return result

    async def _run_logical_attacks(
        self,
        solution: Callable,
        problem: Dict[str, Any],
        context: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        """Run logical attacks on the solution"""
        results = []

        for attacker in self.logical_attackers:
            try:
                attack_result = await attacker(solution, problem, context)
                results.append(attack_result)
            except Exception as e:
                logger.warning(f"Logical attack failed: {e}")
                results.append({
                    'attacker': attacker.__name__,
                    'success': False,
                    'error': str(e),
                })

        return results

    async def _run_fuzzing(
        self,
        solution: Callable,
        problem: Dict[str, Any]
    ) -> FuzzResult:
        """Run automated fuzzing on the solution"""
        # Determine input type from problem
        input_type = self._infer_input_type(problem)

        # Get constraints from problem
        constraints = problem.get('constraints', {})

        # Run fuzzing
        fuzz_result = await self.fuzzer.fuzz(
            solution=solution,
            input_type=input_type,
            constraints=constraints
        )

        return fuzz_result

    def _infer_input_type(self, problem: Dict[str, Any]) -> str:
        """Infer the expected input type from the problem"""
        # Check problem metadata
        if 'input_type' in problem:
            return problem['input_type']

        # Check statement for hints
        statement = problem.get('statement', '').lower()

        if 'string' in statement or 'text' in statement:
            return 'string'
        elif 'number' in statement or 'integer' in statement:
            return 'number'
        elif 'array' in statement or 'list' in statement:
            return 'array'
        elif 'object' in statement or 'json' in statement:
            return 'object'

        # Default to auto (random)
        return 'auto'

    def _evaluate_attack_result(self, result: RedTeamAttackResult) -> bool:
        """
        Evaluate if the solution passes the Red Team attack.

        A solution passes if:
        - No critical vulnerabilities found
        - Logical attacks didn't find major issues
        - Fuzzing found at most minor issues
        """
        # Check for critical vulnerabilities
        if result.critical_vulnerabilities > 0:
            return False

        # Check logical attacks
        for attack in result.logical_attacks:
            if attack.get('success', False) and attack.get('severity', 'low') == 'critical':
                return False

        # Check fuzzing results
        if result.fuzz_results:
            # Too many crashes indicates poor robustness
            crash_rate = result.fuzz_results.crashes_found / result.fuzz_results.iterations
            if crash_rate > 0.1:  # More than 10% crash rate
                return False

        return True

    def _calculate_confidence(self, result: RedTeamAttackResult) -> float:
        """Calculate confidence in the attack result"""
        confidence = 0.5  # Base confidence

        # Increase confidence if fuzzing found issues
        if result.vulnerabilities_found > 0:
            confidence += 0.2

        # Increase confidence if logical attacks found issues
        successful_attacks = sum(1 for a in result.logical_attacks if a.get('success', False))
        if successful_attacks > 0:
            confidence += 0.1 * min(successful_attacks, 3)

        # Increase confidence with more fuzzing iterations
        if result.fuzz_results:
            iteration_factor = min(result.fuzz_results.iterations / 1000, 1.0)
            confidence += 0.2 * iteration_factor

        return min(confidence, 1.0)


class FuzzingConfiguration:
    """Configuration for fuzzing integration"""

    def __init__(
        self,
        enabled: bool = True,
        iterations: int = 1000,
        timeout: float = 5.0,
        max_concurrent: int = 4,
        corpus_size: int = 100,
        auto_enable_on_critical_functions: bool = True,
    ):
        self.enabled = enabled
        self.iterations = iterations
        self.timeout = timeout
        self.max_concurrent = max_concurrent
        self.corpus_size = corpus_size
        self.auto_enable_on_critical_functions = auto_enable_on_critical_functions

    def validate(self) -> List[str]:
        """Validate configuration and return list of errors"""
        errors = []

        if self.iterations < 1:
            errors.append("iterations must be at least 1")
        if self.iterations > 100000:
            errors.append("iterations should not exceed 100000")

        if self.timeout < 0.1:
            errors.append("timeout must be at least 0.1 seconds")
        if self.timeout > 300:
            errors.append("timeout should not exceed 300 seconds")

        if self.max_concurrent < 1:
            errors.append("max_concurrent must be at least 1")
        if self.max_concurrent > 100:
            errors.append("max_concurrent should not exceed 100")

        if self.corpus_size < 0:
            errors.append("corpus_size cannot be negative")
        if self.corpus_size > 10000:
            errors.append("corpus_size should not exceed 10000")

        return errors


def create_red_team_with_fuzzing(
    config: FuzzingConfiguration = None,
    logical_attackers: List[Callable] = None
) -> RedTeamWithFuzzing:
    """
    Factory function to create Red Team with fuzzing.

    Args:
        config: Fuzzing configuration
        logical_attackers: List of logical attack functions

    Returns:
        RedTeamWithFuzzing instance
    """
    config = config or FuzzingConfiguration()

    # Validate configuration
    errors = config.validate()
    if errors:
        raise ValueError(f"Invalid fuzzing configuration: {', '.join(errors)}")

    return RedTeamWithFuzzing(
        fuzzing_enabled=config.enabled,
        fuzz_iterations=config.iterations,
        fuzz_timeout=config.timeout,
        max_concurrent_fuzz=config.max_concurrent,
        logical_attackers=logical_attackers or [],
    )


# Example logical attackers
async def example_logical_attack_input_validation(
    solution: Callable,
    problem: Dict[str, Any],
    context: Dict[str, Any]
) -> Dict[str, Any]:
    """Example: Test input validation"""
    test_cases = [
        None,
        '',
        0,
        -1,
        {'malicious': 'input'},
    ]

    passed = 0
    failed = 0

    for test_input in test_cases:
        try:
            result = solution(test_input)
            passed += 1
        except Exception:
            failed += 1

    return {
        'attacker': 'input_validation',
        'success': failed > 0,
        'severity': 'medium' if failed > 0 else 'none',
        'details': f'{failed}/{len(test_cases)} test cases failed',
    }


async def example_logical_attack_boundary_conditions(
    solution: Callable,
    problem: Dict[str, Any],
    context: Dict[str, Any]
) -> Dict[str, Any]:
    """Example: Test boundary conditions"""
    test_cases = [
        -2**63,  # Min int64
        2**63 - 1,  # Max int64
        -1.0,
        0.0,
        1.0,
        float('inf'),
        float('-inf'),
        float('nan'),
    ]

    passed = 0
    failed = 0

    for test_input in test_cases:
        try:
            result = solution(test_input)
            passed += 1
        except Exception:
            failed += 1

    return {
        'attacker': 'boundary_conditions',
        'success': failed > 0,
        'severity': 'high' if failed > 2 else 'low',
        'details': f'{failed}/{len(test_cases)} boundary cases failed',
    }


# Example usage
async def demo_red_team_with_fuzzing():
    """Demonstration of Red Team with fuzzing"""

    # Example solution with a bug
    def buggy_solution(input_data):
        # Bug: doesn't handle None
        if len(input_data) > 5:
            return input_data[:5]
        return input_data

    # Create Red Team with fuzzing
    red_team = create_red_team_with_fuzzing(
        config=FuzzingConfiguration(
            enabled=True,
            iterations=100,
            timeout=1.0,
            max_concurrent=2,
        ),
        logical_attackers=[
            example_logical_attack_input_validation,
            example_logical_attack_boundary_conditions,
        ]
    )

    # Run attack
    problem = {
        'statement': 'Process input string',
        'input_type': 'string',
    }

    result = await red_team.attack_solution(
        solution=buggy_solution,
        problem=problem
    )

    print(f"\n{'='*60}")
    print(f"Red Team Attack Results")
    print(f"{'='*60}")
    print(f"Attack ID: {result.attack_id}")
    print(f"Passed: {result.passed}")
    print(f"Confidence: {result.confidence:.1%}")
    print(f"\nLogical Attacks: {len(result.logical_attacks)}")
    for attack in result.logical_attacks:
        print(f"  - {attack['attacker']}: {attack['success']} ({attack['severity']})")

    if result.fuzz_results:
        print(f"\nFuzzing Results:")
        print(f"  - Iterations: {result.fuzz_results.iterations}")
        print(f"  - Crashes: {result.fuzz_results.crashes_found}")
        print(f"  - Unique: {result.fuzz_results.unique_crashes}")

    if result.crash_report:
        print(f"\nTop Crash Types:")
        for crash_type, count in list(result.crash_report.top_crash_types.items())[:3]:
            print(f"  - {crash_type}: {count}")

    print(f"\n{'='*60}")


if __name__ == '__main__':
    import asyncio
    asyncio.run(demo_red_team_with_fuzzing())
