/**
 * Generates `src/nvidia-nim-models.ts` from NVIDIA's public NIM model catalog.
 *
 * NVIDIA exposes an OpenAI-compatible models endpoint (no auth required):
 *   GET https://integrate.api.nvidia.com/v1/models
 *
 * This filters to chat / instruction-tuned models and emits a static snapshot
 * used by `AvailableModels` in `src/ai-models.ts`. Run:
 *   cd packages/bubble-shared-schemas && bun run generate:nim-models
 *
 * If the endpoint is unreachable, the existing generated file is preserved.
 */
import { writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '..', 'src', 'nvidia-nim-models.ts');

const NIM_MODELS_URL = 'https://integrate.api.nvidia.com/v1/models';
const HEADER = `// AUTO-GENERATED by scripts/generate-nim-models.ts — DO NOT EDIT MANUALLY.
// Regenerate with: cd packages/bubble-shared-schemas && bun run generate:nim-models
// Source: ${NIM_MODELS_URL}

`;

async function fetchModelIds(): Promise<string[]> {
  const res = await fetch(NIM_MODELS_URL, { headers: { Accept: 'application/json' } });
  if (!res.ok) {
    throw new Error(`NVIDIA NIM models endpoint returned ${res.status} ${res.statusText}`);
  }
  const json = (await res.json()) as {
    data?: { id?: string; owned_by?: string }[];
  };
  const ids = (json.data ?? [])
    .map((m) => m.id)
    .filter((id): id is string => Boolean(id));

  // Keep chat / instruction-tuned models; drop embeddings, rerankers, image/vision,
  // and other non-generative ids.
  const chatIds = ids.filter(
    (id) =>
      /instruct|chat|nemotron|reasoning/i.test(id) &&
      !/embed|rerank|vision|vlm|image|tts|asr|stt|audio/i.test(id)
  );

  // Prefer well-known producers; append the rest.
  return [...new Set(chatIds)].sort((a, b) => a.localeCompare(b));
}

function buildFile(models: string[]): string {
  const body = models
    .map((id) => `  '${id}',`)
    .join('\n');
  return `${HEADER}export const NVIDIA_NIM_MODELS = [
${body}
] as const;
`;
}

async function main() {
  try {
    const models = await fetchModelIds();
    if (models.length === 0) {
      console.warn('[generate-nim-models] API returned 0 chat/instruct models; keeping existing file.');
      return;
    }
    const content = buildFile(models);
    writeFileSync(OUT_PATH, content, 'utf8');
    console.log(`[generate-nim-models] Wrote ${models.length} models to ${OUT_PATH}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[generate-nim-models] Failed to fetch NIM models (${msg}).`);
    if (existsSync(OUT_PATH)) {
      console.warn('[generate-nim-models] Keeping existing generated file.');
    } else {
      console.error('[generate-nim-models] No existing file present; refusing to emit an empty list.');
      process.exit(1);
    }
  }
}

main();