"""
OpenEvolve gRPC Server

High-performance gRPC server that wraps the existing bubblelabs_nodes Python implementations.
Provides streaming support, health checks, and efficient binary serialization.
"""

import asyncio
import logging
import os
import signal
import sys
import time
import traceback
from concurrent import futures
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from typing import AsyncIterator, Callable, Dict, List, Optional, Type

import grpc
from google.protobuf import json_format, struct_pb2, timestamp_pb2
from google.protobuf.any_pb2 import Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Import generated protobuf modules
# These will be generated by the protobuf compiler
# For now, we'll create the structure


@dataclass
class ServerConfig:
    """Configuration for the gRPC server"""
    host: str = "0.0.0.0"
    port: int = 50051
    max_workers: int = 10
    max_concurrent_rpcs: int = 100
    compression: grpc.Compression = grpc.Compression.Gzip
    enable_reflection: bool = True
    keepalive_time_ms: int = 10000
    keepalive_timeout_ms: int = 5000
    
    # Feature flags
    enable_health_check: bool = True
    enable_metrics: bool = True
    enable_streaming: bool = True
    enable_cancellation: bool = True


@dataclass
class ExecutionContext:
    """Context for node execution"""
    execution_id: str
    node_type: str
    start_time: float = field(default_factory=time.time)
    cancelled: bool = False
    progress_callbacks: List[Callable] = field(default_factory=list)
    
    def is_cancelled(self) -> bool:
        return self.cancelled
    
    def cancel(self):
        self.cancelled = True
        for callback in self.progress_callbacks:
            try:
                callback("cancelled")
            except Exception:
                pass


class ExecutionManager:
    """Manages active executions for cancellation and monitoring"""
    
    def __init__(self):
        self._executions: Dict[str, ExecutionContext] = {}
        self._lock = asyncio.Lock()
    
    async def create_execution(self, execution_id: str, node_type: str) -> ExecutionContext:
        async with self._lock:
            ctx = ExecutionContext(execution_id=execution_id, node_type=node_type)
            self._executions[execution_id] = ctx
            return ctx
    
    async def get_execution(self, execution_id: str) -> Optional[ExecutionContext]:
        async with self._lock:
            return self._executions.get(execution_id)
    
    async def cancel_execution(self, execution_id: str) -> bool:
        async with self._lock:
            ctx = self._executions.get(execution_id)
            if ctx:
                ctx.cancel()
                return True
            return False
    
    async def complete_execution(self, execution_id: str):
        async with self._lock:
            if execution_id in self._executions:
                del self._executions[execution_id]
    
    async def list_executions(self) -> List[ExecutionContext]:
        async with self._lock:
            return list(self._executions.values())


class NodeAdapter:
    """
    Adapter that wraps existing bubblelabs_nodes to work with gRPC.
    This bridges the old Python API with the new gRPC interface.
    """
    
    def __init__(self):
        self._node_registry: Dict[str, Type] = {}
        self._import_nodes()
    
    def _import_nodes(self):
        """Import available nodes from bubblelabs_nodes"""
        try:
            # Import the bubblelabs_nodes module
            import sys
            sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', 'bubblelabs_nodes'))
            
            # Try to import the node registry
            try:
                from bubblelabs_nodes import NodeRegistry
                self._node_registry = NodeRegistry.list_nodes()
                logger.info(f"Loaded {len(self._node_registry)} nodes from bubblelabs_nodes")
            except ImportError as e:
                logger.warning(f"Could not import NodeRegistry: {e}")
                self._node_registry = {}
                
        except Exception as e:
            logger.error(f"Error importing nodes: {e}")
            self._node_registry = {}
    
    def get_node(self, node_type: str, config: Optional[Dict] = None):
        """Get a node instance by type"""
        node_class = self._node_registry.get(node_type)
        if not node_class:
            raise ValueError(f"Unknown node type: {node_type}")
        return node_class(config or {})
    
    def list_nodes(self) -> Dict[str, Type]:
        """List all available node types"""
        return self._node_registry.copy()
    
    async def execute_node(
        self,
        node_type: str,
        inputs: Dict,
        config: Optional[Dict] = None,
        ctx: Optional[ExecutionContext] = None
    ) -> Dict:
        """
        Execute a node with the given inputs.
        
        This method wraps the existing bubblelabs_nodes API and provides
        integration with the new gRPC execution context.
        """
        node = self.get_node(node_type, config)
        
        # Create a context wrapper that bridges to bubblelabs_nodes WorkflowState
        class WorkflowStateWrapper:
            def __init__(self, exec_ctx: Optional[ExecutionContext]):
                self.exec_ctx = exec_ctx
                self.artifacts = {}
                self.errors = []
                
            def generate_execution_id(self) -> str:
                return self.exec_ctx.execution_id if self.exec_ctx else str(time.time())
            
            def add_artifact(self, name: str, data: Dict):
                self.artifacts[name] = data
            
            def add_error(self, error: Dict):
                self.errors.append(error)
            
            def update_progress(self, progress: int, message: str = ""):
                if self.exec_ctx:
                    for callback in self.exec_ctx.progress_callbacks:
                        callback({"percent": progress, "message": message})
        
        workflow_state = WorkflowStateWrapper(ctx)
        
        # Check for cancellation before execution
        if ctx and ctx.is_cancelled():
            raise asyncio.CancelledError("Execution was cancelled")
        
        # Execute the node
        try:
            # Try the safe execution method first
            if hasattr(node, 'execute_safe'):
                result = node.execute_safe(inputs, workflow_state)
            elif hasattr(node, 'execute'):
                result = node.execute(inputs, workflow_state)
            else:
                raise RuntimeError(f"Node {node_type} has no execute method")
            
            # Check for cancellation after execution
            if ctx and ctx.is_cancelled():
                raise asyncio.CancelledError("Execution was cancelled")
            
            return {
                "result": result,
                "artifacts": workflow_state.artifacts,
                "errors": workflow_state.errors
            }
            
        except Exception as e:
            logger.error(f"Node execution failed: {e}")
            raise


class HealthServicer:
    """Health checking service for gRPC"""
    
    def __init__(self, node_adapter: NodeAdapter):
        self.node_adapter = node_adapter
        self._status = "SERVING"
    
    def Check(self, request, context):
        """Standard gRPC health check"""
        from grpc_health.v1 import health_pb2
        return health_pb2.HealthCheckResponse(status=self._status)
    
    def Watch(self, request, context):
        """Streaming health check"""
        from grpc_health.v1 import health_pb2
        while True:
            yield health_pb2.HealthCheckResponse(status=self._status)
            time.sleep(5)
    
    def set_status(self, status: str):
        self._status = status


class OpenEvolveServicer:
    """
    Main gRPC service implementation.
    Implements the NodeRegistry service defined in the proto files.
    """
    
    def __init__(self, config: ServerConfig):
        self.config = config
        self.node_adapter = NodeAdapter()
        self.execution_manager = ExecutionManager()
        self.version = "2.0.0-grpc"
        self.start_time = time.time()
    
    def _create_metadata(self, request_id: str) -> Dict:
        """Create response metadata"""
        return {
            "request_id": request_id,
            "timestamp": timestamp_pb2.Timestamp().GetCurrentTime(),
            "server_version": self.version,
            "processing_time_ms": 0  # Will be updated
        }
    
    def _struct_to_dict(self, struct: struct_pb2.Struct) -> Dict:
        """Convert protobuf Struct to Python dict"""
        return json_format.MessageToDict(struct)
    
    def _dict_to_struct(self, data: Dict) -> struct_pb2.Struct:
        """Convert Python dict to protobuf Struct"""
        struct = struct_pb2.Struct()
        json_format.ParseDict(data, struct)
        return struct
    
    def _run_async(self, coro):
        """
        Run an async coroutine from a synchronous context.
        
        This handles the case where we may or may not already be in an event loop.
        """
        try:
            # Try to get the current event loop
            loop = asyncio.get_running_loop()
            # If we're already in an event loop, we can't use asyncio.run()
            # Instead, create a new thread to run the coroutine
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor() as executor:
                future = executor.submit(asyncio.run, coro)
                return future.result()
        except RuntimeError:
            # No event loop running, we can use asyncio.run()
            return asyncio.run(coro)
    
    # =========================================================================
    # Node Registry Service Methods
    # =========================================================================
    
    def ListNodes(self, request, context):
        """List all available nodes"""
        start_time = time.time()
        
        try:
            nodes = self.node_adapter.list_nodes()
            
            # Build node info list
            node_infos = []
            for node_type, node_class in nodes.items():
                try:
                    # Create instance to get metadata
                    node = node_class({})
                    
                    node_info = {
                        "node_id": node_type,
                        "node_type": node_type,
                        "display_name": getattr(node, 'DISPLAY_NAME', node_type),
                        "description": getattr(node, 'DESCRIPTION', ''),
                        "icon": getattr(node, 'ICON', 'default'),
                        "category": getattr(node, 'CATEGORY', 'general'),
                        "version": getattr(node, 'VERSION', '1.0.0'),
                    }
                    
                    # Get parameter schema if available
                    if hasattr(node, 'get_parameter_schema'):
                        try:
                            schema = node.get_parameter_schema()
                            node_info['parameter_schema'] = schema
                        except Exception as e:
                            logger.warning(f"Could not get schema for {node_type}: {e}")
                    
                    node_infos.append(node_info)
                    
                except Exception as e:
                    logger.warning(f"Error getting info for {node_type}: {e}")
            
            processing_time = int((time.time() - start_time) * 1000)
            
            return {
                "metadata": {
                    **self._create_metadata(request.metadata.request_id),
                    "processing_time_ms": processing_time
                },
                "nodes": node_infos,
                "pagination": {
                    "total_count": len(node_infos),
                    "has_next": False
                }
            }
            
        except Exception as e:
            logger.error(f"ListNodes failed: {e}")
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            raise
    
    def GetNodeSchema(self, request, context):
        """Get schema for a specific node"""
        try:
            node_type = request.node_type
            node = self.node_adapter.get_node(node_type)
            
            schema = {}
            if hasattr(node, 'get_parameter_schema'):
                schema = node.get_parameter_schema()
            
            return {
                "metadata": self._create_metadata(request.metadata.request_id),
                "node_info": {
                    "node_id": node_type,
                    "node_type": node_type,
                    "display_name": getattr(node, 'DISPLAY_NAME', node_type),
                    "description": getattr(node, 'DESCRIPTION', ''),
                    "parameter_schema": schema
                }
            }
            
        except ValueError as e:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details(str(e))
            raise
        except Exception as e:
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            raise
    
    def ExecuteNode(self, request, context):
        """Execute a node synchronously"""
        start_time = time.time()
        execution_id = request.metadata.request_id
        
        try:
            # Create execution context (sync wrapper for async method)
            exec_ctx = self._run_async(
                self.execution_manager.create_execution(
                    execution_id, 
                    request.node_type
                )
            )
            
            # Convert inputs
            inputs = self._struct_to_dict(request.inputs) if request.inputs else {}
            config = self._struct_to_dict(request.config) if request.config else {}
            
            # Execute (sync wrapper for async method)
            result = self._run_async(
                self.node_adapter.execute_node(
                    request.node_type,
                    inputs,
                    config,
                    exec_ctx
                )
            )
            
            # Complete execution (sync wrapper for async method)
            self._run_async(self.execution_manager.complete_execution(execution_id))
            
            processing_time = int((time.time() - start_time) * 1000)
            
            return {
                "metadata": {
                    **self._create_metadata(request.metadata.request_id),
                    "processing_time_ms": processing_time
                },
                "execution_id": execution_id,
                "state": "EXECUTION_STATE_COMPLETED",
                "result": self._dict_to_struct(result.get("result", {})),
            }
            
        except asyncio.CancelledError:
            self._run_async(self.execution_manager.complete_execution(execution_id))
            context.set_code(grpc.StatusCode.CANCELLED)
            context.set_details("Execution was cancelled")
            raise
        except Exception as e:
            self._run_async(self.execution_manager.complete_execution(execution_id))
            logger.error(f"ExecuteNode failed: {e}")
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            raise
    
    def ExecuteNodeStreaming(self, request, context):
        """Execute a node with streaming progress updates"""
        execution_id = request.metadata.request_id
        
        async def generate_updates():
            # Create execution context
            exec_ctx = await self.execution_manager.create_execution(
                execution_id, 
                request.node_type
            )
            
            # Progress queue
            progress_queue = asyncio.Queue()
            
            def on_progress(data):
                asyncio.create_task(progress_queue.put(data))
            
            exec_ctx.progress_callbacks.append(on_progress)
            
            try:
                # Send initial progress
                yield {
                    "execution_id": execution_id,
                    "state": "EXECUTION_STATE_RUNNING",
                    "progress": {"percent": 0, "message": "Starting..."}
                }
                
                # Convert inputs
                inputs = self._struct_to_dict(request.inputs) if request.inputs else {}
                config = self._struct_to_dict(request.config) if request.config else {}
                
                # Execute in background
                import threading
                result_holder = [None]
                error_holder = [None]
                
                def execute():
                    try:
                        result = self._run_async(
                            self.node_adapter.execute_node(
                                request.node_type,
                                inputs,
                                config,
                                exec_ctx
                            )
                        )
                        result_holder[0] = result
                    except Exception as e:
                        error_holder[0] = e
                
                thread = threading.Thread(target=execute)
                thread.start()
                
                # Stream progress while executing
                while thread.is_alive():
                    try:
                        progress_data = await asyncio.wait_for(
                            progress_queue.get(), 
                            timeout=0.1
                        )
                        yield {
                            "execution_id": execution_id,
                            "state": "EXECUTION_STATE_RUNNING",
                            "progress": progress_data
                        }
                    except asyncio.TimeoutError:
                        pass
                    
                    if context.is_active() and not context.add_callback(lambda: None):
                        # Client disconnected
                        await self.execution_manager.cancel_execution(execution_id)
                        break
                
                thread.join()
                
                # Send final result
                if error_holder[0]:
                    raise error_holder[0]
                
                yield {
                    "execution_id": execution_id,
                    "state": "EXECUTION_STATE_COMPLETED",
                    "progress": {"percent": 100, "message": "Complete"},
                    "partial_result": self._dict_to_struct(result_holder[0].get("result", {}))
                }
                
            except asyncio.CancelledError:
                yield {
                    "execution_id": execution_id,
                    "state": "EXECUTION_STATE_CANCELLED",
                    "progress": {"percent": 0, "message": "Cancelled"}
                }
            except Exception as e:
                yield {
                    "execution_id": execution_id,
                    "state": "EXECUTION_STATE_FAILED",
                    "error": {
                        "error_code": "EXECUTION_ERROR",
                        "message": str(e),
                        "retryable": False
                    }
                }
            finally:
                await self.execution_manager.complete_execution(execution_id)
        
        try:
            # Run the async generator
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            
            gen = generate_updates()
            while True:
                try:
                    update = loop.run_until_complete(gen.asend(None))
                    yield update
                except StopAsyncIteration:
                    break
                    
        except Exception as e:
            logger.error(f"Streaming execution failed: {e}")
            raise
    
    def GetExecutionStatus(self, request, context):
        """Get status of an execution"""
        execution_id = request.execution_id
        
        exec_ctx = self._run_async(self.execution_manager.get_execution(execution_id))
        
        if not exec_ctx:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details(f"Execution {execution_id} not found")
            raise
        
        elapsed = int(time.time() - exec_ctx.start_time)
        
        return {
            "metadata": self._create_metadata(request.metadata.request_id),
            "execution_id": execution_id,
            "state": "EXECUTION_STATE_CANCELLED" if exec_ctx.is_cancelled() else "EXECUTION_STATE_RUNNING",
            "elapsed_seconds": elapsed
        }
    
    def CancelExecution(self, request, context):
        """Cancel a running execution"""
        execution_id = request.execution_id
        
        success = self._run_async(self.execution_manager.cancel_execution(execution_id))
        
        return {
            "metadata": self._create_metadata(request.metadata.request_id),
            "success": success,
            "message": "Cancelled" if success else "Execution not found",
            "final_state": "EXECUTION_STATE_CANCELLED" if success else "EXECUTION_STATE_UNKNOWN"
        }


class OpenEvolveGRPCServer:
    """
    Main gRPC server class.
    Manages the server lifecycle and all services.
    """
    
    def __init__(self, config: Optional[ServerConfig] = None):
        self.config = config or ServerConfig()
        self.server: Optional[grpc.Server] = None
        self.servicer = OpenEvolveServicer(self.config)
        self._shutdown_event = asyncio.Event()
    
    def _create_server(self) -> grpc.Server:
        """Create the gRPC server with all configurations"""
        
        # Server options
        options = [
            ('grpc.max_send_message_length', 50 * 1024 * 1024),  # 50MB
            ('grpc.max_receive_message_length', 50 * 1024 * 1024),  # 50MB
            ('grpc.keepalive_time_ms', self.config.keepalive_time_ms),
            ('grpc.keepalive_timeout_ms', self.config.keepalive_timeout_ms),
            ('grpc.keepalive_permit_without_calls', True),
            ('grpc.http2.max_pings_without_data', 0),
            ('grpc.http2.min_time_between_pings_ms', 10000),
            ('grpc.http2.min_ping_interval_without_data_ms', 5000),
        ]
        
        # Create server
        server = grpc.server(
            thread_pool=futures.ThreadPoolExecutor(max_workers=self.config.max_workers),
            options=options,
            compression=self.config.compression,
            maximum_concurrent_rpcs=self.config.max_concurrent_rpcs
        )
        
        return server
    
    def start(self):
        """Start the gRPC server"""
        logger.info(f"Starting OpenEvolve gRPC Server v{self.servicer.version}")
        
        self.server = self._create_server()
        
        # Add servicer (this would add the generated servicer)
        # For now, we'll use the generic servicer
        # add_NodeRegistryServicer_to_server(self.servicer, self.server)
        
        # Add health check service
        if self.config.enable_health_check:
            try:
                from grpc_health.v1 import health_pb2_grpc
                from grpc_health.v1 import health
                
                health_servicer = HealthServicer(self.servicer.node_adapter)
                health_pb2_grpc.add_HealthServicer_to_server(health_servicer, self.server)
                logger.info("Health check service enabled")
            except ImportError:
                logger.warning("grpc_health.v1 not available, skipping health service")
        
        # Add reflection service
        if self.config.enable_reflection:
            try:
                from grpc_reflection.v1alpha import reflection
                # This would include the actual service names
                service_names = [
                    'openevolve.grpc.NodeRegistry',
                    'grpc.health.v1.Health',
                    reflection.SERVICE_NAME,
                ]
                reflection.enable_server_reflection(service_names, self.server)
                logger.info("Reflection service enabled")
            except ImportError:
                logger.warning("grpc_reflection not available, skipping reflection")
        
        # Bind to port
        address = f"{self.config.host}:{self.config.port}"
        self.server.add_insecure_port(address)
        
        # Start server
        self.server.start()
        logger.info(f"gRPC Server started on {address}")
        
        # Setup signal handlers
        self._setup_signal_handlers()
        
        # Keep running
        try:
            self._wait_for_shutdown()
        except KeyboardInterrupt:
            logger.info("Received keyboard interrupt")
        finally:
            self.stop()
    
    def _setup_signal_handlers(self):
        """Setup handlers for graceful shutdown"""
        
        def signal_handler(sig, frame):
            logger.info(f"Received signal {sig}")
            self._shutdown_event.set()
        
        signal.signal(signal.SIGINT, signal_handler)
        signal.signal(signal.SIGTERM, signal_handler)
        
        if hasattr(signal, 'SIGQUIT'):
            signal.signal(signal.SIGQUIT, signal_handler)
    
    def _wait_for_shutdown(self):
        """Wait for shutdown signal"""
        # In a real implementation, this would use asyncio
        # For now, just sleep and check
        while not self._shutdown_event.is_set():
            time.sleep(0.1)
    
    def stop(self, grace_period: float = 5.0):
        """Stop the gRPC server gracefully"""
        logger.info("Stopping gRPC server...")
        
        if self.server:
            self.server.stop(grace_period)
            logger.info("gRPC server stopped")


def main():
    """Main entry point"""
    
    # Load configuration from environment
    config = ServerConfig(
        host=os.getenv('GRPC_HOST', '0.0.0.0'),
        port=int(os.getenv('GRPC_PORT', '50051')),
        max_workers=int(os.getenv('GRPC_MAX_WORKERS', '10')),
        enable_reflection=os.getenv('GRPC_ENABLE_REFLECTION', 'true').lower() == 'true',
        enable_health_check=os.getenv('GRPC_ENABLE_HEALTH', 'true').lower() == 'true',
    )
    
    server = OpenEvolveGRPCServer(config)
    server.start()


if __name__ == '__main__':
    main()
