#!/usr/bin/env python3
"""
generate_lean.py

Generate Lean 4 code from Python Constraint objects.

Usage:
    constraint = Constraint(...)
    lean_code = generate_lean_constraint(constraint)

Author: Agent O1 (Lean 4 Formalization Specialist)
"""

import re
from pathlib import Path
from typing import Optional
from dataclasses import dataclass


@dataclass
class LeanConstraint:
    """Lean 4 constraint definition"""
    id: str
    type: str  # 'hard', 'soft', 'preference'
    description: str
    formalization: str
    dependencies: list
    source: str

    def to_lean(self) -> str:
        """Convert to Lean 4 code"""
        deps_str = str(self.dependencies).replace("'", '"')

        return f"""def {self._sanitize_id(self.id)} : Constraint := {{
  id := "{self.id}"
  type := ConstraintType.{self.type}
  description := "{self.description}"
  formalization := True  -- {self.formalization}
  dependencies := {deps_str}
  source := "{self.source}"
}}"""

    def _sanitize_id(self, id_str: str) -> str:
        """Sanitize constraint ID for Lean 4"""
        # Remove special characters, replace with underscores
        return re.sub(r'[^a-zA-Z0-9_]', '_', id_str)


def generate_lean_constraint(
    id: str,
    type: str,
    description: str,
    formalization: str,
    dependencies: Optional[list] = None,
    source: str = "python"
) -> str:
    """
    Generate Lean 4 constraint definition.

    Args:
        id: Constraint ID
        type: Constraint type ('hard', 'soft', 'preference')
        description: Human-readable description
        formalization: Lean 4 proposition (simplified as string)
        dependencies: List of constraint IDs this depends on
        source: Source of constraint

    Returns:
        Lean 4 code defining the constraint

    Example:
        >>> lean_code = generate_lean_constraint(
        ...     id="temp_max",
        ...     type="hard",
        ...     description="Temperature must be less than 1000°C",
        ...     formalization="forall (T : Real), T < 1000"
        ... )
        >>> print(lean_code)
        def temp_max : Constraint := ...
    """
    constraint = LeanConstraint(
        id=id,
        type=type,
        description=description,
        formalization=formalization,
        dependencies=dependencies or [],
        source=source
    )

    return constraint.to_lean()


def generate_contradiction_theorem(c1_id: str, c2_id: str) -> str:
    """
    Generate Lean 4 theorem proving two constraints contradict.

    Args:
        c1_id: First constraint ID
        c2_id: Second constraint ID

    Returns:
        Lean 4 theorem code

    Example:
        >>> theorem = generate_contradiction_theorem("c1", "c2")
        >>> print(theorem)
        theorem c1_c2_contradict : contradict c1 c2 := by ...
    """
    lean_id1 = re.sub(r'[^a-zA-Z0-9_]', '_', c1_id)
    lean_id2 = re.sub(r'[^a-zA-Z0-9_]', '_', c2_id)

    return f"""theorem {lean_id1}_{lean_id2}_contradict :
    contradict {lean_id1} {lean_id2} := by
  unfold contradict
  -- Show ¬({lean_id1}.formalization ∧ {lean_id2}.formalization)
  sorry  -- Proof requires specific constraints"""


def generate_equivalence_theorem(set1_name: str, set2_name: str) -> str:
    """
    Generate Lean 4 theorem proving two constraint sets are equivalent.

    Args:
        set1_name: Name of first constraint set
        set2_name: Name of second constraint set

    Returns:
        Lean 4 theorem code
    """
    return f"""theorem {set1_name}_{set2_name}_equivalent :
    equivalentSets {set1_name} {set2_name} := by
  apply equivalence_template
  . intro P h1
    -- Show all constraints in {set2_name} satisfied
    sorry
  . intro P h2
    -- Show all constraints in {set1_name} satisfied
    sorry"""


def generate_acyclicity_theorem(graph_name: str) -> str:
    """
    Generate Lean 4 theorem proving a graph is acyclic.

    Args:
        graph_name: Name of dependency graph

    Returns:
        Lean 4 theorem code
    """
    return f"""theorem {graph_name}_acyclic :
    ¬{graph_name}.hasCycle := by
  apply acyclicity_template
  intro node path
  -- Show no path from node back to itself
  sorry"""


def export_to_lean_file(
    constraints: list,
    filepath: Path,
    module_name: str = "Generated"
) -> None:
    """
    Export constraints to a Lean 4 file.

    Args:
        constraints: List of LeanConstraint objects
        filepath: Output Lean 4 file path
        module_name: Name for the Lean 4 module

    Example:
        >>> constraints = [
        ...     LeanConstraint("c1", "hard", "Constraint 1", "True", []),
        ...     LeanConstraint("c2", "soft", "Constraint 2", "True", ["c1"])
        ... ]
        >>> export_to_lean_file(constraints, Path("output.lean"))
    """
    lines = [
        f"/-!",
        f"Auto-generated Lean 4 constraints",
        f"",
        f"Module: {module_name}",
        f"Generated by: Agent O1 (Lean 4 Formalization Specialist)",
        f"-/",
        f"",
        f"import RESE.Basic",
        f"import RESE.Constraint",
        f"import RESE.Templates",
        f"",
        f"namespace {module_name}",
        f""
    ]

    # Add constraint definitions
    for constraint in constraints:
        lines.append(constraint.to_lean())
        lines.append("")

    # End namespace
    lines.extend([
        f"",
        f"end {module_name}"
    ])

    filepath.write_text("\n".join(lines))


# Convenience function for integration with Python SCE

def python_constraint_to_lean(python_constraint) -> str:
    """
    Convert Python Constraint object to Lean 4 code.

    Args:
        python_constraint: Python Constraint from SCE

    Returns:
        Lean 4 code

    Example:
        >>> from core.symbolic_constraint_engine import Constraint
        >>> c = Constraint(
        ...     id="temp_max",
        ...     type=ConstraintType.HARD,
        ...     description="Temperature < 1000",
        ...     formalization="T < 1000",
        ...     source="user"
        ... )
        >>> lean_code = python_constraint_to_lean(c)
    """
    type_map = {
        "hard": "hard",
        "soft": "soft",
        "preference": "preference"
    }

    return generate_lean_constraint(
        id=python_constraint.id,
        type=type_map.get(python_constraint.type.value, "hard"),
        description=python_constraint.description,
        formalization=python_constraint.formalization,
        dependencies=python_constraint.dependencies,
        source=python_constraint.source
    )


if __name__ == "__main__":
    # Demonstration
    print("Lean 4 Generator")
    print("=" * 50)

    # Generate example constraint
    lean_code = generate_lean_constraint(
        id="temp_max",
        type="hard",
        description="Temperature must be less than 1000°C",
        formalization="forall (T : Real), T < 1000",
        dependencies=[],
        source="user_prompt"
    )

    print("\nExample Constraint:")
    print(lean_code)

    # Generate contradiction theorem
    theorem_code = generate_contradiction_theorem("temp_max", "temp_min")
    print("\nExample Theorem:")
    print(theorem_code)

    print("\n[OK] Lean 4 generator working")
