"""
Auto-generated Extraction Prompt with Embedded Models
Generated by Knowledge Extraction Agent
This file contains a complete, self-contained extraction prompt system.
"""

EXTRACTION_PROMPT = """
TASK: AI Consultancy Reports

EXTRACTION TASK:
to extract structured information from AI consultancy reports

EMBEDDED PYDANTIC MODELS:
```python
```python
from pydantic import BaseModel, Field, field_validator
from enum import Enum
from typing import List

class CompanyType(str, Enum):
    STARTUP = "startup"
    ESTABLISHED = "established"

class AiMaturityLevel(str, Enum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"

class AiField(str, Enum):
    GENERATIVE_AI = "Generative AI"
    MACHINE_LEARNING = "machine learning"
    PREDICTIVE_ANALYTICS = "predictive analytics"
    RULE_BASED_SYSTEMS = "Rule-based systems"
    OTHER = "Other"

class CompanyDomain(str, Enum):
    ARTS_ENTERTAINMENT = "Arts & entertainment"
    AUTOMOTIVE = "Automotive"
    BUSINESS_ENHANCEMENT = "Business enhancement"
    CONSTRUCTION = "Construction"
    CULTURAL_CREATIVE_INDUSTRIES = "Cultural & creative industries"
    DEFENSE = "Defense"
    EDUCATION_TRAINING = "Education & training"
    ENVIRONMENT_SUSTAINABILITY = "Environment & sustainability"
    FINANCE = "Finance"
    HEALTHCARE_WELLBEING = "Healthcare & wellbeing"
    IMMIGRATION = "Immigration"
    MANUFACTURING = "Manufacturing"
    PROPERTY_REAL_ESTATE = "Property and real estate sector"
    SECURITY = "Security"
    SMART_CITIES = "Smart cities"
    TRANSPORT_LOGISTICS = "Transport & logistics"
    TRAVEL_TOURISM = "Travel & tourism"

class ServicesSought(str, Enum):
    AI_ROADMAP_DESIGN = "AI roadmap design"
    TECHNICAL_GUIDANCE = "technical guidance"
    PROOF_OF_CONCEPT_DEVELOPMENT = "proof of concept development"
    STUDENT_THESIS_PROJECT = "student thesis project"
    NETWORKING_SUPPORT = "networking support"
    DATA_COLLECTION = "data collection"

class AIConsultancyReportsInfo(BaseModel):
    companyname: str = Field(..., description="The name of the company receiving consultancy")
    expertnames: List[str] = Field(..., description="Names of the experts who provided consultancy")
    customermanagername: str = Field(..., description="Name of the customer manager")
    consultancydate: str = Field(..., description="Date when the consultancy took place")
    companytype: CompanyType = Field(..., description="Type of company based on maturity")
    aimaturitylevel: AiMaturityLevel = Field(..., description="Company's current AI maturity level")
    aifield: AiField = Field(..., description="The AI field the company is interested in")
    intendedaiidea: str = Field(..., description="Company's intended AI idea described in a concise phrase")
    companydomain: CompanyDomain = Field(..., description="The domain in which the company operates")
    targetgroups: List[str] = Field(..., description="Company's target groups or customer segments")
    servicessought: List[ServicesSought] = Field(..., description="Services that the company is seeking from the consultancy")
    keyrecommendations: List[str] = Field(..., description="Key recommendations provided by the experts")

    @field_validator('expertnames')
    @classmethod
    def validate_expertnames(cls, v):
        if not isinstance(v, list):
            raise ValueError('expertnames must be a list')
        return v

    @field_validator('targetgroups')
    @classmethod
    def validate_targetgroups(cls, v):
        if not isinstance(v, list):
            raise ValueError('targetgroups must be a list')
        return v

    @field_validator('servicessought')
    @classmethod
    def validate_servicessought(cls, v):
        if not isinstance(v, list):
            raise ValueError('servicessought must be a list')
        return v

    @field_validator('keyrecommendations')
    @classmethod
    def validate_keyrecommendations(cls, v):
        if not isinstance(v, list):
            raise ValueError('keyrecommendations must be a list')
        return v
```
```

CRITICAL EXTRACTION RULES:
1. ACCURACY & VERIFICATION:
   - Extract information ONLY from the provided text
   - Never fabricate, infer, or guess any information
   - Use 'n/a' for any fields where information is not explicitly stated
   - Verify all extracted data against the source text
   - Maintain exact values, dates, and numerical figures as written

2. DATA HANDLING:
   - For dates: Use DD-MM-YYYY format when possible
   - For numbers: Preserve original precision and units
   - For text: Maintain original spelling and capitalization
   - For lists: Extract all relevant items, remove duplicates
   - For enums: Choose ONLY from the specified options AND return the STRING VALUE, not the enum member name
   - For the extracted fields whose length exceeds 30 words, summarize their text into less than 30 words comprising very brief key phrases separated by semi-colon.

3. FIELD VALIDATION:
   - Enum fields must match one of the specified values exactly
   - For enum fields: Return the STRING VALUE (e.g., "moderate") NOT the enum member name (e.g., "MODERATE")
   - List fields should contain valid, non-empty items
   - Numerical fields should be valid numbers in correct format

4. ENUM FIELD HANDLING (CRITICAL):
   - For enum fields, ALWAYS return the string value, NEVER the enum member name
   - Example: For AiMaturityLevel enum, return "moderate" NOT "MODERATE"
   - Example: For CompanyType enum, return "startup" NOT "STARTUP"
   - Example: For AiField enum, return "machine learning" NOT "MACHINE_LEARNING"
   - The JSON output must contain the actual string values that match the enum definitions

5. QUALITY ASSURANCE:
   - Double-check all extracted information against source
   - Ensure no information is duplicated across fields
   - Verify that field types match the expected data types
   - Confirm that all required fields are addressed
   - Validate that enum selections are from available options
   - CRITICAL: Verify enum fields return string values, not member names


OUTPUT FORMAT:
Return the extracted information as a JSON object that exactly matches the AIConsultancyReportsInfo structure shown above.

CRITICAL: All JSON field names MUST be in snake_case format (lowercase with underscores) to match the model exactly.
For example: "due_date", "bank_name", "car_type" - NOT "Due date", "bank name", "car type"

Example output structure:
```json
{
  "field_name_1": "extracted_value_or_n/a",
  "field_name_2": ["list", "of", "values"],
  "field_name_3": "enum_option_or_n/a"
}
```

VALIDATION CHECKLIST:
Before returning your response, verify:
- All required fields are populated or marked 'n/a'
- All enum fields contain valid options only AND return STRING VALUES (not member names)
- All numerical fields contain valid numbers
- All date fields follow proper format
- No information is fabricated or inferred
- JSON structure matches the model exactly
- Field names match the model exactly (snake_case)
- Data types are appropriate for each field
- CRITICAL: Enum fields return values like "moderate", "startup", "machine learning" NOT "MODERATE", "STARTUP", "MACHINE_LEARNING"

FINAL INSTRUCTIONS:
- Process the document systematically
- Extract information field by field as specified above
- Maintain accuracy over completeness
- When in doubt, use 'n/a' rather than guessing
- Return only the JSON object with extracted data
- Ensure the output can be parsed as valid JSON
"""

def get_extraction_prompt():
    """Return the complete extraction prompt with embedded models"""
    return EXTRACTION_PROMPT
